Apicurio/apicurio-registry

distro/openshift-template/apicurio-registry-template-kafka.yml
tests/src/main/java/io/apicurio/tests/RegistryFacade.java

- apicurio-registry-template-kafka.yml exposing port of registries
- This PR adding external listener to be able communicate with registries outside of the cluster.

[MO] - [template] -> exposing cluster

---

app/src/main/java/io/apicurio/registry/content/ContentCanonicalizer.java
app/src/main/java/io/apicurio/registry/content/ContentCanonicalizerFactory.java
app/src/main/java/io/apicurio/registry/content/canon/AvroContentCanonicalizer.java
app/src/main/java/io/apicurio/registry/content/canon/JsonContentCanonicalizer.java
app/src/main/java/io/apicurio/registry/content/canon/NoOpContentCanonicalizer.java
app/src/main/java/io/apicurio/registry/metrics/PersistenceExceptionLivenessCheck.java
app/src/main/java/io/apicurio/registry/metrics/PersistenceTimeoutReadinessCheck.java
app/src/main/java/io/apicurio/registry/metrics/ResponseErrorLivenessCheck.java
app/src/main/java/io/apicurio/registry/metrics/ResponseTimeoutReadinessCheck.java
app/src/main/java/io/apicurio/registry/storage/impl/AbstractMapRegistryStorage.java
app/src/test/java/io/apicurio/registry/ArtifactsResourceTest.java
app/src/test/java/io/apicurio/registry/content/ContentCanonicalizerFactoryTest.java
app/src/test/resources/application.properties
common/src/main/java/io/apicurio/registry/rest/ArtifactsResource.java
storage/jpa/src/main/java/io/apicurio/registry/storage/impl/jpa/JPARegistryStorage.java
storage/streams/src/main/java/io/apicurio/registry/streams/StreamsRegistryStorage.java

This is a modified version of @alesj's implementation.  It does not store the canonical content.  Instead, it pushes the conversion of content from as-is to canonical format only when matching by content.  So the canonicalizer is only run when matching.  Original content is always stored.
A refinement is still probably required - to hash the canonical content and store the hash for fast initial comparison.  That is not yet done.

Get Meta-Data By Content now uses canonicalized content

---

docs/assemblies/getting-started/as_intro-to-the-registry.adoc
docs/modules/getting-started/c_intro-to-registry.adoc
docs/modules/getting-started/p_installing-registry-in-memory-storage.adoc
docs/modules/getting-started/p_installing-registry-jpa-storage.adoc
docs/modules/getting-started/p_installing-registry-kafka-kubernetes-storage.adoc
docs/modules/getting-started/p_installing-registry-kafka-storage.adoc
docs/modules/getting-started/p_installing-registry-kafka-streams-storage.adoc

Tidy up conditional text for branding and curl examples

tidy up conditions and examples

---

utils/converter/src/main/java/io/apicurio/registry/utils/converter/ExtJsonConverter.java

The `ExtJsonConverter` is not configurable from extrenal properties

Invalid super method called

---

app/src/main/java/io/apicurio/registry/ccompat/rest/CompatibilityResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/ConfigResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/ModeResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/SchemasResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/SubjectVersionsResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/SubjectsResource.java
app/src/main/java/io/apicurio/registry/ibmcompat/api/Api.java
app/src/main/java/io/apicurio/registry/ibmcompat/api/ApiService.java
app/src/main/java/io/apicurio/registry/ibmcompat/api/impl/ApiServiceImpl.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/AnyOfStateModificationEnabledModification.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/EnabledModification.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/NewSchema.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/NewSchemaVersion.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/Schema.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaInfo.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaListItem.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaState.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaSummary.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaVersion.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/StateModification.java
app/src/test/java/io/apicurio/registry/ConfluentClientTest.java
app/src/test/java/io/apicurio/registry/SerdeMixTest.java
app/src/test/java/io/apicurio/registry/SubjectsResourceTest.java
app/src/test/java/io/apicurio/registry/cluster/ClusterIT.java
app/src/test/java/io/apicurio/registry/ibmcompat/IBMClientTest.java
app/src/test/java/io/apicurio/registry/ibmcompat/SchemaRegistryRestAPIClient.java
tests/src/main/java/io/apicurio/tests/serdes/KafkaClients.java
tests/src/main/java/io/apicurio/tests/utils/subUtils/ArtifactUtils.java
tests/src/main/java/io/apicurio/tests/utils/subUtils/GlobalRuleUtils.java
tests/src/test/java/io/apicurio/tests/BaseIT.java

They are now:  `/ccompat` and `/ibmcompat`

Renamed the confluent and ibm rest compatibility endpoints

---

app/pom.xml
app/src/main/java/io/apicurio/registry/content/ContentCanonicalizerFactory.java
app/src/main/java/io/apicurio/registry/content/canon/KafkaConnectContentCanonicalizer.java
app/src/main/java/io/apicurio/registry/rules/compatibility/ArtifactTypeAdapterFactory.java
app/src/main/java/io/apicurio/registry/rules/validity/ContentValidatorFactory.java
app/src/main/java/io/apicurio/registry/rules/validity/KafkaConnectContentValidator.java
app/src/main/java/io/apicurio/registry/util/ArtifactTypeUtil.java
app/src/test/java/io/apicurio/registry/content/ContentCanonicalizerFactoryTest.java
app/src/test/java/io/apicurio/registry/rules/validity/KafkaConnectContentValidatorTest.java
app/src/test/resources/io/apicurio/registry/rules/validity/kconnect-invalid.json
app/src/test/resources/io/apicurio/registry/rules/validity/kconnect-valid.json
common/src/main/java/io/apicurio/registry/rest/ArtifactsResource.java
common/src/main/java/io/apicurio/registry/rest/beans/ArtifactMetaData.java
common/src/main/java/io/apicurio/registry/rest/beans/Rule.java
common/src/main/java/io/apicurio/registry/rest/beans/VersionMetaData.java
common/src/main/java/io/apicurio/registry/types/ArtifactType.java
common/src/main/resources/META-INF/openapi.json
utils/converter/src/main/java/io/apicurio/registry/utils/converter/ExtJsonConverter.java

Kafka Connect uses a schema format that is JSON based but is not JSON Schema.  It's also apparently not Avro, but it's similar to Avro.  This PR adds registry support for this JSON based schema language.

Added support for Kafka Connect schemas

---

app/src/test/java/io/apicurio/registry/AbstractRegistryTestBase.java

Throw RuntimeException instead of NPE, @alesj fyi
requested in https://github.com/Apicurio/apicurio-registry/pull/265#pullrequestreview-356636483

Throw RuntimeException instead of NPE

---

storage/jpa/src/main/java/io/apicurio/registry/storage/impl/jpa/JPARegistryStorage.java

using Postgres as storage backend, get artifact by global id `/ids/{globalId}` and get artifact by version `/artifacts/{artifactId}/versions/{version}` fail due to Large Objects exception as below. The solution is to wrap the call in `@Transactional` annotation (discussion here https://stackoverflow.com/questions/3164072/large-objects-may-not-be-used-in-auto-commit-mode)
I applied the fix in my own deployment and it confirmed to fix the issue.
Exception stacktrace:
```
[io.api.reg.res.RegistryExceptionMapper] (executor-thread-1) An unexpected server error was encountered.: io.apicurio.registry.storage.RegistryStorageException: An unexpected server error was encountered.
at io.apicurio.registry.storage.impl.jpa.JPARegistryStorage.getArtifactMetaData(JPARegistryStorage.java:404)
at …
```

fix PSQL Large objects exception

---

distro/openshift-template/apicurio-registry-template-streams.yml
storage/streams/src/main/java/io/apicurio/registry/streams/diservice/DistributedService.java

KS NPE, better exception for #306

---

app/src/main/java/io/apicurio/registry/rest/ArtifactsResourceImpl.java
client/src/main/java/io/apicurio/registry/client/CachedRegistryService.java
common/src/main/java/io/apicurio/registry/rest/ArtifactsResource.java
common/src/main/resources/META-INF/openapi.json

the method `getArtifactIds()` is there, but it is not defined in the `openapi.json`. This PR adds the GET endpoint to return all published artifacts, and links it to the existing JPA implementation

JPA storage can return list of all artifacts

---

.circleci/config.yml
tests/src/main/java/io/apicurio/tests/serdes/KafkaClients.java
tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/MetadataConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java

This PR introduces several changes for tests, which are running against a stable instance of Registry and Kafka, for example in OCP/Kubernetes cluster. 
It fixes only protobuf tests because 30s timeout wasn't enough in case of use Kafka from Strimzi. Other fixes cannot be tested atm, because confluent API return wrong values. However, from my POV these changes are needed to run without failures.

Add fixes for tests running against stable instance

---

distro/connect-converter/pom.xml
distro/connect-converter/src/assembly/converter-distribution.xml

Current content of Kafka connect zip is:
<details>
<summary><b>content.zip</b></summary>
<pre><code>
annotations-13.0.jar
aopalliance-repackaged-2.6.1.jar
apicurio-registry-client-1.2.0-SNAPSHOT.jar
apicurio-registry-common-1.2.0-SNAPSHOT.jar
apicurio-registry-utils-converter-1.2.0-SNAPSHOT.jar
apicurio-registry-utils-serde-1.2.0-SNAPSHOT.jar
avro-1.9.2.jar
btf-1.2.jar
cdi-api-2.0.jar
checker-qual-2.5.2.jar
commons-compress-1.19.jar
connect-json-2.4.0.jar
failureaccess-1.0.1.jar
geronimo-config-impl-1.2.2.jar
guava-27.0.1-jre.jar
hk2-api-2.6.1.jar
hk2-locator-2.6.1.jar
hk2-utils-2.6.1.jar
istack-commons-runtime-3.0.10.jar
jackson-annotations-2.10.2.jar
jackson-core-2.10.2.jar
jackson-coreutils-1.6.jar
jackson-databind-2.10.2.jar
jackson-datatype-jdk8-2.10.2.jar …

Limit content of the Kafka Connect distribution

---

app/pom.xml
tests/pom.xml
tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java

Moves RegistryConverterTest to tests module and modifies it to be a IT so can be included in QE process

move converters test to tests module

---

app/src/main/java/io/apicurio/registry/rest/ArtifactsResourceImpl.java
app/src/main/java/io/apicurio/registry/util/ContentTypeUtil.java
app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
app/src/test/java/io/apicurio/registry/ArtifactsResourceTest.java
app/src/test/java/io/apicurio/registry/util/ContentTypeUtilTest.java
app/src/test/resources/io/apicurio/registry/openapi-empty.yaml
app/src/test/resources/io/apicurio/registry/sample.wsdl
common/src/main/java/io/apicurio/registry/rest/ArtifactsResource.java
common/src/main/java/io/apicurio/registry/types/ArtifactMediaTypes.java
ui/packages/models/src/artifactTypes.model.ts
ui/packages/models/src/contentTypes.model.ts
ui/packages/registry/src/app/components/common/artifactTypeIcon.tsx
ui/packages/registry/src/app/pages/artifactVersion/artifactVersion.tsx
ui/packages/registry/src/app/pages/artifacts/components/uploadForm/uploadForm.tsx
ui/packages/services/src/artifacts/artifacts.service.ts
ui/packages/services/src/baseService.ts
ui/packages/services/src/downloader/downloader.service.ts

We now accept content-type of YAML and XML when adding content to the registry.
YAML content can be sent for JSON-style artifacts (Avro, OpenAPI, AsyncAPI, etc).
The UI now sends the right content-type for whatever it's sending (XML, JSON, YAML, Protobuf).
YAML content is transformed to JSON immediately by the server, so will be stored as JSON even if sent as YAML.

Better YAML and XML support

---

tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/AllArtifactTypesIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

Signed-off-by: Lukas Kral <lukywill16@gmail.com>
This PR will fix some problems with IT tests:
- first thing I fixed was connection for Confluent client -> the problem here was that we used always `DEFAULT_REGISTRY_HOST` which was set to `localhost` -> so when we ran the tests on Jenkins x Openshift machine, where was SR deployed too, the tests were simply failling
- second problem was in cleaning -> when we had tests for creating some rules or artifacts (for example) and didn't remove it, the other tests were failing because of the rules or because artifact were already created
- third thing that I done was disabling test `createAndDeleteMultipleSchemas` - the problem is - how I mentioned in #475 - that when we wanted to create x schemas at once, the connection to registry simply died - …

[registry][fixes] Add cleanup, fix connection for Confluent client

---

tests/src/main/java/io/apicurio/tests/Constants.java
tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/ConfluentBaseIT.java
tests/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/AllArtifactTypesIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/MetadataConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

* create confluent base class so cleaning methods are only called when confluence tests are executed
* check health endpoint to way for registry to be ready before starting testsuite
* added tests to verify rules are deleted when artifact is deleted
Test `SchemasConfluentIT#testCreateDeleteSchemaRuleIsDeleted` is showing a bug in the rules deletion when an artifact is deleted.

 Several improvements to confluent compatibility tests

---

app/src/main/java/io/apicurio/registry/metrics/RestMetricsInterceptor.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/LoadTest.java

I've created a basic load test that creates and deletes 1000 artifacts concurrently to try to reproduce the issues we've seen of the api freezing, I had no luck reproducing the issue but found a bug in `RestMetricsInterceptor`

fix concurrency issue and add basic load test

---

storage/streams/src/main/java/io/apicurio/registry/streams/StreamsRegistryStorage.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/LoadIT.java

* rename LoadTest, increase timeout and reduce number of artifacts created
* fix bug in streams storage where artifact rules weren't when artifact is deleted
increase timeout, this bug was reproducible in tests module running against streams storage in test `RulesResourceIT.testRulesDeletedWithArtifact`

Fix various issues

---

utils/tests/src/main/java/io/apicurio/registry/utils/tests/RegistryServiceExtension.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

This is needed for QE CI so tests metadata reporting will work properly, currently every test is run twice because is run with two variants of the registry client. I added a new env var to be able to control this so tests in QE CI are not executed twice

tests - add env var to be able to manage tests invocation

---

tests/pom.xml

Dependency `kafka-protobuf-serializer` includes `com.github.everit-org.json-schema:org.everit.json.schema:jar:1.12.1` which fails to be pulled in internal CI, I would love to fix the issue I have in internal CI but I figured out there is no need to include `kafka-protobuf-serializer` in tests pom, so I removed it and some others that are not needed

tests - remove unnecessary dependencies

---

tests/pom.xml
tests/src/test/java/io/apicurio/tests/BaseIT.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/RegistryServiceExtension.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/SimpleDisplayName.java

This changes simplify the name of testcases in xunit reports and are needed for QE to easily be able to do test reporting.

tests - fix tests name in test reporting

---

tests/src/main/java/io/apicurio/tests/serdes/KafkaClients.java
tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/ConfluentBaseIT.java
tests/src/test/java/io/apicurio/tests/converters/KafkaConnectConverterIT.java
tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
tests/src/test/java/io/apicurio/tests/serdes/apicurio/BasicApicurioSerDesIT.java
tests/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/AllArtifactTypesIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/LoadIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/MetadataIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java
tests/src/test/java/io/apicurio/tests/ui/DeleteArtifactIT.java
tests/src/test/java/io/apicurio/tests/ui/UploadArtifactsIT.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/RegistryServiceExtension.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/RegistryServiceTest.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

Changes `TestUtils.getRegistryUrl` to `TestUtils.getRegistryApiUrl` to fix an issue with `getRegistryUIUrl` where the replacement done (from /api to /ui) produced issues in cases where the registry host started with `http://apicurio...` (which is pretty common :) )
This PR also removes the fields from `RegistryServiceTest` annotation because they were not being used and from my POV they weren't useful

tests - fix getRegistryUrl

---

app/src/main/resources/application.properties

When doing local tests, I wasn't able to change the http port for quarkus.
I tried to run quarkus:dev goal setting the HTTP_PORT environment variable but it didn't change the port
when running.
Looking at quarkus configuration guide https://quarkus.io/guides/config#create-the-configuration I see that
profile properties start with '%'.
However, '@' was being used for the quarkus.http.port which was a typo and prevented the http port
for quarkus being configurable.
I think this might be a typo, unless I'm missing some way to configure the port when the property starts with '@'.
What do you think?

Fix configurable quarkus http port

---

utils/serde/src/main/java/io/apicurio/registry/utils/serde/strategy/AbstractCrudIdStrategy.java

Related to issue #687  not about cache request, but after review with partner @antonmry, this simple change made possible update the artifact when the schema is different.
Three strategies extends `AbstractCrudIdStrategy`:
- `AutoRegisterIdStrategy`: always run update, no affectation by this changed
- `GetOrCreateIdStrategy`: if artifact-id exists, get the last global-id (don't check if schema is equals), otherwise create artifact with the schema. No affectation by this change: if artifact not found, create it (no possible update)
- `CachedSchemaIdStrategy`: If artifact-id exists but schema isn't equals gets a 404 response, try to create artifact and fails (the artifact exists). **The change affects only this case**: try to create artifact, really add a new version of schema, and gets the …

Crud strategies, if not found, create artifact or update schema (#687)

---

app/src/main/java/io/apicurio/registry/metrics/RestMetricsResponseFilter.java
app/src/main/java/io/apicurio/registry/metrics/RestMetricsResponseFilteredNameBinding.java
app/src/main/java/io/apicurio/registry/rest/RegistryApplication.java

Hi,
As part of https://issues.redhat.com/browse/IPT-109, https://issues.redhat.com/browse/IPT-155 I'm trying to come up with a solution on reporting metrics with the response codes status and durations (latencies) in the REST API.
I've taken a look at the codebase to see how API rest is exposed and this is how I think it works:
It seems that metrics in service-registry are reported/exposed using the `Microprofile` (https://projects.eclipse.org/projects/technology.microprofile) Java library. Metrics are exposed on the `/metrics` endpoint.
The REST Web Services API is exposed using `JAX-RS` (https://docs.oracle.com/javaee/7/api/javax/ws/rs/package-summary.html) . The REST API is exposed in the `/api` endpoint.
Based on this I explored the following approaches:
* Trying to use some possible …

Implement HTTP Response status code metrics reporting for REST API

---

app/src/main/java/io/apicurio/registry/ibmcompat/api/Api.java
app/src/main/java/io/apicurio/registry/ibmcompat/api/ApiService.java
app/src/main/java/io/apicurio/registry/ibmcompat/api/impl/ApiServiceImpl.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/AnyOfStateModificationEnabledModification.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/EnabledModification.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaInfo.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaModificationPatch.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaState.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/SchemaVersion.java
app/src/main/java/io/apicurio/registry/ibmcompat/model/StateModification.java
app/src/test/java/io/apicurio/registry/ibmcompat/IBMCompatApiTest.java
app/src/test/resources/io/apicurio/registry/ibmcompat/avro.json

- This commit improves the data returned by the ibmcompat API GET
endpoints to include metadata already stored with the artifact.
- It also improves the ibmcompat API POST endpoints by returning
metadata stored with the artifact.
- It also adds a set of initial tests for the functionality that follow
the ccompat API and artifact API tests.
- It also improves the ibmcompat API PATCH endpoints by setting the
metadata stored with the artifact.

Enhance ibmcompat API methods

---

.github/scripts/docker-prune.sh
app/pom.xml
app/src/test/java/io/apicurio/registry/RegistryClientTest.java
app/src/test/java/io/apicurio/registry/auth/KeycloakResourceManager.java
client/pom.xml
client/src/main/java/io/apicurio/registry/client/GenericClient.java
client/src/main/java/io/apicurio/registry/client/HeaderDecorator.java
client/src/main/java/io/apicurio/registry/client/RegistryClient.java
client/src/main/java/io/apicurio/registry/client/auth/Auth.java
client/src/main/java/io/apicurio/registry/client/auth/AuthConfig.java
client/src/main/java/io/apicurio/registry/client/auth/AuthProvider.java
client/src/main/java/io/apicurio/registry/client/auth/AuthStrategy.java
client/src/main/java/io/apicurio/registry/client/auth/HeaderDecorator.java
client/src/main/java/io/apicurio/registry/client/auth/KeycloakAuth.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/RegistryServiceExtension.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

Authentication/authorization proof of concept: https://github.com/Apicurio/apicurio-registry/issues/674
Poc with keycloak:
https://github.com/carlesarnal/apicurio-registry/tree/auth-poc-674
Update Registry Client to support a client method with a configurable authentication mechanism. Config is provided as a parameter in the create/cached method. Currently, it only supports keycloak auth strategy, but it can be extended to support other mechanisms. 
Example:
```
String registryUrl = "http://0.0.0.0:8080/api";
AuthConfig config = new AuthConfig.Builder(AuthProvider.KEYCLOAK)
.setServerUrl("http://127.0.0.1:8081/auth")
.setClientId("admin-cli")
.setRealm("master")
.setUsername("admin")
.setPassword("admin")
.Build();
RegistryService service = RegistryClient.cached(registryUrl, config);
```

Adding support for auth for the registry client

---

app/src/main/java/io/apicurio/registry/storage/ArtifactStateExt.java
app/src/test/java/io/apicurio/registry/ArtifactStateTest.java
storage/asyncmem/src/main/java/io/apicurio/registry/asyncmem/AsyncInMemoryRegistryStorage.java

- This commit allows an artifact to transition from the `Deprecated`
state to either the `Enabled` or `Disabled` states. This allows users
who have accidentally deprecated a schema to re-enable it, or it allows
a deprecated schema to become disabled so that clients can no longer use
it.
See initial discussion in issue #722

Allow transition from Deprecated state to Enabled or Disabled states

---

app/src/main/java/io/apicurio/registry/ibmcompat/api/Api.java
app/src/main/java/io/apicurio/registry/ibmcompat/api/impl/ApiServiceImpl.java
app/src/main/java/io/apicurio/registry/ibmcompat/api/impl/ApiUtil.java
app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
app/src/test/java/io/apicurio/registry/ibmcompat/IBMCompatApiTest.java

- This commit updates the ibmcompat API so that metadata that does not
have an equivalent in the artifacts API is stored in and retrieved from
the `properties` metadata field.
- It also updates the API path handling to allow either the schema name
or schema ID (which is the lower-cased schema name) to be used to
address the artifact.

Store ibmcompat API metadata in properties field

---

tests/pom.xml
tests/src/main/java/io/apicurio/tests/Constants.java
tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/ConfluentBaseIT.java
tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
tests/src/test/java/io/apicurio/tests/serdes/apicurio/BasicApicurioSerDesIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/AllArtifactTypesIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/LoadIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/MetadataIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/MetadataConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java
tests/src/test/java/io/apicurio/tests/ui/UploadArtifactsIT.java

Adds a new test profile used in QE pipelines for quickly testing main functionalities.
Fix a minor issue in confluent api tests cleanup and disables LoadIT test because it is flaky and should be reworked

tests - add new profile and disable LoadIT test

---

utils/maven-plugin/pom.xml
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/DownloadRegistryMojo.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
utils/maven-plugin/src/main/java/io/apicurio/registry/types/ArtifactExtensionType.java
utils/maven-plugin/src/test/resources/test-build/pom.xml

Automatic extension detection in the maven plugin download goal

---

app/src/main/resources/application.properties

Fixes #768 
The following env variables can be used now for overriding topic names
- REGISTRY_STREAMS_TOPOLOGY_STORAGE_TOPIC
- REGISTRY_STREAMS_TOPOLOGY_GLOBAL_ID_TOPIC

Allow users to define Kafka Streams topic names

---

utils/serde/src/main/java/io/apicurio/registry/utils/serde/AbstractSerde.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AvroKafkaDeserializer.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AvroSerde.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/JsonSchemaSerde.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/ProtobufSerde.java

- This commit adds three implementations of Kafka's Serde interface
which provides a wrapper for a Serializer and Deserializer. The
three implementations wrap the AvroKafkaSerializer/Deserializer, the
JsonSchemaKafkaSerializer/Deserializer and the
ProtobufKafkaSerializer/Deserializer. See issue #641 for more info.
- It also adds a workaround for the issue where Kafka Deserializers
throw a `java.lang.IllegalStateException: Method not supported on an
outbound message` error (see #702 and #808) due to the use of
JAX-RS classes in the CompatibleClient class.

Add Kafka Serde implementations for Kafka Streams applications

---

rest-client/src/main/java/io/apicurio/registry/client/CompatibleClient.java
rest-client/src/main/java/io/apicurio/registry/client/RegistryRestClientFactory.java
rest-client/src/main/java/io/apicurio/registry/client/RegistryRestClientImpl.java
rest-client/src/main/java/io/apicurio/registry/client/request/Config.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AbstractKafkaSerDe.java

- This commit adds support for HTTPS calls to apicurio-registry with or
without TLS client auth. Supported configuration keys are:
- `apicurio.registry.request.ssl.truststore.location`
- `apicurio.registry.request.ssl.truststore.password`
- `apicurio.registry.request.ssl.truststore.type`
- `apicurio.registry.request.ssl.keystore.location`
- `apicurio.registry.request.ssl.keystore.password`
- `apicurio.registry.request.ssl.keystore.type`
- `apicurio.registry.request.ssl.key.password`
- It also refactors the request header handling code to move it out of
the serdes code and into the RegistryRestClient, so all clients can use
it. This includes the basic auth handling for when the username and
password are encoded in the URL.

Add TLS auth support to rest client calls

---

app/src/main/java/io/apicurio/registry/rest/ArtifactsResourceImpl.java
ui/packages/registry/src/app/pages/artifactVersion/artifactVersion.tsx
ui/packages/registry/src/app/pages/artifacts/components/artifactList/artifactList.css
ui/packages/registry/src/app/pages/artifacts/components/artifactList/artifactList.tsx

Updated the UI to no longer break when encountering disabled artifacts.
I have not yet added actual support for enabling/disabling (or deprecating/undeprecating) via the UI yet.  But at least the UI won't break when it sees disabled content.
I did add a label/badge to the artifact listing that will display when an artifact is disabled or deprecated.

Support disabled artifacts in the UI listing/details

---

.github/workflows/verify.yaml

This will help to quickly identify if there was a problem building the images or with the kubernetes tests, as both things were in the same job

Kubernetes Tests to separated job

---

.github/workflows/kubernetes-tests.yaml

Adds a new GH actions workflow to run the kubernetes tests on demand, it builds the docker images (without pushing them to docker hub) and loads it into the kubernetes cluster used to run the tests.

kubernetes tests - manual trigger

---

tests/src/test/java/io/apicurio/tests/selenium/SeleniumChromeExtension.java

UI tests were failing when executed from the kubernetes test suite, that was because selenium was deployed in a container that cannot access the kubernetes cluster deployed for k8s testsuite (accessible through localhost)...
With this changes new tests assume that if env var "EXTERNAL_REGISTRY" is true it means registry is deployed by someone else and selenium (required only for ui tests) is deployed by someone else as well. Selenium connection details are in env vars "SELENIUM_HOST" and "SELENIUM_PORT"
Because for k8s testsuite selenium is deployed inside kubernetes cluster in order to be able to access an apicurio-registry deployed inside same kubernetes cluster I had to add env vars "REGISTRY_SELENIUM_HOST" and "REGISTRY_SELENIUM_PORT" to be able to specify a reachable url to selenium

ui tests - fix selenium tests when run in k8s testsuite

---

common/src/main/java/io/apicurio/registry/utils/ConcurrentUtil.java
storage/infinispan/src/main/java/io/apicurio/registry/infinispan/InfinispanRegistryStorage.java
tests/src/main/java/io/apicurio/tests/RegistryFacade.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java

fixes "deleteGlobalRules" for infinispan storage, it was using the default "clear" method which indicates to not be used in production, actually it produced a race sometimes in tests making RulesResourceIT to fail.
This PR also changes RulesResourceIT tests to use the new rest client

fix infinispan global rules cleanup bug

---

app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
app/src/test/java/io/apicurio/registry/rules/defaultglobal/DefaultGlobalRulesProfile.java
app/src/test/java/io/apicurio/registry/rules/defaultglobal/DefaultGlobalRulesResourceTest.java

Created from #821  
- This commit uses a new implementation of the QuarkusTestProfile
interface to set a default global rule via configuration overrides. This
allows the default global rule functionality to be tested in the new
test class.

Add tests for default global rules

---

storage/sql/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/SearchedVersionMapper.java

When using SQL storage, the "version" property wasn't mapped from the ResultSet, causing the UI to not receive it, and listing empty version names in the UI dropdown. 
This also broke the navigation to different artifact versions using the dropdown since the URL ended up including "undefined" in the path.
Fix for issue https://github.com/Apicurio/apicurio-registry/issues/1015

Map the version property into the DTO exposed to the frontend for SearchedVersion

---

storage/ksql/src/main/java/io/apicurio/registry/storage/impl/ksql/KafkaSqlRegistryStorage.java
storage/ksql/src/main/java/io/apicurio/registry/storage/impl/ksql/sql/KafkaSQLSink.java
storage/ksql/src/main/java/io/apicurio/registry/storage/impl/ksql/sql/SQLRegistryStorage.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/GlobalIdGenerator.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/SqlGlobalIdGenerator.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
utils/sql/src/main/resources/io/apicurio/registry/storage/impl/sql/h2.ddl
utils/sql/src/main/resources/io/apicurio/registry/storage/impl/sql/postgresql.ddl

Implements the abstraction in the SQL storage to provide the globalId in the ksql storage the globalId is generated from the kafka record partition + offset (similarly to the streams impl)

ksql - generate globalId from kafka record

---

app/src/main/java/io/apicurio/registry/ccompat/dto/CompatibilityLevelDto.java
app/src/main/java/io/apicurio/registry/ccompat/dto/CompatibilityLevelParamDto.java
app/src/main/java/io/apicurio/registry/ccompat/rest/ConfigResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/impl/ConfigResourceImpl.java
app/src/test/java/io/apicurio/registry/ConfluentCompatApiTest.java

For the GET config calls, both the global and the subject ones, the Confluent API expect a `compatibility` field and return a `compatibilityLevel` field.
For the PUT config calls, both the global and the subjects ones, the Confluent API expect a `compatibility` field and return a `compatibility` field.
You have all the required info [here](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#config).

Fix compatibility level issue

---

app/src/main/java/io/apicurio/registry/rest/ArtifactsResourceImpl.java
app/src/main/java/io/apicurio/registry/storage/impl/AbstractMapRegistryStorage.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java

I noticed the `updateVersionMetaData` was not updating the labels and properties.
I also refactored a bit the method to handle the metadata update in the sql storage because I saw a possibility to remove some duplicated code

fix update metadata bug

---

utils/sql/src/main/resources/io/apicurio/registry/storage/impl/sql/h2.ddl
utils/sql/src/main/resources/io/apicurio/registry/storage/impl/sql/postgresql.ddl

Switched some of the DB indexes to be hash indexes instead of default b-tree indexes for faster identity lookups

Use hash DB indexes in some cases

---

app/src/main/java/io/apicurio/registry/rest/ArtifactsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/RegistryExceptionMapper.java
app/src/main/java/io/apicurio/registry/storage/InvalidArtifactIdException.java
common/src/main/java/io/apicurio/registry/utils/ArtifactIdValidator.java
rest-client/src/main/java/io/apicurio/registry/client/RegistryRestClientImpl.java
rest-client/src/main/java/io/apicurio/registry/client/exception/InvalidArtifactIdException.java
rest-client/src/main/java/io/apicurio/registry/client/service/ArtifactsService.java
rest-client/src/main/java/io/apicurio/registry/client/service/SearchService.java
tests/src/main/java/io/apicurio/tests/RegistryDeploymentManager.java
tests/src/main/java/io/apicurio/tests/utils/BaseHttpUtils.java
tests/src/main/java/io/apicurio/tests/utils/subUtils/ArtifactUtils.java
tests/src/test/java/io/apicurio/tests/selenium/resources/ArtifactListItem.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
tests/src/test/java/io/apicurio/tests/ui/DeleteArtifactIT.java
tests/src/test/java/io/apicurio/tests/ui/RegistryUITester.java
tests/src/test/java/io/apicurio/tests/ui/UploadArtifactsIT.java
tests/src/test/java/io/apicurio/tests/ui/pages/ArtifactDetailsPage.java
tests/src/test/java/io/apicurio/tests/ui/pages/ArtifactsListPage.java
tests/src/test/java/io/apicurio/tests/ui/pages/UploadArtifactDialog.java
ui/packages/registry/src/app/pages/artifacts/components/uploadForm/uploadForm.tsx

This PR implements the handling of special characters in artifactId in the UI, rest client and api backend.
After some investigation around react-router (used in the UI) and okhttp and retrofit (used in the rest client) I concluded to no longer allow non ASCII characters and the percentage simbol `&`  to be part of an artifactId 
The api now validates when creating an artifact if it's allowed, otherwise the backend returns http status 400
In the UI , react-router produced URI encoding issues that caused crashes in the web when the artifactId contained the character `%` , I have not been able to solve this by updating the router dependency so I decided to forbid the problematic character
The rest client had several issues handling special characters. 
`okhttp` does not allow to have …

special characters handling - % and non ASCII characters are now forbidden

---

storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlConfiguration.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlCoordinator.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlFactory.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlStorageProvider.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlSubmitter.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/sql/KafkaSqlSink.java

I had to restructure some things in order to make the Kafka message submitter injectable so that it could easily be used by the Sink, where it was needed in this use-case.
When reviewing this PR, the actual functional change is here:
https://github.com/Apicurio/apicurio-registry/pull/1108/files#diff-47a512339688aeb4390b3269d8c92a87ce49ed56916e0a88e0cde27717f4bdaf
There is a new try/catch block in the `processArtifactMessage` method - that is where the tombstone message is being sent on failure.  The rest of the changes are so that I could inject the message submitter into `KafkaSqlSink`.  :)

Refactoring to support more easily adding tombstone messages on failures

---

tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

There are several integration tests that have been failing in master for a while now, but always for the streams storage variant.
That indicates there are issues because of the asynchronous storage.
One issue was with `BasicApicurioSerDesIT.testEvolveAvroApicurio` , the problem was in `TestUtils.waitFor` that leaked an AssertionError
The other issue was with `ArtifactsIT.testAllowedSpecialCharactersCreateViaApi` that reported an http error with code 409, that lead to the process of artifacts cleanup after each test. This PR improves the cleanup process to ensure all artifacts are 100% removed after each test.

fix streams unstable tests

---

app/pom.xml
app/src/main/java/io/apicurio/registry/mt/TenantContext.java
app/src/main/java/io/apicurio/registry/mt/TenantContextImpl.java
app/src/main/java/io/apicurio/registry/mt/TenantRequestFilter.java
app/src/main/java/io/apicurio/registry/services/tenant/CustomTenantConfigResolver.java
app/src/main/resources/application.properties
app/src/test/java/io/apicurio/registry/storage/AbstractRegistryStorageTest.java
app/src/test/java/io/apicurio/registry/storage/MockTenantContext.java
app/src/test/java/io/apicurio/registry/storage/MultitenantRegistryProfile.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/api/RegistryTenantResource.java
multitenancy/tenant-manager-api/src/test/java/io/apicurio/multitenant/RegistryTenantResourceTest.java
multitenancy/tenant-manager-api/src/test/java/io/apicurio/multitenant/TenantManagerClientTest.java
multitenancy/tenant-manager-datamodel/src/main/java/io/apicurio/multitenant/datamodel/NewRegistryTenantRequest.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/sql/KafkaSqlSink.java
storage/kafkasql/src/test/java/io/apicurio/registry/storage/impl/sql/KafkaSqlRegistryStorageTest.java
storage/sql/src/test/java/io/apicurio/registry/storage/impl/sql/SqlRegistryStorageTest.java

This PR adds a vertx filter that allows the registry to accept requests at 
`/t/{tenantId}/api/...`
The registry still accepts requests at `/api/...` or '/health/...` ...
it also adds the property `registry.enable.multitenancy` to enable and disable this feature

tenant urls mapping

---

distro/connect-converter/pom.xml

types other than jar was not getting resolved by maven since the id specified in the descriptor was getting appended

fix: do not append assembly Id

---

app/src/main/resources/application.properties

Adds HTTP permission path for version 2 of the API.

V2 api auth support

---

app/src/test/java/io/apicurio/registry/RegistryClientV2Test.java
app/src/test/java/io/apicurio/registry/rest/v2/AdminResourceTest.java

AdminResourceTest#testLoggersCRUD was failing because of a conflict with RegistryClientV2Test. Now it should be fixed

fix testLoggersCRUD test

---

serdes/serde-common/src/main/java/io/apicurio/registry/serde/utils/Utils.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/AvroConverter.java

attempt to fix 
```
java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: io.apicurio.registry.serde.avro.AvroKafkaSerializer
at io.apicurio.registry.serde.utils.Utils.loadClass(Utils.java:65)
at io.apicurio.registry.serde.utils.Utils.instantiate(Utils.java:50)
at io.apicurio.registry.utils.converter.SerdeBasedConverter.configure(SerdeBasedConverter.java:72)
at io.apicurio.registry.utils.converter.AvroConverter.configure(AvroConverter.java:52)
at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:298)
at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:530)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1258)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$170 …
```

fix connect-converters

---

app/src/main/java/io/apicurio/registry/rest/DisableApisFilter.java
app/src/main/java/io/apicurio/registry/services/DisabledApisMatcherService.java
app/src/main/java/io/apicurio/registry/services/tenant/CustomTenantConfigResolver.java
app/src/test/java/io/apicurio/registry/ccompat/rest/ConfluentCompatApiTest.java
app/src/test/java/io/apicurio/registry/mt/MultitenancyNoAuthTest.java
app/src/test/java/io/apicurio/registry/mt/MultitenancyNoAuthTestProfile.java
app/src/test/java/io/apicurio/registry/rest/DisableApisFlagsTest.java
app/src/test/java/io/apicurio/registry/rest/DisableApisTestProfile.java
app/src/test/java/io/apicurio/registry/rest/MultipleRequestFiltersTestProfile.java
app/src/test/java/io/apicurio/registry/rest/MultitenancyAndDisabledApisTest.java

Implements #1236 and adds a few tests to verify the new functionality and the interation of several `ContainerRequestFilters` (multitenancy filter and disabled apis filter)

disable apis flag - list of regexps

---

app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
app/src/test/java/io/apicurio/registry/RegistryClientTest.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/selenium/resources/ArtifactListItem.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/UploadArtifactsIT.java
storage/streams/src/main/java/io/apicurio/registry/streams/StreamsRegistryStorage.java

The streams storage was handling the default group ("default" or null) incorrectly. It was returning a string "null" instead of null. I noticed this error in the UI tests.
This PR adds a test to verify all storages handle the default group the same way, plus some improvements in the UI tests that were failing.

fix streams storage default group handling and fix ui tests

---

app/src/main/java/io/apicurio/registry/logging/LoggingInterceptor.java

@Apicurio/developers all ok with this?  from the experience I have reading logs for test runs, I think our logs are too verbose, the logging interceptor is annoying sometimes

logging interceptor - log as trace, logs too verbose

---

app/src/main/java/io/apicurio/registry/mt/MultitenancyProperties.java
app/src/main/java/io/apicurio/registry/mt/TenantIdResolver.java
app/src/main/java/io/apicurio/registry/mt/TenantMetadataService.java
app/src/main/java/io/apicurio/registry/rest/RegistryApplicationServletFilter.java
app/src/main/java/io/apicurio/registry/services/DisabledApisMatcherService.java

This PR implements a check in `RegistryApplicationServletFilter` that disables the UI when the registry is deployed with multitenancy enabled.
If we want the UI to be used with multitenancy enableb (and with authentication working) the easiest way I can think of is to provide a UI server that will use some version of the `/ui/config.js` servlet to provide the specific tenantAuth info... so for this the issue #1313 will be kept open.

Disable UI when multitenancy is enabled

---

integration-tests/legacy-tests/src/test/java/io/apicurio/tests/serdes/apicurio/BasicApicurioSerDesIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/JsonSchemaMsgFactory.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/JsonSchemaSerdeIT.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractKafkaDeserializer.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/DefaultIdHandler.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/DefaultSchemaResolver.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/Legacy4ByteIdHandler.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/config/BaseKafkaDeserializerConfig.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/fallback/DefaultFallbackArtifactProvider.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/fallback/FallbackArtifactProvider.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/headers/DefaultHeadersHandler.java

This PR adds a new functionality to our serdes, specifically the deserializers. There is a new interface `FallbackArtifactProvider` that allows to implement custom strategies to try to lookup for a schema in the case the `SchemaResolver` fail to find an artifact. 
Wether it's because no globalId can be found in the kafka message or because the `SchemaResolver` failed to find an artifact in the registry for that globalId...
There is a DefaultFallbackArtifactProvider that uses hardcoded config properties.

serdes - fallback artifact reference provider

---

integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java

This PR attempt to fix a really weird bug, where if the globalId and contentId are the same the tests will fail.
Because those tests are testing negative scenarios of the contentId functionality...

fix serdes tests bug - contentId and globalId equals

---

integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/DefaultSchemaResolver.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/config/DefaultSchemaResolverConfig.java

This PR disables two tests that are currently failing in master, I spend quite some time troubleshooting them and they work fine in my laptop... I'll disable it for now
This PR also implements a small changes in the serdes, is a bug I noticed writing a quarkus application. Sometimes the user cannot control the type of the parameter that gets passed to the serdes, and so the version got passed as an Integer. The kafka class we use to handle the configurations failed if the parameter is not a string (in the case of the artifact version).

fix getExplicitArtifactVersion bug and disable flaky tests

---

integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryDeploymentManager.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryFacade.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java

This is a change needed for the kubernetes testsuite

integration-tests - only wait when registry deployed locally

---

.github/workflows/cli-release-macos.yaml
.github/workflows/cli-release-win64.yaml
.github/workflows/cli-release.yaml
.github/workflows/nightly-build.yaml
cli/README.md
cli/src/main/java/io/apicurio/registry/cli/EntryCommand.java
cli/src/main/java/io/apicurio/registry/cli/admin/ExportCommand.java
cli/src/main/java/io/apicurio/registry/cli/admin/ImportCommand.java
cli/src/main/resources/application.properties

This PR adds the import and export features to the CLI tool.
This PR also adds two new workflows for building the native executables of the CLI for linux, windows and macOS platforms.
The new workflows are triggered when a new release is created and they add the executables as assets of the release.

cli - import export commands

---

app/src/test/java/io/apicurio/registry/events/KafkaEventsTest.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryFacade.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ApicurioV2BaseIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/LoadBalanceRegistryClient.java
storage/kafkasql/pom.xml

This PR disables the kafka-events QuarkusTest when running kafkasql unit-tests, because of issues in GH actions due to running two kafka instances in containers.
This PR also improves the integration-tests, now it deploys 3 registry nodes locally and the load balancer client does a random load balancing. This is expected to provide a more realistic scenario...

integration-tests - more realistic clustered tests

---

app/src/main/java/io/apicurio/registry/ImportLifecycleBean.java
app/src/test/java/io/apicurio/registry/ImportLifecycleBeanTest.java
app/src/test/java/io/apicurio/registry/ImportLifecycleBeanTestProfile.java

resolve #1502 
This introduces the env variable `REGISTRY_IMPORT_URL` to provide the URL to a ZIP file containing the export of a registry.
In an OCP instance, it could be used both:
- "dinamically" using an init container to download the ZIP file and adding the env variable value to the Deployment
- "statically" creating a container image with a bundled ZIP file (sample Dockerfile in [1])
~The PR is missing the tests and I suppose the package and the name of the class should be discussed as well but I would like to share something working to explore with you such a solution.~ fixed
[1]
```
FROM apicurio/apicurio-registry-mem:latest-snapshot
ADD export.zip /tmp/registry/
ENV REGISTRY_IMPORT=/tmp/registry/export.zip
```

StartupEvent observer to run the import

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/H2SqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/PostgreSQLSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
app/src/test/java/io/apicurio/registry/rest/v2/AdminResourceTest.java

This improves the reset of the db sequences we have, and should fix the errors when importing data from old registry reported in issue #1500

fix reset globalId and contentId sequence

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java

Improvement to the export API to export only the rows from the content table that belong to the current tenant.

Export only tenant content

---

.github/workflows/release.yaml

events triggered by the GITHUB_TOKEN will not create a new workflow run. Hence, the cli-release workflows were not getting triggered on the release event.

fix: Use PAT for creating release

---

.github/workflows/tool-exportV1-release.yaml

This PR adds a GH workflow to build and attach to a release the exportV1 tool.
Because the exportV1 tool is likely only going to be released one or two times this workflow has only a manual dispatch trigger configuration.

release exportV1 tool

---

app/pom.xml
app/src/test/java/io/apicurio/registry/ApicurioTestTags.java
app/src/test/java/io/apicurio/registry/auth/AuthTestNoRoles.java
app/src/test/java/io/apicurio/registry/auth/SimpleAuthTest.java
app/src/test/java/io/apicurio/registry/events/KafkaEventsTest.java
app/src/test/java/io/apicurio/registry/maven/MojoAuthTest.java
build-deploy.sh
pom.xml
pr-check.sh
storage/sql/pom.xml
storage/sql/src/test/java/io/apicurio/registry/storage/util/PostgreSqlEmbeddedTestResource.java

Small modifications to our quarkus tests so we can run them without depending on docker.
Modifications to pr-check and build-deploy scripts to use the latest modifications.

pr-check script, run quarkus tests inside docker

---

utils/converter/src/main/java/io/apicurio/registry/utils/converter/ExtJsonConverter.java

After looking at the original Kafka JSON converter, this should fix the linked issue, please, review.

Allow nulls in json converter

---

.dockerignore

This allows docker to be run without transferring gigabytes of context

chore: add .dockerignore

---

app/src/main/resources-unfiltered/META-INF/resources/apidocs/index.html
ui/src/services/auth/auth.service.ts
ui/src/services/config/config.service.ts
ui/src/services/config/config.type.ts

This modification supports authentication when the UI is used in a federated (micro UI) environment.  This allows the host page to pass a `getToken` function into the federate components.  That can be done via the standard `config` property currently required by all the federated components.  The config should look something like this:
```javascript
{
apis: "http://localhost:8080/t/:tenantId/apis",
config: {
artifacts: {
url: "url-to-artifacts-api"
},
auth: {
type: "gettoken",
getToken: function() => Promise<string>
},
features: {
readOnly: false,
breadcrumbs: false,
multiTenant: true
},
ui: {
navPrefixPath: "navigation-prefix-path"
}
}
}
```
The new bit is the `auth` section.  The type of auth should be set to `gettoken` and then the `getToken` property should be a function with the …

Implemented support for "gettoken" style auth in the UI

---

utils/protobuf-schema-utilities/pom.xml
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
utils/protobuf-schema-utilities/src/test/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtilsTest.java
utils/protobuf-schema-utilities/src/test/proto/TestOrdering.proto

This will fix the [#1617 issue](https://github.com/Apicurio/apicurio-registry/issues/1617). 
Parsed schema looks like below with the fix,
```
// Proto schema formatted by Wire, do not edit.
// Source: 
package io.apicurio.registry.utils.protobuf.schema;
message Address {
required string street = 1 [json_name = "Address_Street"];
optional int32 zip = 2;
optional string city = 3;
}
message Customer {
required string name = 1;
}
```

Fix json_name option bug with FileDescriptionUtils parser

---

ui/src/services/groups/groups.service.ts

This pull request should fix wrong YAML OpenAPI file recognition, which was caused by different result of XML error parsing in Chrome browser.

Chrome YAML file type recognition fix;

---

ui/src/app/pages/artifactVersion/components/tabs/documentation.tsx
ui/src/app/pages/artifactVersion/components/tabs/errorTab.css
ui/src/app/pages/artifactVersion/components/tabs/errorTab.tsx
ui/src/app/pages/artifactVersion/components/tabs/index.ts

This pr is adding error screen in documentation tab when JSON parsing of OpenAPI fails. Fixes issue #1624.
There should be discussion about the displayed text.

[WIP] Handle JSON Parse Error in OpenAPI documentation tab

---

app/src/test/resources/test-realm.json
common/src/main/java/io/apicurio/registry/auth/KeycloakAuth.java
multitenancy/tenant-manager-client/src/main/java/io/apicurio/multitenant/client/Auth.java

This fixes the expiration check since the previous one was setting the expiration time when verifying the token so it was actually never being checked properly, basically, the `isExpired` check would return false even when the token was expired. This will fix that issue.
This also reduces the test access token lifespan so the mechanism is actually triggered.

Fix expiration check

---

utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
utils/protobuf-schema-utilities/src/test/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtilsTest.java
utils/protobuf-schema-utilities/src/test/proto/TestOrderingSyntax2Specified.proto

This commit will fix the following bug with Protobuf FileDescriptor parsing.
1. Interpret correctly when `proto2` syntax is specifically used in `.proto` schema file.
This commit is part of bug fixes reported in issue #1671

Fix protobuf bugs where proto2 syntax is specified

---

utils/converter/pom.xml
utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroData.java
utils/converter/src/test/java/io/apicurio/registry/utils/converter/avro/AvroDataTest.java

Fixes [1740](https://github.com/Apicurio/apicurio-registry/issues/1740)
Original fix https://github.com/confluentinc/schema-registry/issues/1376.
The issue happens with Avro 1.9+ where if a field of type `long` has `connect.default` property, e.g.
```
"type": "record"
"name": "sample"
"namespace": "io.apicurio",
"fields": [
{
"name": "prop",
"type": {
"type": "long",
"connect.default": 42,
"connect.version": 1
}
}
]
```
then `AvroData.toConnectSchema` throws
```
org.apache.kafka.connect.errors.DataException: Invalid type for INT64: class java.lang.Integer
at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1498)
at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1230)
at …
```

connect.default on long avro field

---

.github/dependabot.yml
integration-tests/testsuite/pom.xml
pom.xml
schema-compatibility/protobuf/pom.xml
serdes/protobuf-serde/pom.xml
utils/protobuf-schema-utilities/pom.xml
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufMessage.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufSchemaLoader.java
utils/protobuf-schema-utilities/src/test/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtilsTest.java
utils/protobuf-schema-utilities/src/test/proto/TestOrderingSyntax2References.proto
utils/protobuf-schema-utilities/src/test/proto/TestOrderingSyntax3.proto
utils/protobuf-schema-utilities/src/test/proto/TestOrderingSyntax3References.proto

This issue adds supports for parsing the nested references in the Proto schema correctly. This bug was raised as part of [issue](https://github.com/Apicurio/apicurio-registry/issues/1671). 
**Background**
When a nested reference is present in the schema, it is not interpreted correctly,
For example,
```
package foo.bar;
message A {
}
message  B {
A a = 1;
}
```
When a `FileDescriptorProto` is generated for above schema, 
**Current behavior**
```
name: "fileName.proto"
package: "foo.bar"
message_type {
name: "A"
field {
}
message_type {
name: "B"
field {
name: "A"
number: 1
label: LABEL_OPTIONAL
type: TYPE_MESSAGE
}
}
```
**Expected behavior**
```
name: "fileName.proto"
package: "foo.bar"
message_type {
name: "A"
field {
}
message_type {
name: "B"
field {
name: "A"
number: 1
label: …
```

Add support for interpreting nested and internal / external types

---

utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroData.java
utils/converter/src/test/java/io/apicurio/registry/utils/converter/avro/AvroDataTest.java

Fix for #1825. This PR handles an issue with type conversion when schema of a field is `INT64` but the value is small enough to fit an `int`. `toConnectData` throws a `DataException`. The fix is to check if the class of the value is `Integer` and explicitly cast it to a `long`. The method already checks if the value is null or not to there is no need to use `Long`.

Check and convert data type for INT64

---

distro/openshift-template/mt/apicurio-registry-mt-template.yaml

default empty parameter value was making deployment to fail

fix mt template bug

---

client/src/main/java/io/apicurio/registry/rest/client/exception/RateLimitedClientException.java
client/src/main/java/io/apicurio/registry/rest/client/impl/ErrorHandler.java
integration-tests/testsuite/src/main/java/io/apicurio/tests/utils/RateLimitingProxy.java
integration-tests/testsuite/src/main/java/io/apicurio/tests/utils/TooManyRequestsMock.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ApicurioV2BaseIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/RateLimitedRegistrySerdeIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/SimpleSerdesTesterBuilder.java

This adds a new exception to our rest client to allow to handle rate limited scenarios.
I wrote a bunch of tests to verify how the serdes behave currently, and it mainly looks good.
We still may have issues in more advanced usecases where the rate limited exception may hit bad :)
One scenario I want to write a test is:
- serdes internal cache expiration, that may force me to implement some logic in the serdes to make it smart enough to use the data that was in the cache before hitting the rate limit exception. Still maybe a pretty rare situation

serdes: rate limiting test scenarios

---

utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractRegistryMojo.java

I've added the ability to set some of the configuration properties for the plugin on the command line. 
For example, the registryUrl property can be set with `-Dregistry.url`
A complete example using the example from the main README would like this : 
`mvn clean  install -Pupload -Dregistry.url=https://service-registry-stage.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com/t/1602aa52-6cc7-43bc-99a1-7239bd5fef86/api/v2`

feat: allow plugin properties to be set on command line

---

app/src/test/java/io/apicurio/registry/RegistryClientTest.java
integration-tests/integration-tests-common/pom.xml
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/Constants.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/KafkaFacade.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryFacade.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/auth/JWKSMockServer.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/kafka/EmbeddedKafka.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/multitenancy/MultitenancySupport.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/multitenancy/MultitenantAuthIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/multitenancy/TenantUser.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/multitenancy/TenantUserClient.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/multitenancy/serdes/RateLimitedRegistrySerdeIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
pom.xml
utils/tests/pom.xml
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TooManyRequestsMock.java

Because multitenancy test profile is something with specific infra configuration (multitenancy, auth enabled,...) it's a perfect place to have serdes tests using authentication.
This PR moves some tests to the multitenancy profile and introduces some changes that will allow us to have more serdes tests using authentication

move rate limit tests to multitenancy profile + auth to serdes rate limit tests

---

app/src/main/resources/application.properties
distro/openshift-template/mt/apicurio-registry-mt-template.yaml
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/api/TenantsResourceImpl.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/api/services/RegistryDeploymentInfoService.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/auth/CustomAuthenticationMechanism.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/logging/audit/AuditHttpRequestContext.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/logging/audit/AuditHttpRequestInfo.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/logging/audit/AuditLogService.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/logging/audit/Audited.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/logging/audit/AuditedInterceptor.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/logging/audit/HttpRequestsAuditFilter.java
multitenancy/tenant-manager-api/src/main/resources/application.properties
multitenancy/tenant-manager-api/src/test/java/io/apicurio/multitenant/TenantManagerClientTest.java
multitenancy/tenant-manager-api/src/test/java/io/apicurio/multitenant/logging/audit/MockAuditLogService.java

this PR adds audit logging to the tenant-manager. I implemented it using an interceptor
It's missing adding auditing for authentication failures
and also missing gather client IPs

tenant-manager: audit logging

---

integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/Constants.java

this is to try to make kafkasql clustered tests more stable

increase integration tests timeouts to deploy registry

---

app/src/main/resources/application.properties
storage/kafkasql/src/main/resources/overlay.properties

See https://github.com/Apicurio/apicurio-registry/issues/1591 for a discussion about this issue.
This PR improves the default values for the KafkaSQL consumer (groupId) and producer (clientId).

Better support for unique client and group ids in kafkasql

---

app/src/main/java/io/apicurio/registry/auth/AuthorizedInterceptor.java
app/src/main/java/io/apicurio/registry/cncf/schemaregistry/SchemagroupsResource.java
app/src/main/java/io/apicurio/registry/rest/RegistryApplicationServletFilter.java
app/src/main/resources-unfiltered/META-INF/resources/apidocs/index.html

This PR fixes several things around apidocs and the access to it in a multitenant environment.
- fix for CNCF api path, missing /apis prefix
- fix for CNCF docs url, looks like it changed
- fix for accessing api docs in a multitenant environment
In `RegistryApplicationServletFilter.java` we had a check that did not allow access to `/apis` prefixed endpoints to the default tenant if multitenancy is enabled. That did not allow to access , for instance, `http://localhost:8080/apis/registry/v2` to see the api docs. But that check was added as a security measure to not allow to access the rest of the API with the default tenant in multitenancy mode. 
So the fix consisted of moving the mentioned check to the `AuthorizedInterceptor` that way apidocs can be accessed anonimously and the rest of …

Fix cncf api path and apidocs access

---

storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/ContentIdKey.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/GlobalIdKey.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/values/ActionType.java

Resolves #1993 and #1873 
TODO:
Needs a test:
- Start Kafka
- Create the `kafkasql-journal` topic with aggressive log compaction 
```
bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic kafkasql-journal --partitions 1 --replication-factor 1 --config min.cleanable.dirty.ratio=0.000001 --config cleanup.policy=compact --config segment.ms=100 --config delete.retention.ms=100
```
- Start Registry
- Add ~3 artifacts
- Stop Registry
- Restart Registry to load data from the topic
- Add another artifact -> exception
@famartinrh Could you please work on the tests if you have some time?

Prevent compaction of messages related to sequences

---

ui/src/app/components/errorPage/accessErrorPage.css
ui/src/app/components/errorPage/accessErrorPage.tsx
ui/src/app/components/errorPage/errorPage.tsx
ui/src/app/pages/basePage.tsx
ui/src/services/baseService.ts

Instead of the generic error page, users will now see a specialty error page for 403 errors.  The error page looks like this:

Add specific error page for 403 errors.

---

app/src/main/resources/application.properties
app/src/main/resources/io/apicurio/registry/storage/impl/sql/h2.ddl
app/src/main/resources/io/apicurio/registry/storage/impl/sql/postgresql.ddl

this is a very bad issue IMO , so if we have any release containing this bug we should do a patch release
also this made me think we need a set of scripts or tests to verify dummy things like this. In general things I've been thinking that need verification are:
- the db version in the code matches the version in the ddls
- the openshift mt template is properly formatted (parameters are not repeated,...)

fix missing db version update

---

app/src/main/java/io/apicurio/registry/rest/v2/DownloadsResourceImpl.java
ui/src/app/pages/rules/rules.tsx
ui/src/models/downloadRef.model.ts
ui/src/services/admin/admin.service.ts
ui/src/services/baseService.ts

Example usage from somewhere in the UI:
```typescript
private doExport = (): void => {
Services.getAdminService().exportAs("export.zip").then((ref) => {
window.location.href = ref.href;
}).catch(error => {
this.handleServerError(error, "Error exporting data.");
})
}
```

Add support for export to the AdminService in the UI layer

---

ui/src/services/groups/groups.service.ts

This appears to have arrived as a copy-paste error some time ago so I have edited this to remove the offending characters.

fix: remove hidden bidi characters

---

storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java

It seems that `@Observes StartupEvent ev` causes the code in that method to execute before any of the injected beans have been initialized via their own `@PostConstruct`.  Sample log output proving this:
```
2021-12-03T13:26:13.2355694Z 2021-12-03 13:26:13 INFO <> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (main) Using Kafka-SQL artifactStore.
2021-12-03T13:26:13.5978267Z 2021-12-03 13:26:13 INFO <> [io.apicurio.registry.utils.kafka.KafkaUtil] (kafka-admin-client-thread | adminclient-1) Creating new Kafka topic: kafkasql-journal
2021-12-03T13:26:13.5981680Z 2021-12-03 13:26:13 INFO <> [io.apicurio.registry.utils.kafka.KafkaUtil] (kafka-admin-client-thread | adminclient-1) Created new topic: kafkasql-journal
2021-12-03T13:26:13.7206836Z 2021-12-03 13:26:13 INFO <> …
```

Try using @PostConstruct instead of StartupEvent

---

utils/exportV1/pom.xml

- Adds the quarkus rest client as a dependency to provide the resteasy
JAX-RS implementation, as the 1.3.x Apicurio rest client uses the
JAX-RS WebApplicationException class when an API call fails.
Contributes to: #1806

fix: Add JAX-RS implementation to exportV1 tool

---

ui/src/app/pages/artifactVersion/artifactVersion.tsx
ui/src/app/pages/artifactVersion/components/tabs/content.tsx
ui/src/app/pages/artifactVersion/components/tabs/info.tsx
ui/src/models/artifactMetaData.model.ts

fix for https://github.com/Apicurio/apicurio-registry/issues/651
and new feature for artifacts whose content is json. This PR removes the format button. Content will be automatically pretty printed if it's json and it can be parsed without errors.

ui: auto format json content and fix modifiedOn on info tab

---

app/src/main/java/io/apicurio/registry/metrics/health/readiness/ResponseTimeoutReadinessCheck.java

this should fix the unexpected log message 
`Expected header X-Apicurio-Registry-ResponseTimeoutReadinessCheck-RequestStart not found.`

fix: too verbose warn log

---

app/src/main/java/io/apicurio/registry/cncf/schemaregistry/impl/SchemagroupsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/SearchResourceImpl.java
app/src/main/java/io/apicurio/registry/storage/dto/SearchFilter.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/test/java/io/apicurio/registry/ArtifactSearchTest.java
app/src/test/java/io/apicurio/registry/rest/v2/GroupsResourceTest.java
app/src/test/java/io/apicurio/registry/rest/v2/SearchResourceTest.java
app/src/test/java/io/apicurio/registry/storage/AbstractRegistryStorageTest.java
app/src/test/java/io/apicurio/registry/storage/RegistryStoragePerformanceTest.java

fix for #2125 , now the REST layer parses que "properties" queryParam looking for ":" delimiter to separate property key and value. Adding another way to provide propertyKey and propertyValue to the API can be implemented later.
we had the implicit requirement in the storage layer that property value must be not null. This PR brings that requirement explicitly to the REST layer.

bugfix: search by properties, search by key and value

---

app/src/main/java/io/apicurio/registry/ccompat/rest/impl/ConfigResourceImpl.java
app/src/main/java/io/apicurio/registry/ccompat/rest/impl/SubjectVersionsResourceImpl.java
app/src/main/java/io/apicurio/registry/ccompat/rest/impl/SubjectsResourceImpl.java
app/src/main/java/io/apicurio/registry/logging/audit/AuditingConstants.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/test/java/io/apicurio/registry/ccompat/rest/ConfluentCompatApiTest.java

from #2185 
the issue is that `deleteArtifactVersion` method leaved the latest column in artifact table corrupted (with null value) that made a lot APIs to break
this PR also adds some missing audit logging

bugfix: deleteArtifactVersion leaves artifacts.latest column corrupted

---

.github/workflows/integration-tests.yaml
.github/workflows/kubernetes-tests.yaml
.github/workflows/verify.yaml
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/SimpleSerdesTesterBuilder.java

This PR leaves the matrix job to test java 11 and 17 only for the verify build job

reduce number of ci jobs

---

distro/openshift-template/mt/apicurio-registry-mt-template.yaml

This PR changes the deployment model for multitenant apicurio-registry. Now tenant-manager will be provisioned in a new deployment and we will use envoy proxy as a sidecar. Using envoy will be used for basic rate limiting and to ease TLS setup.
Configuration updates in the control plane components may be needed after this, as well as for metrics and alerts.

mt: tenant-manager extract to its own deployment

---

README.md

- Added a section to the readme covering the kafkasql artifact build and deployment both to kafka at localhost:9092 and an external and secured kafka cluster.
- Minor descriptive changes for clarity.

Updated readme with respect to kafkasql storage option.

---

app/src/main/resources/application.properties
ui/src/app/components/modals/progressModal.css
ui/src/app/components/modals/progressModal.tsx
ui/src/app/pages/artifacts/artifacts.tsx
ui/src/app/pages/artifacts/components/toolbar/toolbar.tsx
ui/src/services/admin/admin.service.ts
ui/src/services/baseService.ts

This pull request adds support for Importing and Exporting content (ZIP file) in the UI.  These functions have been available in the REST API for some time, and also in the MAS CLI, but not in the UI.  The functionality is admin-only, so the new UI changes will only be available to admin users.  Here's what it looks like:
When downloading artifacts, clicking the menu item simply starts a download of the ZIP file.  Nothing additional needs to be done.  When uploading artifacts, there is a followup modal dialog that lets the user choose the ZIP file they want to upload.  Then there is a progress dialog that appears while the import is happening.

Added import/export functions in UI

---

app/src/main/java/io/apicurio/registry/rest/v2/SearchResourceImpl.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/test/java/io/apicurio/registry/ArtifactSearchTest.java
app/src/test/java/io/apicurio/registry/rest/v2/SearchResourceTest.java

Work for #2187. Used this [bug fix](https://github.com/Apicurio/apicurio-registry/pull/2166/files) as a guide.
- Added `testSearchByPropertyKey()` to `SearchResourceTest.java`
- Added functional code to make the test pass. 
- Broadened the test cases to ensure correct behaviour in a variety of situations (following cases given in `testSearchByPropertyKey()`).
- Added cases to `testCaseInsensitiveSearch()` and tidied comments.

Added search by property key and relevant tests

---

app/src/main/java/io/apicurio/registry/rules/compatibility/CompatibilityRuleExecutor.java
app/src/test/java/io/apicurio/registry/rest/v1/ArtifactsResourceTest.java
app/src/test/java/io/apicurio/registry/rest/v1/TestResourceTest.java
app/src/test/java/io/apicurio/registry/rest/v2/GroupsResourceTest.java

Resolves #2160 
- Added list of diffs to end of printed error message. 
- Added helper method to construct the list of errors along with the location of the compatibility conflict.
~~I couldn't find any tests relevant to these changes, I imagine because they are purely aesthetic.~~
Oh silly me...
- Changed expected returned error message in 3 tests:
1. ArtifactsResourceTest.testCreateArtifactVersionCompatibilityRuleViolation 
2. TestResourceTest.testTestArtifactCompatibilityViolation 
3. GroupsResourceTest.testCreateArtifactVersionCompatibilityRuleViolation

Provide user with reasons for incompatible json error.

---

.github/workflows/verify.yaml

This will cause a [Repository Dispatch](https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event) to be sent to the SDK repo, which will trigger a workflow there to generate a new SDK.
I just need to obtain a PAT for this with the required scope (repo) - maybe I can reuse an existing one?
If you want to verify this use [act](https://github.com/nektos/act) with a personal access token, and comment out lines 178 & 161.
```shell
act -j notify-sdk --secret $REPO_ACCESS_TOKEN
```

Use `workflow_call` to trigger generation job in SDK repo

---

.github/workflows/verify.yaml

This PR adds multiple SDK repo targets in a matrix, allowing the job to be reused.
See the result in action:
- Python: https://github.com/Apicurio/apicurio-registry-client-sdk-python/pull/2
- JS: https://github.com/Apicurio/apicurio-registry-client-sdk-js/pull/6
- Go: https://github.com/Apicurio/apicurio-registry-client-sdk-go/pull/8

Notify multiple SDK repos about OAS change event

---

docs/modules/ROOT/partials/getting-started/con-registry-serdes-strategy.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc

just some small changes to make reference to the new location of the SchemaResolver interface in the docs

fix schema resolver references in docs

---

.github/workflows/release.yaml
.github/workflows/tag-registry-examples.yaml
.github/workflows/verify.yaml

The existing release workflow fails if there are issues while tagging the registry examples repo. The tagging of the examples repo is done as part of the separate workflow, so that the registry release can be done smoothly.

Decouple release workflow

---

storage/kafkasql/src/test/resources/test-overlay.properties

We're having some issues with kafkasql testing and I think the reason is the database not being ready, let's see if this fixes the flaky kafkasql tests and then we can adjust the time if we think 2s is too much (likely yes).

Increase kafka sql startup lag for tests

---

app/src/main/java/io/apicurio/registry/auth/AuthConfig.java
app/src/main/java/io/apicurio/registry/ccompat/store/CCompatConfig.java
app/src/main/java/io/apicurio/registry/rest/v2/AdminResourceImpl.java
app/src/main/java/io/apicurio/registry/services/auth/CustomAuthenticationMechanism.java
app/src/main/java/io/apicurio/registry/ui/config/UiConfigProperties.java
ui/src/app/pages/settings/settings.tsx

Copy edits to UI labels and descriptions only, mostly for consistency with text used elsewhere in the UI and docs.

docs: copy edits to ui text for dynamic config props

---

pom.xml
ui/package.json
ui/yarn.lock

`apicurio-data-models` has been deprecated and moved to `@apicurio/data-models`.

chore(deps): install apicurio-data-models 1.1.26

---

common/src/main/java/io/apicurio/registry/rest/v2/GroupsResource.java
common/src/main/resources/META-INF/openapi.json

This PR updates the content type of the artifact metadata request bodies to be `{}` instead of `binary`.
The PR has moved the order of some things..this is because I needed to edit source in order to make this change. I have proposed we make this possible in Studio going forward: https://github.com/Apicurio/apicurio-studio/issues/1885
This should fix https://github.com/Apicurio/apicurio-registry-client-sdk-go/issues/17

[Apicurio] Please merge generated API project

---

ui/src/app/components/common/ifNotEmpty.tsx
ui/src/app/components/common/index.ts
ui/src/app/pages/settings/components/configProperty.css
ui/src/app/pages/settings/components/configProperty.tsx
ui/src/app/pages/settings/components/propertyInput.tsx
ui/src/app/pages/settings/settings.css
ui/src/app/pages/settings/settings.tsx

I think the only thing missing from the designs is the Toasts.  I need to think a little more about how that should be done, especially given the various deployment models for the UI.  (RHOSR vs. community)
Here is a screenshot of the updated UI:

Updated the Settings page L&F based on UX designs

---

ui/src/app/pages/artifactVersion/components/tabs/info.css
ui/src/app/pages/artifactVersion/components/tabs/info.tsx

This PR returns the Download button which was mistakenly removed in https://github.com/Apicurio/apicurio-registry/pull/2525/files

fix: add Download button

---

.github/workflows/integration-tests.yaml
.github/workflows/kubernetes-tests-manual.yaml
.github/workflows/kubernetes-tests.yaml
.github/workflows/maven-snapshot-release.yaml
.github/workflows/registry-rhbq-build.yaml
.github/workflows/release-images.yaml
.github/workflows/release.yaml
.github/workflows/tag-registry-examples.yaml
.github/workflows/tool-exportV1-release.yaml
.github/workflows/update-openapi.yaml
.github/workflows/verify.yaml

Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates.

Use Temurin Distribution and Attach built JARs and Libraries to the release

---

pom.xml

- Mitigates
[CVE-2020-36518](https://nvd.nist.gov/vuln/detail/CVE-2020-36518)
- Mitigates
[CVE-2021-43797](https://nvd.nist.gov/vuln/detail/CVE-2021-43797)
Signed-off-by: Andrew Borley <BORLEY@uk.ibm.com>

build(deps): Bump quarkus version from 2.7.5.Final to 2.7.6.Final

---

pom.xml
schema-util/json/pom.xml
serdes/jsonschema-serde/pom.xml

See https://github.com/everit-org/json-schema#maven-installation & https://search.maven.org/search?q=everit%20json .
Ran into this when trying to update `io.apicurio:apicurio-registry-utils-converter` from version 2.2.1.Final to 2.2.4.Final.
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':writer:connectorConfigDoc'.
> Could not resolve all files for configuration ':writer:runtimeClasspath'.
> Could not find com.github.everit-org.json-schema:org.everit.json.schema:1.14.1.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/com/github/everit-org/json-schema/org.everit.json.schema/1.14.1/org.everit.json.schema-1.14.1.pom
- https://packages.confluent.io/maven/com/github/everit-org/json-schema/org.everit.json.schema/1.14.1/org. …
```

fix everit-json maven coordinates

---

system-tests/src/main/java/io/apicurio/registry/systemtests/framework/DatabaseUtils.java
system-tests/src/main/java/io/apicurio/registry/systemtests/registryinfra/resources/ApicurioRegistryResourceType.java
system-tests/src/test/java/io/apicurio/registry/systemtests/OLMTests.java

This test tries if we are able to create Apicurio Registry instances in multiple namespaces when OLM operator is installed cluster-wide, and we are NOT able to create Apicurio Registry instances in multiple namespaces when OLM operator is installed as namespaced.

New(system-tests, OLMTests): Multinamespace test

---

docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-creating-access-token-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-downloading-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-testing-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-client.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

- Replaces MAS SSO with RH SSO token URL for downstream

docs: use correct sso token url downstream

---

app/src/main/java/io/apicurio/registry/ui/config/UiConfigProperties.java
app/src/main/java/io/apicurio/registry/ui/servlets/ConfigJsServlet.java
app/src/main/resources/application.properties
ui/config/config-oidcjs.js
ui/package.json
ui/src/services/auth/auth.service.ts
ui/src/services/config/config.service.ts
ui/src/services/config/config.type.ts
ui/yarn.lock

Opening in draft for early feedback. This introduces the support for using different oauth servers in the UI instead of just use keycloak. I still want to test and refactor a few things, especially around properties management (right now some oauth and keycloak ones are mixed) and I also want to test the new code to see if I can make it work with keycloak allowing us to remove keycloak-js from the project and just use the generic solution.

Initial support for using different oauth servers

---

.github/workflows/integration-tests.yaml
.github/workflows/kubernetes-tests-manual.yaml
.github/workflows/kubernetes-tests.yaml
.github/workflows/verify.yaml

`actions/setup-java@v3` integrates the caching step, I added the caching in a few places where it makes sense and was missing (e.g. left it out from the release jobs)

[chore] Use built-in caching from `actions/setup-java@v3`

---

.github/workflows/publish-debug-image.yaml

This is the example output on how to run the generated Docker image:
https://github.com/andreaTP/apicurio-registry/runs/7862757374?check_suite_focus=true#step:6:7
The Docker image will be available for one day only, but you can always re-run the CI or trigger any action on the PR will rebuild it.

Publish a mem image to ease the reviews

---

.github/workflows/image-scan-impl.yaml
.github/workflows/image-scan-reusable.yaml

Question:
- Should we have a separate repository for "reusable workflows"? Or should we use one of the already available?
It just needs to be a public repo:
https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

Add a reusable image scan GH Action

---

ui/package-lock.json
ui/package.json
ui/src/app/pages/artifactVersion/artifactVersion.tsx
ui/src/app/pages/artifactVersion/components/tabs/documentation.tsx
ui/webpack.common.js

Adds support for rendering documentation for AsyncAPI artifacts, resolves #1011
The documentation is rendered in-browser using the [asyncapi-react](https://github.com/asyncapi/asyncapi-react) react component, much like the Redoc-based rendering of OpenAPI specifications.

AsyncAPI Documentation Tab

---

app/src/main/java/io/apicurio/registry/services/http/RegistryExceptionMapperService.java
app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/VersionAlreadyExistsException.java
app/src/main/java/io/apicurio/registry/storage/decorator/RegistryStorageDecorator.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
client/src/main/java/io/apicurio/registry/rest/client/exception/ExceptionMapper.java
client/src/main/java/io/apicurio/registry/rest/client/exception/VersionAlreadyExistsException.java
client/src/main/java/io/apicurio/registry/rest/client/impl/RegistryClientImpl.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ApicurioV2BaseIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java

This PR adds new registry exception - version already exists exception. It is thrown when client tries to create new artifact version with the version string, that is already in use for this artifact.
Fixes  #2609

feat: better handling of version string unique key violation exception

---

ui/config/config-keycloakjs-rbac.js
ui/config/config-keycloakjs.js
ui/package.json
ui/src/app/components/common/ifAuth.tsx
ui/src/app/pages/artifactVersion/artifactVersion.tsx
ui/src/app/pages/artifactVersion/components/modals/changeOwnerModal.tsx
ui/src/app/pages/artifactVersion/components/tabs/info.tsx
ui/src/app/pages/roles/components/modals/grantAccessModal.tsx
ui/src/app/pages/roles/components/modals/selectPrincipalAccount.tsx
ui/src/models/artifactOwner.model.ts
ui/src/models/index.ts
ui/src/services/auth/auth.service.ts
ui/src/services/groups/groups.service.ts
ui/tsconfig.json

Implemented the UI for Change Owner.  Includes adding an "Owner" field to the artifact details page, with a pencil icon next to it (only when applicable and allowed).
If a source of principals is available we'll use the typeahead control.  If not we'll use a standard text box.

Implement Change Owner modal in the UI

---

app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java

This avoids returning `500` when there are issues downloading the artifact content.
Thanks, @jsenko for noticing it!
resolves #2758

[feat] Better error handling when downloading artifact contents from URL

---

integration-tests/testsuite/src/test/java/io/apicurio/tests/selenium/SeleniumProvider.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/RegistryUITester.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/UploadArtifactsIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/pages/UploadArtifactDialog.java
ui/src/app/components/common/if.tsx
ui/src/app/components/common/index.ts
ui/src/app/components/common/isLoading.tsx
ui/src/app/components/common/urlUpload.css
ui/src/app/components/common/urlUpload.tsx
ui/src/app/pages/artifacts/components/uploadForm/uploadForm.tsx
ui/src/services/groups/groups.service.ts
ui/src/services/index.ts
ui/src/services/url.ts

Instead of providing the URL and a SHA, the UI now uses the same `UrlUpload` control as RHOAD.  It looks like this now:
The API change that allows users to upload by a URL still exists and works, but he UI now doesn't use it.

Change the Create Artifact (by URL) UI to be more consistent with RHOAD

---

multitenancy/tenant-manager-api/src/main/resources/application.properties
storage/sql/src/main/resources/overlay.properties

Fast-forwarding Carles fix for `native-image` since it's failing all the CI rebased on latest main.

Add '--allow-incomplete-classpath' to native builds

---

.github/workflows/verify.yaml
pom.xml

To reduce compilation time and restore the previous condition of the CI I'm here proposing to have the `system-tests` module only optionally enabled.
It was added to the main pom here: https://github.com/Apicurio/apicurio-registry/pull/2737/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R141

Conditional inclusion of system-tests

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/upgrader/ProtobufCanonicalHashUpgrader.java

This was a mistake - the upgrader runs as part of upgrading the DB.  The artifact references was added to the DB schema in REV 8.  The proto upgrader is REV 5.  So it should have older SQL, since it's upgrading from REV 4 to REV 5... which is pre-refs.

Revert upgrader back to original SQL

---

docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-changing-artifact-owner-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-kafka-streams-operatorhub.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-postgresql-operatorhub.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-registry-operatorhub.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-register.adoc
docs/modules/ROOT/partials/getting-started/proc-setting-up-kafka-streams-storage.adoc
docs/modules/ROOT/partials/getting-started/proc-setting-up-postgresql-storage.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
docs/modules/ROOT/partials/shared/attributes-links.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

Updates user docs as follows:
- Update to `REGISTRY_AUTH_OBAC_ENABLED` variable
- Add missing variables for 
--  `REGISTRY_AUTH_AUTHENTICATED_READS_ENABLED`
--  `REGISTRY_AUTH_OBAC_LIMIT_GROUP_ACCESS`
- Clean up security config and change artifact owner docs 
- Add feedback from QE testing of downstream docs (mostly link fixes)
Documents following issues:
- #2743 
- #2755

docs: updated + new security options

---

.github/workflows/integration-tests.yaml

This should be a viable workaround for this issue:
https://github.com/Apicurio/apicurio-registry/actions/runs/3191285239/jobs/5222146661#step:8:2623
The workaround might be necessary in other workflows ...

Workaround `jackson-coreutils` download issue

---

.github/workflows/registry-rhbq-build.yaml
.github/workflows/verify.yaml

The workaround seems to be effective.

Implement the `jackson-coreutils` workaround in more CI workflows

---

ui/src/app/pages/artifacts/components/uploadForm/uploadForm.tsx

This was premature optimization for no gain and was impacting e2e testing.  There really isn't a need
to debounce the input.  Users *may* type in the artifact upload text area, but if they do the regular performance of React seems fine, even for reasonably large inputs.

Removed the debouncer from the Upload artifact form

---

pom.xml
storage/sql/src/main/resources/overlay.properties

This enables debugging options for the native-image in Operate First, so that we can further investigate in case something misbehave.

Enable debugging options for the SQL native image

---

new-system-tests/src/test/java/io/apicurio/registry/systemtests/SqlKeycloak.java
new-system-tests/src/test/java/io/apicurio/registry/systemtests/SqlNoIAM.java
new-system-tests/src/test/resources/common/00_operator_group.yaml

`OperatorGroup` for operators installed in namespace is shared between more operators, it can be placed in `common` resources directory and created before all other test resources.

Update(OperatorGroup): Create OperatorGroup at the beginning of test(s)

---

.github/workflows/dependabot-automerge.yaml

This seems to be an officially supported thing:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
let's try it out!

Enable automerge of dependabot semver patches

---

ui/src/models/artifactTypes.model.ts

Another option is removal of static artifact types list to show that something went wrong with request getting those types from instance.

Update(ui/artifactTypes.model.ts): Add missing XML artifact type

---

docs/modules/ROOT/partials/getting-started/ref-registry-rule-maturity-matrix.adoc

Full validation rules (syntax and semantic) are already implemented for XSD and WSDL artifacts:
https://github.com/Apicurio/apicurio-registry/blob/09a65c9562a38db10c748c876123fbfd0bd336c8/schema-util/wsdl/src/main/java/io/apicurio/registry/rules/validity/WsdlContentValidator.java#L46
https://github.com/Apicurio/apicurio-registry/blob/09a65c9562a38db10c748c876123fbfd0bd336c8/schema-util/xsd/src/main/java/io/apicurio/registry/rules/validity/XsdContentValidator.java#L47
So the documentation should be updated accordingly.

docs: actualise validity rules values for XSD & WSDL

---

.github/workflows/update-openapi.yaml
.github/workflows/validate-openapi.yaml

This PR sets up automated notifications to `app-services-sdk-*` when the API schema updates, as well as an spectral check. Needs `APP_SERVICES_CI_TOKEN` set up before merge.

ci: dispatch events to app services SDK repos when the API schema changes

---

.github/workflows/release.yaml

This changes the release workflow so that it restores the value of the docs version found in `antora.yml` to something other than `main`.  This is so that the `antora.yml` file that's located on `main` can be set to something like `2.4.x` - useful when generating the documentation.
A better solution than this would probably be to **read** [the value of the `version` property](https://github.com/Apicurio/apicurio-registry/blob/main/docs/antora.yml#L3) as one of the first steps of the release workflow, and then restore **that** value at the end.  @riprasad if you're looking for what I'm guessing is an easy task for you, this might be a nice distraction.  :)

Restore the docs version in antora.yml to something other than main

---

app/src/test/java/io/apicurio/registry/noprofile/maven/RegistryMojoWithMinifyTest.java
app/src/test/resources/io/apicurio/registry/noprofile/maven/avro.avsc
utils/maven-plugin/pom.xml
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterArtifact.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java

Providing the option to minify avro files and use the minified version to be stored in the registry.
We have the use case that some applications provide the avro schemas using the apicurio maven plugin.
But as the avsc file is taken as is, with newlines and spaces and stored other applications using confluent/avro tools have issues, as they are using the avro-maven-plugin which will minify everything.
Whit this change we are following the same behaviour as avro-maven-plugin or give at least the option to do so.

Add option to minify avro with maven plugin

---

app/src/main/resources-unfiltered/META-INF/resources/apidocs/index.html

Version number for confluent schema registry compatibility is v6 instead of v7.

Fix a typo in index.html

---

schema-util/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/DiffUtil.java
schema-util/json/src/test/java/io/apicurio/registry/rules/compatibility/jsonschema/JsonSchemaDiffUtilTest.java

Problem: Compatibility check fails for following JSON Schema case (it can be found in tests) when uploading schemas via UI or API.
Compatibility - Backward
Original schema:
`{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "number",
"multipleOf": 10.0
}`
Updated schema:
`{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "number",
"multipleOf": 5.0
}`
Problem is that it is saved in DB with scale and original code uses .equals to check that remainder is zero. Equals in BigDecimal compares not only value, but also scale, so 0.0 is not equal to 0.
In this PR compareTo is used making this method working for all cases as expected - tests included.

Fix remainder comparison for multipleOf

---

.github/workflows/release.yaml
python-sdk/pyproject.toml

I manually published 2.4.2:
https://pypi.org/manage/project/apicurioregistrysdk/releases/
~~Next time we should probably automate the version bump.~~
Update the release workflow to be fully automated, this would need to be tested.

Updates for the Python SDK release

---

.github/workflows/python-sdk.yaml
.gitignore
python-sdk/.gitignore
python-sdk/kiota-gen.py
python-sdk/pyproject.toml
python-sdk/tests/basic_test.py

`python_sdk` is ways too generic.
cc. @forsberg

rename the root folder of the Python SDK

---

app/src/test/java/io/apicurio/registry/noprofile/maven/RegistryMojoWithAutoReferencesTest.java
app/src/test/resources/io/apicurio/registry/noprofile/maven/TradeRawArray.avsc
app/src/test/resources/io/apicurio/registry/noprofile/maven/citizen.json
app/src/test/resources/io/apicurio/registry/noprofile/maven/citizenIdentifier.json
app/src/test/resources/io/apicurio/registry/noprofile/maven/city.json
app/src/test/resources/io/apicurio/registry/noprofile/maven/mode.proto
app/src/test/resources/io/apicurio/registry/noprofile/maven/qualification.json
app/src/test/resources/io/apicurio/registry/noprofile/maven/table_info.proto
app/src/test/resources/io/apicurio/registry/noprofile/maven/table_notification.proto
app/src/test/resources/io/apicurio/registry/noprofile/maven/table_notification_type.proto
schema-util/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/JsonUtil.java
utils/maven-plugin/pom.xml
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractDirectoryParser.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AvroDirectoryParser.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/JsonSchemaDirectoryParser.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/ParsedDirectoryWrapper.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/ProtobufDirectoryParser.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterArtifact.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufSchemaLoader.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

This PR adds support for, given a set of artifacts (protobuf, avro or json schema) setting the main schema and figuring out all the references between them and registering everything in Registry properly. Essentially, what we can call, automatic, client-side reference resolving. The specific unit tests are already passing but I still want to implement a few more and also add documentation and examples.
@smccarthy-ie we must document this properly since this will reduce a lot of burden when it comes to artifact references usage.

Maven directory resolver

---

utils/tests/pom.xml

Force the version of mime4j used by the KC admin client to a newer version.

Override the version of mime4j used by the KC admin client

---

app/src/main/java/io/apicurio/registry/rules/integrity/IntegrityRuleExecutor.java
pom.xml
schema-util/avro/src/main/java/io/apicurio/registry/rules/validity/AvroContentValidator.java
schema-util/common/src/main/java/io/apicurio/registry/rules/validity/ContentValidator.java
schema-util/graphql/src/main/java/io/apicurio/registry/rules/validity/GraphQLContentValidator.java
schema-util/json/src/main/java/io/apicurio/registry/rules/validity/JsonSchemaContentValidator.java
schema-util/kconnect/src/main/java/io/apicurio/registry/rules/validity/KafkaConnectContentValidator.java
schema-util/openapi/src/main/java/io/apicurio/registry/rules/validity/ApicurioDataModelContentValidator.java
schema-util/protobuf/src/main/java/io/apicurio/registry/rules/validity/ProtobufContentValidator.java
schema-util/util-provider/src/test/java/io/apicurio/registry/rules/validity/AvroContentValidatorTest.java
schema-util/util-provider/src/test/java/io/apicurio/registry/rules/validity/OpenApiContentValidatorTest.java
schema-util/util-provider/src/test/java/io/apicurio/registry/rules/validity/ProtobufContentValidatorTest.java
schema-util/util-provider/src/test/resources/io/apicurio/registry/rules/validity/avro-valid-with-refs.json
schema-util/util-provider/src/test/resources/io/apicurio/registry/rules/validity/openapi-valid-with-refs.json
schema-util/util-provider/src/test/resources/io/apicurio/registry/rules/validity/protobuf-valid-with-refs.proto
schema-util/xml/src/main/java/io/apicurio/registry/rules/validity/XmlContentValidator.java

I have implemented the `IntegrityLevel.ALL_REFS_MAPPED` option in the new integrity rule.  That part of the rule is artifact type-specific.  I have only implemented it for the following types:
* OpenAPI
* AsyncAPI
* Protobuf
* Avro
Notably missing from the list is JSON Schema, because that one needs a bit of thinking.  We need to have a good way of identifying which $ref is external vs. internal (pointing to something in $defs).  That's easier to do in OpenAPI.  But I think for JSON Schema it has to do with the `$id` and perhaps some other rules.  Just need to make sure we do it right.  I wasn't confident enough to just sling some code at it. :)

Implemented the all-refs-must-be-mapped part of the new integrity rule

---

distro/docker-compose/README.md
distro/docker-compose/src/main/resources/docker-compose.apicurio.yml

Previously using `network_mode: host` that is not supported in non-Linux installs.
Changed the `docker-compose.yaml` to explicit expose the ports used for this deployment.

Update compose to use ports instead of host

---

common/pom.xml

No longer need to override the data-models version

Remove data-models version override from common

---

app/src/test/java/io/apicurio/registry/rbac/AdminClientTest.java
client/src/main/java/io/apicurio/registry/rest/client/AdminClient.java
client/src/main/java/io/apicurio/registry/rest/client/impl/AdminClientImpl.java
client/src/main/java/io/apicurio/registry/rest/client/request/provider/AdminRequestsProvider.java
client/src/main/java/io/apicurio/registry/rest/client/request/provider/Routes.java

I forgot to expose the new endpoint through the client library, and apparently, this is a blocker for further development of the Gradle plugin: https://github.com/croz-ltd/apicurio-registry-gradle-plugin/pull/16#discussion_r1241268248
Fixing this now 🙂

feat: Expose listArtifactTypes in the client library

---

app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
pom.xml

The latest patch version of Avro apparently no longer supports parsing two schemas in raw form the way this test was testing.  
I'm not convinced this test was ever doing what it implied.  I suspect that older versions of the Avro parser were simply stopping successfully after parsing an entire Avro schema.  If there was **another** Avro schema still in the buffer, it would be ignored.  But I'm not 100% sure.
@carlesarnal any thoughts on what the `testReferenceRaw` test is trying to do?  It looks to me like it's just making sure that Enum types are properly handled.  But the name of the test implies more.

Upgraded Avro and fixed a test

---

docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc

Addresses the doc aspects of https://github.com/Apicurio/apicurio-registry/issues/3315
**Note:** This PR should also be cherry picked to 2.4.x branch.

docs: fix keycloak auth server URL config

---

app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java

Hi @EricWittmann  and @carlesarnal ,
In this PR I have added checks for the `owner` to ensure it's neither `null` or an empty string. `MissingRequiredParameterException` will be thrown if the check fails.
It will close #3476 .
Thank you for reviewing.

Fix Owner Validation

---

docs/modules/ROOT/pages/getting-started/assembly-configuring-kafka-client-serdes.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-constants.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-consumer.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-producer.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-stream.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-register.adoc
docs/modules/ROOT/partials/getting-started/proc-writing-registry-client.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

- Clarify that the `AUTH_ENABLED` env var must first be set before all auth/authz config options (see https://issues.redhat.com/browse/IPT-994)
- Fix links to Keycloak and Registry Operator docs
- Minor clean up of code callout formatting
**Note**: Please cherry pick to v2.4.x and v2.5.x branches.

docs: Clarify AUTH_ENABLED required for auth/authz

---

.github/workflows/release-images.yaml

Using a customizable GitHub Actions to free disk space on Linux GitHub Actions runners.

fix: free disk space on runner to fix out of space issue

---

app/src/main/java/io/apicurio/registry/storage/ArtifactStateExt.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java

Hi @EricWittmann and @carlesarnal ,
In this PR, I have added checks to ensure that the state can be changed to the same value multiple times. It works for both `/groups/{groupId}/artifacts/{artifactId}/state` and `/groups/{groupId}/artifacts/{artifactId}/versions/{versionId}/state` endpoints. It may close #3475 .
Thank you for reviewing it.

Allow idempotent change to artifact state

---

CONTRIBUTING.md
Makefile
README.md
TESTING.md
distro/docker/pom.xml
srcclr.yml

- Add `mysql` entry to `srcclr.yml` and to the Docker submodule (`pom.xml`)
- Add `run-mysql-integration-tests` and `run-mysql-clustered-integration-tests to integration-test task on Makefile
- Typo fix on README.md, and add entry for `mysql` on CONTRIBUTING.md

fix: Build for MySQL Registry Storage

---

schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
schema-resolver/src/test/java/io/apicurio/registry/resolver/AbstractSchemaResolverTest.java
schema-resolver/src/test/java/io/apicurio/registry/resolver/ERCacheTest.java

Adds the notion of a fault tolerance in refresh for production environments where it's better to use a stale cache value than die when a cache entry refresh fails.  See issue #3807 for details.
Note, this is a port of #3809 to the 2.5.x branch, since 2.4.x is frozen.

feat(schema-cache): ERCache.configureFaultTolerantRefresh #3807

---

schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
schema-resolver/src/test/java/io/apicurio/registry/resolver/AbstractSchemaResolverTest.java
schema-resolver/src/test/java/io/apicurio/registry/resolver/ERCacheTest.java

This brings #3824 and #3823 to the mainline.  See those issues for details.

fix(schema-resolver): caching of latest artifacts and resilient schema updates

---

schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
schema-resolver/src/test/java/io/apicurio/registry/resolver/AbstractSchemaResolverTest.java
schema-resolver/src/test/java/io/apicurio/registry/resolver/ERCacheTest.java

Caching of artifacts with no version (e.g. latest) did not work because reindex would use the new key that has the artifact version that was found in the lookup.  This code changes the default behavior to index both the artifact with its version and the latest/null version.  It also exposes a configuration property (`apicurio.registry.cache-latest`) where this behavior can be disabled for use cases where caching of latest is not desired.  See #3824 for details.

fix(schema-resolver): caching of latest artifacts #3834

---

utils/maven-plugin/src/main/java/io/apicurio/registry/maven/ProtobufDirectoryParser.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufSchemaLoader.java
utils/protobuf-schema-utilities/src/test/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtilsTest.java
utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/broken/helloworld.proto
utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/mypackage0/producerId.proto
utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/mypackage2/version.proto
utils/protobuf-schema-utilities/src/test/resources/parseWithDeps/producer.proto

This is to open a discussion about a new public API to parse a file and its dependencies.
In the current state I don't like (at all) the other public API I've exposed for https://github.com/Apicurio/apicurio-registry/discussions/3819
ie
```java
Descriptors.FileDescriptor mainProtoFd = FileDescriptorUtils.parseProtoFileWithDependencies(mainProto,
mainProtoFileName,
Map.of("mypackage0/producerId.proto", importedProto1, "mypackage2/version.proto", importedProto2));
```

Add util methods to parse proto files with dependencies

---

README.md

With the fix in: https://github.com/redhat-developer/kiota-java-extra/pull/39/files the IDE integration should now work reliably.

Remove obsolete IntelliJ remark

---

.github/dependabot.yml

Thi is supposed to decrease the dependabot noise:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
I have never used this functionality, so we can merge and monitor how it goes.

Experiment: use Groups for dependabot dependencies

---

app/pom.xml
app/src/main/resources/application.properties

Added a quarkus json logging for the registry app for logs indexing into Elasticsearch/Opensearch

added a quarkus json logging for the registry app

---

schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java

Since the parameter of .orElse() is still evaluated we end up calling the registry even if the schema is found in the cache.
Using .orElseGet() instead fixes this issue.
See: https://www.baeldung.com/java-optional-or-else-vs-or-else-get
Fixes: https://github.com/Apicurio/apicurio-registry/issues/3956

Fix incorrect .orElse usage.

---

docs/modules/ROOT/partials/getting-started/con-registry-artifacts.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-automatically-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-manually-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-generating-client-sdk-using-web-console.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifact-references-using-rest-api.adoc

@EricWittmann Please review/merge and cherry pick to `2.5.x`. Thanks!
Seems like the following related example should also be merged? 
https://github.com/Apicurio/apicurio-registry-examples/pull/44

docs: add new auto artifact refs implementation in 2.5.x as tech preview feature

---

app/src/main/resources/application.properties

I was racking my brain trying to figure out why I couldn't set `registry.ccompat.max-subjects` or `registry.ccompat.use-canonical-hash`.
In our installation, everything is configured with envvars, not java properties.  These configs were not added to application.properties, so they weren't settable via envvars nor dynamically.

add missing ccompat properties

---

app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlSubmitter.java
app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/MessageType.java
app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/ArtifactRulesKey.java
app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/GlobalRuleKey.java
app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/GlobalRulesKey.java
app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/MessageTypeToKeyClass.java
app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/sql/KafkaSqlSink.java
app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/values/ArtifactRulesValue.java
app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/values/GlobalRulesValue.java
app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/values/MessageTypeToValueClass.java
integration-tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java

I'm opening this PR to add an integration test that should get run against both storages.  It should pass for sql but fail for kafkasql.
Once I confirm that the test fails for kafkasql I will try to fix the bug and update this PR.
The test failed, as expected.  I will now work on a fix for this problem in the kafkasql storage.

Fix a bug with Delete All Artifact Rules (kafkasql storage only)

---

app/src/main/java/io/apicurio/registry/storage/RegistryStorageProducer.java
app/src/main/java/io/apicurio/registry/storage/StorageBehaviorProperties.java
app/src/main/java/io/apicurio/registry/storage/impl/gitops/GitOpsRegistryStorage.java
docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc

Removes properties from empty category and duplicate `store` category, and assigns both properties to `storage` category.
For example, see broken auto-generated doc output of property in empty category:

docs: fix config properties with no category or wrong category

---

app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/H2SqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/PostgreSQLSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SQLServerSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/ContentEntityMapper.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/ContentMapper.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/DynamicConfigPropertyDtoMapper.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/StoredArtifactMapper.java
app/src/main/resources/io/apicurio/registry/storage/impl/sql/h2.ddl
app/src/main/resources/io/apicurio/registry/storage/impl/sql/mssql.ddl
app/src/main/resources/io/apicurio/registry/storage/impl/sql/postgresql.ddl
app/src/test/java/io/apicurio/registry/noprofile/rest/v3/GroupsResourceTest.java
scripts/validate-files.sh

This PR includes the following DB changes:
* Add `ON DELETE CASCADE` where appropriate to FKs
* Add FK from `artifact_branches` to `artifacts` table
* Rename `globalrules` to `global_rules`
* Rename `rules` table to `artifact_rules`
* Rename `artifactreferences` table to `content_references`
* Rename `artifactreferences` column on `content` table to `refs`
* Rename `comments` table to `version_comments`
* Organize/group table definitions within DDL file
* Create new `group_rules` table (future need)
* Standardize on `seq_name` and `seq_value` for column names in `sequences` table
* Reduce max label value column size to 512
* Add INDEX on label value columns for mssql DB flavor

[Database] Switch to cascading deletes in the DB layer where possible + some cleanup

---

app/src/main/resources/application.properties

Set the default log level for the Quarkus `OidcProvider` to `DEBUG` so that issues with authentication show up in the logs without any additional configuration.

[2.5.x] Set default log level for OIDC provider to DEBUG

---

java-sdk/pom.xml

This allows for easy overriding of the property, e.g.:
```bash
mvn clean install -f java-sdk/pom.xml -Dkiota.base.url=<my-alternative-download-location>
```

Make it easier to change the kiota base url

---

operator/pom.xml

Reverts Apicurio/apicurio-registry#4628

Revert "build(deps): bump io.quarkiverse.operatorsdk:quarkus-operator-sdk-bom from 6.3.3 to 6.6.8"

---

ui/.docker-scripts/nginx.conf

Fix for #4846 
The current Nginx configuration included in the UI container image returns 404 when directly trying to access an API version containing a period (e.g. semantic versions such as 1.0.0) due to the first location in the configuration that matches file extensions.

Nginx returns SPA when trying to access an API version containing a period

---

pom.xml

For some reason, the dependency tree was:
+- io.strimzi:kafka-oauth-client:jar:0.15.0:compile |  \- io.strimzi:kafka-oauth-common:jar:0.14.0:compile
I couldn't find out why.

fix: override version of io.strimzi:kafka-oauth-common

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java

Hey!
We came across an issue when we call the versions endpoint in ApiCurio 3.0.0.M3 using mssql as the underlying storage layer.
The limit and offset variables are not swapped for the searchVersions method (as it is done for the other ones), so the query throws an error.
See the query rewrite for mssql: https://github.com/Apicurio/apicurio-registry/blob/v3.0.0.M3/app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java#L1551
where offset and limit have a different order for mssql
And see as a reference: https://github.com/Apicurio/apicurio-registry/blob/v3.0.0.M3/app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java#L1058
where the variable bindings are swapped for mssql in one of the other methods
Currently the versions …

Fix searchVersions Method when used in ApiCurio 3.0.0.M3 with mssql as storage layer

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractHandleFactory.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/HandleFactory.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/PostgreSQLSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/RegistryDatasourceProducer.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SQLServerSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/jdb/Handle.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/jdb/HandleImpl.java

Original work by @jsenko here:
* https://github.com/Apicurio/apicurio-registry/commit/0e2242468120fa7d40c4a72aba3ef6bf6074a128#diff-9913dedb0313867dac5f172a78a03f2b7d9ec0f8a5b50018aae2376742044ec2

Moved transaction handling into Handle instead of @Transactional

---

app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/AbstractResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/CCompatConfig.java
app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/CompatibilityResourceImpl.java
app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/ConfigResourceImpl.java
app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SchemasResourceImpl.java
app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SubjectVersionsResourceImpl.java
app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SubjectsResourceImpl.java
app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/v7/ConfluentCompatApiWithGroupsTest.java
common/src/main/java/io/apicurio/registry/model/GA.java
docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
utils/tests/src/main/java/io/apicurio/registry/utils/tests/CCompatWithGroupsTestProfile.java

This change introduces a config option that, when enabled, will allow the ccompat API to support groups via a subject naming convention:
`subject` `=` `groupId` `:separator:` `artifactId`
When enabled all CCompat operations will support this new `subject` naming convention.  This allows the ccompat API to read and write artifacts in groups.

Created an option in the CCompat API to support groups via subject naming convention

---

ui/.docker-scripts/create-config.cjs

Caught this when trying to spin up apicurio-api-lifecycle-hub (undefined variable). This is a pure gut feeling fix :)

Fixes AUTH_CLIENT_ID typo

---

.github/workflows/integration-tests.yaml
.github/workflows/registry-rhbq-build.yaml
.github/workflows/release-images.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml
app/src/main/resources/application.properties
integration-tests/pom.xml
integration-tests/src/test/java/io/apicurio/deployment/RegistryDeploymentManager.java
integration-tests/src/test/java/io/apicurio/tests/ApicurioRegistryBaseIT.java
integration-tests/src/test/java/io/apicurio/tests/auth/SimpleAuthIT.java
integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
integration-tests/src/test/java/io/apicurio/tests/kafkasql/KafkaSqlSnapshottingIT.java
integration-tests/src/test/java/io/apicurio/tests/migration/DoNotPreserveIdsImportIT.java
integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/JsonSchemaSerdeIT.java
integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/ProtobufSerdeIT.java
integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/SerdesTester.java
integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/SimpleSerdesTesterBuilder.java
integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/WrongConfiguredConsumerTesterBuilder.java
integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/WrongConfiguredSerdesTesterBuilder.java
integration-tests/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java
integration-tests/src/test/resources/infra/kafka/kafka.yml
integration-tests/src/test/resources/infra/kafka/registry-kafka.yml
integration-tests/src/test/resources/junit-platform.properties
java-sdk-v2/pom.xml
java-sdk/pom.xml
pom.xml
schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java
utils/importexport/pom.xml

This PR introduces the following changes to address a few transient failures in CI:
- No more parallel build. The code generation phase is not thread safe and this was causing some build to fail. We no longer build the separe modules in parallel.
- Add a few required retries due to the nature of the kafkasql storage. All the tests are being executed in a clustered way, and this was causing a few eventual consistency issues. Added a few retries to address this problem.
- Applied a few minor improvements like not using the `install` goal to speed up the full process.
Before merging, this PR has to be squashed to prevent polluting the history.

Stabilize CI pipelines

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/H2SqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/PostgreSQLSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SQLServerSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v3/ConcurrentCreateTest.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

This PR fixes a concurrency problem in the SQL storage when creating artifacts.  There are several "upsert" style operations that must happen when creating artifacts, including:
1. Creating the Group if one does not already exist
2. Inserting Content only if it does not already exist
3. Incrementing sequences (e.g. globalId and contentId)
There were existing race conditions (database dependent) for some or all of these operations.
This PR changes 1 and 2 so that the "Ensure Group Exists" and "Ensure Content Exists" operations occur in their own transactions.  This allows us to forgo using `UPSERT` and instead simply try the `INSERT` and react to the primary key constraint violation.  If a PK violation occurs then we simply go on to the next part of the create (e.g. if creating the group …

[3.x] Concurrent artifact creation test & fixes

---

app/src/test/java/io/apicurio/registry/noprofile/JsonSerdeTest.java
app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
app/src/test/java/io/apicurio/registry/noprofile/serde/ProtobufSerdeTest.java
docs/modules/ROOT/partials/getting-started/con-registry-serdes-avro.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-constants.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc
examples/confluent-serdes/src/main/java/io/apicurio/registry/examples/confluent/serdes/ConfluentSerdesExample.java
examples/event-driven-architecture/README.md
examples/event-driven-architecture/studio-connector.json
integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/JsonSchemaSerdeIT.java
integration-tests/src/test/java/io/apicurio/tests/serdes/apicurio/ProtobufSerdeIT.java
integration-tests/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/strategy/ArtifactReference.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractKafkaSerDe.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/Default4ByteIdHandler.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/Legacy8ByteIdHandler.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/config/BaseKafkaSerDeConfig.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/headers/DefaultHeadersHandler.java
serdes/serde-common/src/test/java/io/apicurio/registry/serde/headers/DefaultHeadersHandlerTest.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/ExtJsonConverter.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/json/CompactFormatStrategy.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/json/FormatStrategy.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/json/PrettyFormatStrategy.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

This PR changes the following default configuration and behaviour in the serdes:
- Make the serdes use a 4 bytes identifier by default (8 bytes is still possible, but with a configuration).
- Make serdes use the contentId by default to better align them with other existing 3rd party serializers.
- Headers are disabled by default, so the schemaId is added to the message body by default. This was wrongly set in 2.x, and now has the correct value.

Change serdes use content id and 4 byte identifier

---

app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
serdes/generic/serde-common/src/main/java/io/apicurio/registry/serde/config/SerdeConfig.java

Fixes a problem where creating a second serializer would fail when it's trying to use an artifact that was previously registered dereferenced by adding a new configuration option to instruct the serializer to dereference the artifact when searching by content.

Fix serializer dereference

---

app/src/main/java/io/apicurio/registry/auth/AuthConfig.java
app/src/main/java/io/apicurio/registry/storage/RegistryStorageProducer.java
app/src/main/java/io/apicurio/registry/storage/impl/gitops/BlueDatasourceProducer.java
app/src/main/java/io/apicurio/registry/storage/impl/gitops/GitOpsRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/gitops/GreenDatasourceProducer.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/RegistryDatasourceProducer.java
docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc

We dropped the `.Final` convention, but some of our config properties were still documented as "available since 3.0.0.Final".

Fixed some of the "available since" info for our config properties (for 3.0.0) config

---

ui/.docker-scripts/entrypoint.sh
ui/.docker-scripts/update-base-href.cjs
ui/Dockerfile
ui/deploy-examples/build-container-image.sh
ui/deploy-examples/getting-started-context-path/docker-compose.yml
ui/deploy-examples/getting-started-context-path/nginx.conf
ui/deploy-examples/getting-started/docker-compose.yml
ui/ui-app/index.html
ui/ui-app/package-lock.json
ui/ui-app/src/app/components/header/AppHeader.tsx
ui/ui-app/src/app/components/header/AppHeaderToolbar.tsx
ui/ui-app/src/app/components/header/AvatarDropdown.tsx
ui/ui-app/src/app/components/modals/GenerateClientModal.tsx
ui/ui-app/vite.config.mts

This should support various k8s/OpenShift and Docker Compose configurations, specifically when you want the Registry API and Registry UI to be served from the same domain.
This PR includes a nice example of how to test this using a docker compose file.

feat(UI): The UI now has better support for being served from a context path

---

app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/CompatibilityResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v3/AdminResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v3/GroupsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v3/IdsResourceImpl.java

Added any missing annotations and fixed any incorrect ones

chore(annotations): Reviewed annotations in the REST layer

---

app/src/main/java/io/apicurio/registry/services/DatabaseConfigInterceptor.java
app/src/main/java/io/apicurio/registry/services/RegistryConfigSource.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractHandleFactory.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/RegistryDatasourceProducer.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlRegistryStorage.java
app/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceInterceptor
app/src/main/resources/application.properties
app/src/test/java/io/apicurio/registry/storage/util/MssqlTestProfile.java
app/src/test/java/io/apicurio/registry/storage/util/MysqlTestProfile.java
app/src/test/java/io/apicurio/registry/storage/util/PostgresqlTestProfile.java
docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
examples/confluent-serdes/pom.xml
operator/model/src/main/java/io/apicurio/registry/operator/api/v1/status/Conditions.java
pom.xml
schema-util/json/pom.xml
utils/exportConfluent/src/main/resources/application.properties

This PR upgrades Quarkus with the following additions:
- We get back to use the datasources created by Quarkus, so any other jdbc property can be configured using standard Quarkus config values.
- The appropriate datasource is activated at application startup, using the configured storage.
- It keeps the existing properties for configuring the Apicurio datasource for backwards compatibility, so we technically have two different ways of configuring the same thing, using the apicurio property and using the quarkus one (just one documented). The Apicurio property could be removed, but that would be a breaking change.

Upgrade quarkus to 3.15

---

ui/package-lock.json
ui/package.json
ui/src/services/auth/auth.service.ts

[2.6.x] Update keycloakjs and use access_token instead of id_token for oidc code path

---

app/src/main/java/io/apicurio/registry/storage/importing/v2/SqlDataUpgrader.java
app/src/test/java/io/apicurio/registry/DataUpgradeTest.java
utils/importexport/src/main/java/io/apicurio/registry/utils/impexp/EntityReader.java

As seen in:
* https://github.com/Apicurio/apicurio-registry/issues/5627

fix(import): Fix an issue where migrating from v2 to v3 failed to create the "latest" branch

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/H2SqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/MySQLSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/PostgreSQLSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SQLServerSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
app/src/main/resources/application.properties
docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc

The information is only used during dbinit and only necessary when installing two Registry instances in the same database but different db schemas.

fix(db): New config property to set the name of the db schema

---

app/src/main/java/io/apicurio/registry/services/http/CoreRegistryExceptionMapperService.java
schema-util/common/src/main/java/io/apicurio/registry/rules/RuleViolationException.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractRegistryMojo.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/TestUpdateRegistryMojo.java

As reported/discussed here:
* https://github.com/Apicurio/apicurio-registry/issues/5629

fix(maven): Improved maven plugin output on failure

---

operator/controller/src/main/resources/application.properties

Having `DEBUG` logs enabled for Quarkus is producing enormous log files.  Changing the default to `INFO`.

Default debug and test log level for Quarkus is now `INFO` instead of `DEBUG`

---

.githooks/pre-commit
install-githooks.sh

If you want to use the hook, all you need to do is:
```
./install-githooks.sh
```
That will copy the hook into `.git/hooks` and you're good to go.  Once installed, the `install.yaml` will automatically be regenerated whenever a change to the operator model is made.

chore(operator):  Created a pre-commit hook for regenerating the operator install.yaml file

---

.github/workflows/composite/setup-minikube/action.yaml
.github/workflows/operator.yaml
.github/workflows/release-operator.yaml
.github/workflows/release.yaml
operator/Makefile
operator/README.md
operator/controller/src/main/resources/application.properties
operator/install/install.yaml
operator/olm-tests/src/test/deploy/catalog/catalog.template.yaml
operator/olm-tests/src/test/java/io/apicurio/registry/operator/it/OLMITBase.java

- This workflow automates all tasks for the operator release, including creating PRs to the OperatorHub and Operator Marketplace repos, however manual intervention might be needed for those PRs to be merged.
- Since I could not fully test the workflow in an actual release, some supervision will be needed when first running this for real.
- After the first release is done, some changes have to be made since the subsequent releases have to reference the previous bundle in the channel. There is a couple of TODOs for this task.
- I've also modified the PR check workflow to improve the run time by skipping local test mode, which will only run on push.
- I've refactored Minikube setup steps into a composite action. We might use this approach in the future for e.g. Slack notifications.
- I found …

feat(operator): add release workflow

---

.github/workflows/release-images.yaml
.github/workflows/release.yaml

I've encountered a Kiota-related build error with node 18.

ci: make sure node version in workflows is 20

---

utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/MessageDefinition.java

When parsing a Protobuf schema, and then generating it back, fields marked with "optional" don't get the same label in the generated output. Instead, they become required. This patch checks per field if it needs to set the "proto3Optional" flag (ignored for oneOf fields). The flag is set if the field is optional, rendering the expected "optional" keyword in fileElement.toSchema().

[Protobuf] Fix generation of "optional" labels in proto3 schema outW

---

.github/workflows/release-operator.yaml
operator/Makefile
operator/controller/src/main/deploy/csv/apicurio-registry-3.clusterserviceversion.yaml
operator/controller/src/test/java/io/apicurio/registry/operator/it/ITBase.java
operator/install/install.yaml
operator/olm-tests/src/test/deploy/catalog/catalog.template.yaml

Should resolve workflow failures in #6193 and #6195

chore(operator): updates after the first release

---

app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SubjectsResourceImpl.java
app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/decorator/RegistryStorageDecoratorReadOnlyBase.java
app/src/main/java/io/apicurio/registry/storage/impl/gitops/GitOpsRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
app/src/test/java/io/apicurio/registry/noprofile/Ticket1062Test.java
app/src/test/java/io/apicurio/registry/storage/impl/readonly/ReadOnlyRegistryStorageTest.java
integration-tests/src/test/java/io/apicurio/tests/ConfluentBaseIT.java

* https://issues.redhat.com/browse/IPT-1062
```
If schema A contains a reference to schema B, then it should be less easy
than it is, to delete schema B whilst A still exists. Schema A will be left with
a dangling reference to a non-existent schema.
I imagine that there will be times when it is necessary to delete a schema
that is referenced by others. However, at present it seems to make no
difference whether the reference exists or not, and the API does not (so far
as I can tell) allow for any control over the way references are interpreted.
```

 Fix for JIRA ticket 1062: deleting subjects that have inbound refs using the ccompat API [3.0.x]

---

.mvn/extensions.xml
schema-util/common/src/main/java/io/apicurio/registry/content/refs/AbstractReferenceArtifactIdentifierExtractor.java
schema-util/common/src/main/java/io/apicurio/registry/content/refs/AvroReferenceArtifactIdentifierExtractor.java
schema-util/common/src/main/java/io/apicurio/registry/content/refs/DefaultReferenceArtifactIdentifierExtractor.java
schema-util/common/src/main/java/io/apicurio/registry/content/refs/ReferenceArtifactIdentifierExtractor.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/AbstractArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/ArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/AsyncApiArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/AvroArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/DefaultArtifactTypeUtilProviderImpl.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/GraphQLArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/JsonArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/KConnectArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/OpenApiArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/ProtobufArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/WsdlArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/XmlArtifactTypeUtilProvider.java
schema-util/util-provider/src/main/java/io/apicurio/registry/types/provider/XsdArtifactTypeUtilProvider.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java

Currently when defining a schema that references another schema, the apicurio-registry-maven-plugin registers the referenced schema using the parent groupid and set the referenced schema artifactid to its fullname (`groupid.artifactid`).
This issue defeats the very purpose of having separate schemas to put some avro object definition in common.
The proposed solution is to create a `ReferenceArtifactIdentifierExtractor` util that is in charge of parsing the artifact id and group id from the external reference `resource` string. An AVRO implementation just break down the resource and separate the artifact id from the group id depending on the position of the last existing `.` according to AVRO 1.12.0 specification. Other implementations are just a default one mimicking the current behavior …

fix: Wrong groupid registering referenced avro schema with apicurio-registry-maven-plugin

---

.github/workflows/composite/setup-minikube/action.yaml
.github/workflows/operator.yaml
operator/Makefile
operator/controller/src/main/deploy/operator/operator.yaml
operator/controller/src/main/deploy/rbac/cluster/cluster-role.yaml
operator/controller/src/main/java/io/apicurio/registry/operator/ConfigMapConfigSource.java
operator/controller/src/main/java/io/apicurio/registry/operator/resource/Labels.java
operator/controller/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
operator/controller/src/test/java/io/apicurio/registry/operator/it/OperatorConfigITTest.java
operator/controller/src/test/resources/k8s/examples/config/operator-config.configmap.yaml
operator/install/install.yaml
operator/olm-tests/src/test/java/io/apicurio/registry/operator/it/SmokeOLMITTest.java

feat(operator): operator should be configurable using a configmap #6194

---

app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SchemasResourceImpl.java
app/src/test/java/io/apicurio/registry/noprofile/Ticket1323Test.java

Reference:  
* https://issues.redhat.com/browse/IPT-1323
Changed the logic of this so that the artifact type is figured out based on the artifact type of the first artifact that references the content.  We need to do this because we do not store the artifact type with the content.
Technically this means that if you upload the same content for two different artifacts with **different artifact types**, then you may get the wrong response from the ccompat API when getting the schema by ID.  You'll still get the right content, but you **might** get the wrong artifact type, because there would be multiple artifacts with different types referencing the same content.

[3.0] fix(1323) : Fixed issue with ccompat API when getting invalid schema by contentId

---

.github/workflows/integration-tests.yaml
.github/workflows/operator.yaml
.github/workflows/quay-clean.yaml
.github/workflows/verify.yaml

Possible alternative to https://github.com/Apicurio/apicurio-registry/pull/6420

chore(ci): replace ghrc.io with a temporary quay.io repository (alternative)

---

schema-resolver/pom.xml
schema-resolver/src/main/java/io/apicurio/registry/resolver/client/RegistryClientFacadeImpl.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/client/RegistryClientFacadeImpl_v2.java
schema-resolver/src/test/java/io/apicurio/registry/resolver/client/RegistryClientFacadeImplTest.java

fixes https://github.com/Apicurio/apicurio-registry/issues/877
In the registry facade impl, add a check on the artifact state to filter out DISABLED artifacts.
Add unit tests dependencies (mockito + assertj) in schema resolver module
Add test case for the v3 registry client facade around ignoreing disabled artifacts versions

Ignore disabled artifact version when searching artifact by content 

---

app/src/test/java/io/apicurio/registry/noprofile/Issue6530Test.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufSchemaLoader.java

Fix for issue:
* https://github.com/Apicurio/apicurio-registry/issues/6530
I think we were not properly writing the various .proto files to the correct locations in the virtual filesystem, prior to loading them.  This caused the validity rule to fail.
The original issue did highlight this problem, although the test .proto files in the issue are not quite right.  The `UserCreated.proto` import should be `demo/UserCreated.proto` for everything to work as expected.

fix(validity-rule): Test and fix for issue #6530

---

ui/ui-app/src/app/App.tsx

- Modified authConfig logic to only use window.location.href as fallback
- Prevents overwriting of explicitly configured redirectUri values coming from app-backend as uiConfig
- Maintains backward compatibility for cases with no configured redirectUri
```
"auth": {
"type": "oidc",
"rbacEnabled": true,
"obacEnabled": false,
"options": {
"redirectUri": "http://localhost:8080",
... ... 
}
},
```

fix: prioritize configured redirectUri coming from app-backend over window.location.href

---

app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeFacadeV2Test.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/client/RegistryClientFacadeFactory.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/config/SchemaResolverConfig.java

Fix for:
* https://github.com/Apicurio/apicurio-registry/issues/6560

fix(6560) : The client facade factory now properly detects the configured endpoint version from the URL

---

app/src/main/java/io/apicurio/registry/auth/AbstractAccessController.java
app/src/main/java/io/apicurio/registry/auth/AppAuthenticationMechanism.java
app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
app/src/test/java/io/apicurio/registry/auth/CCompatAuthTest.java

Fix for issue:
* https://issues.redhat.com/browse/IPT-1186
I believe the root cause was the auth layer not checking the HTTP request for a groupId that should be used when making ccompat API calls.  Because the ccompat API does not support groups, it is possible for a request to include the groupId to use as a http header.  This override the default groupId for ccompat operations.  The auth layer was not checking that http header, so it failed to find the artifact when checking ownership.

fix(ccompat): Fixed an issue with owner only auth and the ccompat api

---

utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractRegistryMojo.java

Authentication to Entra-enabled apicurio-registry was failing with an exception, when using the maven plugin:
```
[ERROR] Exception while registering artifact [default] / [com.example.package.v1.Model]
java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.vertx.core.impl.NoStackTraceThrowable: invalid_request: AADSTS90014: The required field 'scope' is missing from the credential. Ensure that you have all the necessary parameters for the login request. Trace ID: 4dfc2eb8-cffb-447c-8806-7a127b7a1200 Correlation ID: e72690ec-ffcf-49c9-b080-b657ad905b26 Timestamp: 2025-09-30 19:28:17Z
```
After some digging around, I discovered, that the plugin was reading the `clientScope` parameter, but it is not being used.
I have also added additional logging, to see which auth, if any, …

fix: Add client scope support for OAuth2 authentication for maven plugin

---

app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/SubjectsResourceImpl.java
app/src/test/java/io/apicurio/registry/auth/CCompatAuthTest.java

The register endpoint now checks READ permission first when looking up existing schemas, and only checks WRITE permission when creating new ones. This fixes the issue where Kafka producers using Confluent Serializer with `auto.register.schemas=true` would fail even when the schema already exists and the user has READ permissions.

fix: allow read-only users to use register endpoint for existing schemas
