Apicurio/apicurio-registry

app/pom.xml
app/src/main/java/io/apicurio/registry/rest/ArtifactsResource.java
app/src/main/java/io/apicurio/registry/rest/ArtifactsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/RulesResource.java
app/src/main/java/io/apicurio/registry/rest/RulesResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/beans/ArtifactMetaData.java
app/src/main/java/io/apicurio/registry/rest/beans/EditableMetaData.java
app/src/main/java/io/apicurio/registry/rest/beans/Rule.java
app/src/main/java/io/apicurio/registry/rest/beans/VersionMetaData.java
app/src/main/java/io/apicurio/registry/rest/ccompat/AbstractResource.java
app/src/main/java/io/apicurio/registry/rest/ccompat/CompatibilityResource.java
app/src/main/java/io/apicurio/registry/rest/ccompat/ConfigResource.java
app/src/main/java/io/apicurio/registry/rest/ccompat/Errors.java
app/src/main/java/io/apicurio/registry/rest/ccompat/ModeResource.java
app/src/main/java/io/apicurio/registry/rest/ccompat/RestConstants.java
app/src/main/java/io/apicurio/registry/rest/ccompat/SchemasResource.java
app/src/main/java/io/apicurio/registry/rest/ccompat/SubjectVersionsResource.java
app/src/main/java/io/apicurio/registry/rest/ccompat/SubjectsResource.java
app/src/main/resources/META-INF/openapi.json
app/src/test/java/io/apicurio/registry/RulesResourceTest.java
app/src/test/java/io/apicurio/registry/SubjectsResourceTest.java
pom.xml

The Apicurio tool was used to generate an API project from an OpenAPI definition.  Please review this pull request, modify as necessary, and merge!

[Apicurio] Please merge generated API project

---

app/src/main/java/io/apicurio/registry/ccompat/rest/CompatibilityResource.java
app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
app/src/main/java/io/apicurio/registry/rest/ArtifactsResource.java
app/src/main/java/io/apicurio/registry/rest/ArtifactsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/RulesResource.java
app/src/main/java/io/apicurio/registry/rest/RulesResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/beans/ArtifactMetaData.java
app/src/main/java/io/apicurio/registry/rest/beans/Rule.java
app/src/main/java/io/apicurio/registry/rest/beans/VersionMetaData.java
app/src/main/java/io/apicurio/registry/rules/RuleExecutorFactory.java
app/src/main/java/io/apicurio/registry/rules/RulesServiceImpl.java
app/src/main/java/io/apicurio/registry/rules/compatibility/ArtifactTypeAdapterFactory.java
app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/RuleAlreadyExistsException.java
app/src/main/java/io/apicurio/registry/storage/RuleNotFoundException.java
app/src/main/java/io/apicurio/registry/storage/impl/AbstractMapRegistryStorage.java
app/src/main/java/io/apicurio/registry/types/ArtifactType.java
app/src/main/java/io/apicurio/registry/types/RuleType.java
app/src/main/resources/META-INF/openapi.json
app/src/test/java/io/apicurio/registry/ArtifactTypeTest.java
app/src/test/java/io/apicurio/registry/ArtifactsResourceTest.java
app/src/test/java/io/apicurio/registry/RulesResourceTest.java

The Apicurio tool was used to generate an API project from an OpenAPI definition.  Please review this pull request, modify as necessary, and merge!

[Apicurio] Added RuleType and upper-cased some enums

---

app/src/main/java/io/apicurio/registry/rules/validation/ApicurioDataModelContentValidator.java
app/src/main/java/io/apicurio/registry/rules/validation/AsyncApiContentValidator.java
app/src/main/java/io/apicurio/registry/rules/validation/ContentValidatorFactory.java
app/src/main/java/io/apicurio/registry/rules/validation/OpenApiContentValidator.java
app/src/test/java/io/apicurio/registry/rules/validation/AsyncApiContentValidatorTest.java
app/src/test/resources/io/apicurio/registry/rules/validation/asyncapi-invalid-semantics.json
app/src/test/resources/io/apicurio/registry/rules/validation/asyncapi-invalid-syntax.json
app/src/test/resources/io/apicurio/registry/rules/validation/asyncapi-valid-semantics.json
app/src/test/resources/io/apicurio/registry/rules/validation/asyncapi-valid-syntax.json

Fixes https://github.com/Apicurio/apicurio-registry/issues/17

Implemented validation rule for AsyncAPI

---

README.md
app/src/main/resources/application.properties
app/src/test/resources/application.properties
distro/docker/pom.xml
distro/docker/src/main/docker/Dockerfile.jpa.jvm
pom.xml
storage/jpa/src/main/java/io/apicurio/registry/storage/impl/jpa/JPADatabaseManager.java

I went over build and runtime configuration options (incl. JPA), and made sure users know how to run the app.
Please take a look at README.md and check it makes sense and the information is valid.
@alesj Could you please add the kafka part? Thanks.

[WIP] Clean up and document build and runtime configuration

---

README.md
storage/streams/src/main/java/io/apicurio/registry/streams/StreamsTopologyProvider.java
utils/kafka/src/main/proto/storage.proto

Mention helper scripts in README.

Remove rules state -- not needed.

---

app/pom.xml
app/src/main/java/io/apicurio/registry/metrics/AbstractErrorCounterHealthCheck.java
app/src/main/java/io/apicurio/registry/metrics/PersistenceExceptionLivenessApply.java
app/src/main/java/io/apicurio/registry/metrics/PersistenceExceptionLivenessCheck.java
app/src/main/java/io/apicurio/registry/metrics/PersistenceExceptionLivenessInterceptor.java
app/src/main/java/io/apicurio/registry/metrics/PersistenceSimpleReadinessCheck.java
app/src/main/java/io/apicurio/registry/metrics/PersistenceTimeoutReadinessApply.java
app/src/main/java/io/apicurio/registry/metrics/PersistenceTimeoutReadinessCheck.java
app/src/main/java/io/apicurio/registry/metrics/PersistenceTimeoutReadinessInterceptor.java
app/src/main/java/io/apicurio/registry/metrics/README.md
app/src/main/java/io/apicurio/registry/metrics/ResponseErrorLivenessCheck.java
app/src/main/java/io/apicurio/registry/metrics/ResponseTimeoutReadinessCheck.java
app/src/main/java/io/apicurio/registry/rest/ArtifactsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/RegistryExceptionMapper.java
app/src/main/java/io/apicurio/registry/storage/RegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/InMemoryRegistryStorage.java
storage/jpa/src/main/java/io/apicurio/registry/storage/impl/jpa/JPARegistryStorage.java
storage/kafka/src/main/java/io/apicurio/registry/kafka/KafkaRegistryStorage.java

Run the app and then `curl -v http://localhost:8080/health`
The commit also contains some minor automatic formatting changes, I can remove them if needed. Maybe we could decide on a common code style.

Readiness and Liveness reports

---

docs/pom.xml
docs/rest-api-docs/index.html
docs/rest-api/README.md
docs/rest-api/pom.xml
docs/rest-api/src/main/assembly/static-assembly.xml
docs/rest-api/src/main/resources/index.html
docs/rest-api/src/main/resources/run.sh
pom.xml

Add .html file to render REST API docs using Redoc tool

Add REST API docs

---

.checkstyle/checkstyle.xml
.checkstyle/java.header
.checkstyle/suppressions.xml
tests/TESTING.md
tests/pom.xml
tests/src/main/java/io/apicurio/tests/Constants.java
tests/src/main/java/io/apicurio/tests/KafkaFacade.java
tests/src/main/java/io/apicurio/tests/RegistryFacade.java
tests/src/main/java/io/apicurio/tests/executor/Exec.java
tests/src/main/java/io/apicurio/tests/executor/ExecResult.java
tests/src/main/java/io/apicurio/tests/interfaces/ExtensionContextParameterResolver.java
tests/src/main/java/io/apicurio/tests/interfaces/TestSeparator.java
tests/src/main/java/io/apicurio/tests/utils/BaseHttpUtils.java
tests/src/main/java/io/apicurio/tests/utils/subUtils/ArtifactUtils.java
tests/src/main/java/io/apicurio/tests/utils/subUtils/GlobalRuleUtils.java
tests/src/main/java/io/apicurio/tests/utils/subUtils/TestUtils.java
tests/src/main/resources/log4j.properties
tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/MetadataIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/MetadataConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java
tests/src/test/resources/application.properties

* feature
This PR also add some basic tests for `confluent` and `apicurio` artifacts, metadata, versions and rules.

[MO/JS] - [it tests] -> smoke tests done

---

app/pom.xml
pom.xml
tests/TESTING.md
tests/pom.xml
tests/src/main/java/io/apicurio/tests/Constants.java
tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/MetadataIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/MetadataConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java

HttpUtils to apicurio client
This PR adding reworked apicurio API tests to apicurio client.

[MO] - [apicurio api] -  httpUtils -> apicurio client

---

tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java

Enhancement
Clearning environmnent(confluent schemas) before all tests

[MO] - [tests] -> adding clearing confluent subjects

---

docs/modules/getting-started/c_intro-to-registry.adoc
docs/modules/getting-started/c_registry_rules.adoc
docs/modules/getting-started/p_installing-registry-in-memory-storage.adoc
docs/modules/getting-started/p_installing-registry-jpa-storage.adoc
docs/modules/getting-started/p_installing-registry-kafka-storage.adoc
docs/modules/getting-started/p_installing-registry-kafka-streams-storage.adoc

Adds review feedback from eric, links to OpenShift templates

Update Getting Started with links to OpenShift templates 

---

docs/assemblies/getting-started/as_installing-the-registry.adoc
docs/assemblies/getting-started/as_intro-to-the-registry.adoc
docs/index.adoc
docs/modules/getting-started/c_intro-to-registry.adoc
docs/modules/getting-started/c_registry_rules.adoc
docs/modules/getting-started/p_installing-registry-kafka-kubernetes-storage.adoc

Verify install steps for AMQ Streams on OpenShift and tidy up

Verify install steps

---

docs/assemblies/getting-started/as_intro-to-the-registry.adoc
docs/modules/getting-started/c_intro-to-registry.adoc
docs/modules/getting-started/c_registry_rules.adoc
docs/modules/getting-started/p_installing-registry-kafka-kubernetes-storage.adoc

Add peer review feedback and links to blog articles and demos

add peer review feedback

---

app/src/main/java/io/apicurio/registry/ibmcompat/api/impl/ApiServiceImpl.java
app/src/test/java/io/apicurio/registry/AbstractRegistryTestBase.java
app/src/test/java/io/apicurio/registry/util/PropertiesLoader.java
app/src/test/java/io/confluent/connect/avro/AvroData.java
search/client/src/main/java/io/apicurio/registry/search/client/hotrod/HotRodSearchClient.java
search/client/src/main/java/io/apicurio/registry/search/client/rest/RestSearchClient.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroData.java

Code improvements / polish
- Close getResourceAsStream input stream
- Compare values using .equals
- Eliminate unnecessary local store
- Use %n instead of \n for String.format

Code improvements / polish

---

distro/connect-converter/pom.xml
distro/docker-compose/pom.xml
distro/pom.xml

Add the ability to set the tarLongFileMode of the assemblies, keep the default of gnu

Add the ability to set the tarLongFileMode of the assemblies

---

app/src/test/java/io/apicurio/registry/AbstractRegistryTestBase.java
app/src/test/java/io/apicurio/registry/ArtifactStateTest.java
app/src/test/java/io/apicurio/registry/RegistryClientTest.java
app/src/test/java/io/apicurio/registry/RegistryConverterTest.java
app/src/test/java/io/apicurio/registry/RegistrySerdeTest.java
app/src/test/java/io/apicurio/registry/cluster/ClusterIT.java
app/src/test/java/io/apicurio/registry/maven/DownloadRegistryMojoTest.java
app/src/test/java/io/apicurio/registry/maven/RegisterRegistryMojoTest.java
app/src/test/java/io/apicurio/registry/maven/TestUpdateRegistryMojoTest.java
tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/MetadataIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java

Ensure UTF-8 is used

---

docs/assemblies/getting-started/as_intro-to-registry-rules.adoc
docs/assemblies/getting-started/as_managing-registry-artifacts.adoc
docs/getting-started/master-docinfo.xml
docs/getting-started/master.adoc
docs/modules/getting-started/con_registry-overview.adoc
docs/modules/getting-started/proc_installing-registry-kafka-kubernetes-storage.adoc
docs/modules/getting-started/proc_managing-artifacts-using-client-code.adoc
docs/modules/getting-started/proc_managing-artifacts-using-maven-plugin.adoc
docs/modules/getting-started/proc_managing-artifacts-using-rest-api.adoc
docs/modules/getting-started/proc_setting-up-kafka-kubernetes-storage.adoc
docs/modules/getting-started/ref_registry-artifact-types.adoc
docs/modules/getting-started/ref_registry-rule-types.adoc

add new chapters on managing artifacts using rest api, maven plugin, client code, some restructuring

new chapters on managing artifacts

---

docs/assemblies/getting-started/as_installing-the-registry.adoc
docs/assemblies/getting-started/as_intro-to-registry-rules.adoc
docs/assemblies/getting-started/as_intro-to-the-registry.adoc
docs/modules/getting-started/con_registry-overview.adoc
docs/modules/getting-started/con_registry-rules.adoc
docs/modules/getting-started/proc_installing-registry-kafka-kubernetes-storage.adoc
docs/modules/getting-started/proc_managing-artifacts-using-client-code.adoc
docs/modules/getting-started/proc_managing-artifacts-using-maven-plugin.adoc
docs/modules/getting-started/proc_managing-artifacts-using-rest-api.adoc
docs/modules/getting-started/proc_setting-up-kafka-kubernetes-storage.adoc
docs/modules/getting-started/ref_registry-artifact-types.adoc
docs/shared/attributes.adoc

- Add new APPLICATION_SERVER_HOST and APPLICATION_SERVER_PORT parameters. 
- Tidy up latest draft for review

update install docs with new env params

---

app/src/test/java/io/apicurio/registry/compatibility/CompatibilityRuleApplicationTest.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/AvroConverter.java

This PR is in reference to issue https://github.com/Apicurio/apicurio-registry/issues/378 - "Set sensible defaults for Avro converter".

Set sensible defaults for Avro converter

---

app/src/main/java/io/apicurio/registry/util/ArtifactTypeUtil.java
app/src/test/java/io/apicurio/registry/util/ArtifactTypeUtilTest.java
app/src/test/resources/io/apicurio/registry/util/wsdl-2.0.wsdl
app/src/test/resources/io/apicurio/registry/util/wsdl.wsdl
app/src/test/resources/io/apicurio/registry/util/xml-schema.xsd
app/src/test/resources/io/apicurio/registry/util/xml.xml

@EricWittmann  as per comment at https://github.com/Apicurio/apicurio-registry/pull/355#issuecomment-609937441
Try to detect what type of XML format is being sent when no type is defined

Autodetect xml type

---

tests/src/main/resources/log4j2.xml

This was a miss from https://github.com/Apicurio/apicurio-registry/pull/435

tests, adding back log4j config.

---

app/src/main/java/io/apicurio/registry/rest/ArtifactsResourceImpl.java
app/src/test/java/io/apicurio/registry/ArtifactStateTest.java
app/src/test/java/io/apicurio/registry/ArtifactsResourceTest.java
app/src/test/java/io/apicurio/registry/JsonSerdeTest.java
app/src/test/java/io/apicurio/registry/RegistryClientTest.java
app/src/test/java/io/apicurio/registry/RegistrySerdeTest.java
app/src/test/java/io/apicurio/registry/cluster/ClusterIT.java
app/src/test/java/io/apicurio/registry/content/ContentExtractorTest.java
app/src/test/java/io/apicurio/registry/maven/DownloadRegistryMojoTest.java
app/src/test/java/io/apicurio/registry/maven/TestUpdateRegistryMojoTest.java
client/src/main/java/io/apicurio/registry/client/CachedRegistryService.java
common/src/main/java/io/apicurio/registry/rest/ArtifactsResource.java
common/src/main/java/io/apicurio/registry/rest/beans/IfExistsType.java
common/src/main/resources/META-INF/openapi.json
tests/src/main/java/io/apicurio/tests/utils/subUtils/ArtifactUtils.java
tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/strategy/AbstractCrudIdStrategy.java

@carlesarnal I've created a new branch `issues/362` so we can collaborate on this.  The branch exists on the upstream repository.  So you should be able to check it out and work on the back-end impl.

Added a query param to Create Artifact (ifExists)

---

utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

Fixes api path in registry url, as we had it worked with local deployment and failed on CI

tests - fix api path

---

utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

from #489 I forgot one place to add api path

tests - external registry - fix api path

---

ui/pom.xml

Add proxy settings too ui to support building behind a firewall.

Add proxy settings to ui

---

storage/streams/src/main/java/io/apicurio/registry/streams/StreamsRegistryStorage.java
tests/src/test/java/io/apicurio/tests/ConfluentBaseIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java

Fixes a bug in streams storage where deleteing an artifact always thrown artifact not found exception.
The code change I did in stream storage is inspired in what I've seen in other storages implementation

fix delete artifact bug in streams storage

---

storage/jpa/src/main/java/io/apicurio/registry/storage/impl/jpa/JPARegistryStorage.java

Fixes #516 and adds missing @Transactional annotation

add missing @Transactional

---

ui/packages/registry/src/app/pages/artifactVersion/components/tabs/info.tsx
ui/packages/registry/src/app/pages/artifacts/components/artifactList/artifactList.tsx
ui/packages/registry/src/app/pages/artifacts/components/artifactList/artifactName.tsx
ui/packages/registry/src/app/pages/artifacts/components/artifactList/index.ts

Improved presentation of artifacts in UI when they have no name

---

docs/assemblies/getting-started/as_intro-to-the-registry.adoc
docs/getting-started/master-docinfo.xml
docs/modules/getting-started/con_registry-overview.adoc
docs/modules/getting-started/ref_registry-artifact-types.adoc
docs/shared/attributes-links.adoc
docs/shared/attributes.adoc

Add intro to Kafka Connect convertors, links for more info, tidy up

Kafka connect converters

---

storage/jpa/src/main/java/io/apicurio/registry/storage/impl/jpa/JPARegistryStorage.java

Hi @EricWittmann, If I got right how the versions are working, this should solve the possible race condition.

Add lock for max version selection

---

app/src/main/java/io/apicurio/registry/rest/ArtifactsResourceImpl.java
common/src/main/java/io/apicurio/registry/rest/ArtifactsResource.java
common/src/main/java/io/apicurio/registry/types/ArtifactMediaTypes.java
common/src/main/resources/META-INF/openapi.json
ui/packages/models/src/contentTypes.model.ts
ui/packages/registry/package.json
ui/packages/services/package.json
ui/packages/services/src/artifacts/artifacts.service.ts
ui/yarn.lock

Only relevant when the user does not specify the artifact type in the form (when creating a new artifact).

Improved the artifact type negotiation between UI and back-end

---

pom.xml

upgraded to Quarkus 1.3.3.Final

---

docs/assemblies/getting-started/as_managing-registry-artifacts.adoc
docs/modules/getting-started/con_registry-overview.adoc
docs/modules/getting-started/con_registry-rules.adoc
docs/modules/getting-started/proc_adding-artifacts-using-console.adoc
docs/modules/getting-started/proc_browsing-artifacts-using-console.adoc
docs/modules/getting-started/proc_configuring-rules-using-console.adoc
docs/modules/getting-started/proc_managing-artifacts-using-client-code.adoc
docs/modules/getting-started/proc_managing-artifacts-using-rest-api.adoc
docs/modules/getting-started/ref_registry-rule-types.adoc

First draft of user doc for new user interface

Add UI doc topics

---

tests/src/test/java/io/apicurio/tests/ConfluentBaseIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java

Adds some active wait to confluent tests for more stable test runs

confluent tests - wait for subject deleted

---

app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
app/src/test/java/io/apicurio/registry/ArtifactsResourceTest.java
app/src/test/java/io/apicurio/registry/FullApiTest.java
app/src/test/java/io/apicurio/registry/RulesResourceTest.java
app/src/test/java/io/apicurio/registry/SerdeMixTest.java
app/src/test/java/io/apicurio/registry/storage/RegistryStorageSmokeTest.java
storage/asyncmem/src/main/java/io/apicurio/registry/asyncmem/AsyncInMemoryRegistryStorage.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

Updated all tests that failed as a consequence of the change to asyncmem storage.

made asyncmem deletes asynchronous

---

app/src/test/java/io/apicurio/registry/SerdeMixTest.java

fix unit test

---

app/src/main/java/io/apicurio/registry/storage/impl/AbstractMapRegistryStorage.java
app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
app/src/test/java/io/apicurio/registry/ArtifactStateTest.java
app/src/test/java/io/apicurio/registry/ArtifactsResourceTest.java
app/src/test/java/io/apicurio/registry/ConfluentCompatApiTest.java
app/src/test/java/io/apicurio/registry/FullApiTest.java
app/src/test/java/io/apicurio/registry/RegistryClientTest.java
app/src/test/java/io/apicurio/registry/RulesResourceTest.java
app/src/test/java/io/apicurio/registry/storage/RegistryStorageSmokeTest.java
storage/asyncmem/src/main/java/io/apicurio/registry/asyncmem/AsyncInMemoryRegistryStorage.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

Tests are updated to fully account for async storages now.

All asyncmem storage functions are now async

---

docs/assemblies/getting-started/as_artifact-rule-types.adoc
docs/assemblies/getting-started/as_installing-the-registry.adoc
docs/assemblies/getting-started/as_intro-to-registry-rules.adoc
docs/assemblies/getting-started/as_intro-to-the-registry.adoc
docs/assemblies/getting-started/as_managing-registry-artifacts.adoc
docs/getting-started/master-docinfo.xml
docs/getting-started/master.adoc
docs/modules/getting-started/con_registry-distros.adoc
docs/modules/getting-started/con_registry-overview.adoc
docs/modules/getting-started/con_registry-rules.adoc
docs/modules/getting-started/proc_adding-artifacts-using-console.adoc
docs/modules/getting-started/proc_browsing-artifacts-using-console.adoc
docs/modules/getting-started/proc_configuring-rules-using-console.adoc
docs/modules/getting-started/proc_installing-kafka-streams-operatorhub.adoc
docs/modules/getting-started/proc_installing-postgresql-operatorhub.adoc
docs/modules/getting-started/proc_installing-registry-kafka-streams-template-storage.adoc
docs/modules/getting-started/proc_installing-registry-operatorhub.adoc
docs/modules/getting-started/proc_managing-artifacts-using-client-code.adoc
docs/modules/getting-started/proc_managing-artifacts-using-rest-api.adoc
docs/modules/getting-started/proc_setting-up-infinispan-storage.adoc
docs/modules/getting-started/proc_setting-up-kafka-kubernetes-storage.adoc
docs/modules/getting-started/proc_setting-up-kafka-streams-storage.adoc
docs/modules/getting-started/proc_setting-up-postgresql-storage.adoc
docs/modules/getting-started/ref_registry-rule-types.adoc
docs/shared/attributes.adoc

Steps for installing with Streams, Infinispan, and PostgreSQL storage

Update operator install steps

---

docs/assemblies/getting-started/as_installing-the-registry.adoc
docs/modules/getting-started/con_registry-storage.adoc
docs/modules/getting-started/proc_adding-artifacts-using-console.adoc
docs/modules/getting-started/proc_installing-kafka-streams-operatorhub.adoc
docs/modules/getting-started/proc_installing-postgresql-operatorhub.adoc
docs/modules/getting-started/proc_installing-registry-operatorhub.adoc
docs/modules/getting-started/proc_managing-artifacts-using-client-code.adoc
docs/modules/getting-started/proc_managing-artifacts-using-maven-plugin.adoc
docs/modules/getting-started/proc_managing-artifacts-using-rest-api.adoc
docs/modules/getting-started/proc_setting-up-infinispan-storage.adoc
docs/modules/getting-started/proc_setting-up-kafka-streams-storage.adoc
docs/modules/getting-started/proc_setting-up-postgresql-storage.adoc
docs/shared/attributes.adoc

Technical review feedback on installing and managing chapters

Add doc feedback install

---

docs/modules/getting-started/con_kafka-connect-converters.adoc
docs/readme.adoc
docs/shared/attributes-links.adoc

Add simple local build instructions for user docs, change CDC attributes to Debezium

Add user doc build steps to readme

---

.github/project.yaml
.github/workflows/release.yaml

Added step to tweet about the release
Retry maven deploy step 3 times
Other fixes to the flow due to steps introduced for apicurio website changes
Added comments to project.yaml for clarity

Enhancements to the release workflow

---

app/src/test/java/io/apicurio/registry/ConfluentClientTest.java
app/src/test/java/io/apicurio/registry/SerdeMixTest.java
pom.xml
tests/src/test/java/io/apicurio/tests/ConfluentBaseIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/MetadataConfluentIT.java
tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java

Introduced presumably when we upgraded the confluent client version.

Fixed multiple deprecation warnings in tests

---

.github/workflows/integration-tests.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml

Extracted out Integration tests as a separate worflow
Changed runner OS from 'ubuntu-latest' to 'ubuntu-18.04'

Workflow enhancements

---

app/src/main/java/io/apicurio/registry/ibmcompat/api/impl/ApiServiceImpl.java
app/src/test/java/io/apicurio/registry/ibmcompat/IBMCompatApiTest.java

- This commit fixes the response from the ibmcompat schema
verification calls to return the schema contents as a JSON-escaped
string, to match the openapi definition for the ibmcompat API. This is
on the following endpoints:
- `POST /api/ibmcompat/schemas?verify=true`
- `POST /api/ibmcompat/schemas/{schemaid}/versions?verify=true`

Return JSON-escaped strings from ibmcompat schema verification requests

---

.github/workflows/release.yaml

Updated the release script to also automate the building and releasing of the documentation

Build registry docs as part of release script

---

app/src/test/java/io/apicurio/registry/RegistrySerdeTest.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AbstractKafkaDeserializer.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AbstractKafkaSerDe.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AbstractKafkaSerializer.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AbstractKafkaStrategyAwareSerDe.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AvroEncoding.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AvroKafkaDeserializer.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AvroKafkaSerializer.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/JsonSchemaKafkaDeserializer.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/ProtobufKafkaDeserializer.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/ProtobufKafkaSerializer.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/util/HeaderUtils.java

Add option to use headers instead of magic byte for serializing the global-ids

Add support for clean Avro issue#643

---

storage/jpa/src/main/java/io/apicurio/registry/storage/impl/jpa/JPARegistryStorage.java

Remove version metadata in case of artifact state updated to DELETED

---

rest-client/src/main/java/io/apicurio/registry/client/CompatibleClient.java
rest-client/src/main/java/io/apicurio/registry/client/RegistryRestClientFactory.java
rest-client/src/main/java/io/apicurio/registry/client/request/HeadersInterceptor.java
utils/serde/src/main/java/io/apicurio/registry/utils/serde/AbstractKafkaSerDe.java

Add additional headers to registry client via config
Signed-off-by: A. Garrard <GARRARD@uk.ibm.com>

Add ability to provide additional headers issue 827

---

distro/connect-converter/src/assembly/converter-distribution.xml

See:  https://github.com/Apicurio/apicurio-registry/issues/497

Reduced the list of dependencies packaged in the Kafka Connector distro

---

.github/workflows/integration-tests.yaml
tests/pom.xml
tests/src/main/java/io/apicurio/tests/KafkaFacade.java
tests/src/main/java/io/apicurio/tests/RegistryFacade.java
tests/src/main/java/io/apicurio/tests/serdes/KafkaClients.java
tests/src/test/java/io/apicurio/tests/BaseIT.java
tests/src/test/java/io/apicurio/tests/serdes/apicurio/BasicApicurioSerDesIT.java
tests/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/ExtJsonConverter.java

I don't know why this tests were removed from PR's, adding it back

Execute integration tests in PRs

---

.github/scripts/collect_kubernetes_logs.sh
.github/scripts/test_apicurio_kubernetes.sh
.github/workflows/verify.yaml

Adds to the verify workflow, when it builds and pushes docker images, the test of that images in kubernetes using the new e2e testsuite

add kubernetes tests with e2e testsuite

---

app/src/main/java/io/apicurio/registry/ccompat/dto/CompatibilityLevelDto.java

for compatibility.
https://docs.confluent.io/current/schema-registry/develop/api.html#get--config-(string-%20subject)
https://github.com/Apicurio/apicurio-registry/issues/700

Alias compatibilityLevel to compatibility

---

tests/src/test/java/io/apicurio/tests/ui/DeleteArtifactIT.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

This will help with tests stability.

Increase retries on all tests and increase timeouts in some UI tests

---

pom.xml
storage/infinispan/src/main/java/io/apicurio/registry/infinispan/InfinispanConfiguration.java

Remove infinispan.version duplicated definition

---

storage/jpa/src/main/java/io/apicurio/registry/storage/impl/jpa/JPARegistryStorage.java

fix sql injection

---

docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-concepts.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-strategy.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-types.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-consumer.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-producer.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-stream.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-register.adoc

This was done to document the new Avro encoding option from here:  https://github.com/Apicurio/apicurio-registry/pull/774

Added avro and json schema serde documentation

---

cli/README.md
cli/pom.xml
cli/src/main/java/io/apicurio/registry/cli/AbstractCommand.java
cli/src/main/java/io/apicurio/registry/cli/ArtifactCommand.java
cli/src/main/java/io/apicurio/registry/cli/CUArtifactCommand.java
cli/src/main/java/io/apicurio/registry/cli/CUCommand.java
cli/src/main/java/io/apicurio/registry/cli/CUJsonCommand.java
cli/src/main/java/io/apicurio/registry/cli/ClearCommand.java
cli/src/main/java/io/apicurio/registry/cli/CreateCommand.java
cli/src/main/java/io/apicurio/registry/cli/DeleteCommand.java
cli/src/main/java/io/apicurio/registry/cli/EntryCommand.java
cli/src/main/java/io/apicurio/registry/cli/ExitCommand.java
cli/src/main/java/io/apicurio/registry/cli/GetCommand.java
cli/src/main/java/io/apicurio/registry/cli/ListCommand.java
cli/src/main/java/io/apicurio/registry/cli/ListRulesCommand.java
cli/src/main/java/io/apicurio/registry/cli/Main.java
cli/src/main/java/io/apicurio/registry/cli/MainCommand.java
cli/src/main/java/io/apicurio/registry/cli/MetadataCommand.java
cli/src/main/java/io/apicurio/registry/cli/UpdateCommand.java
cli/src/main/java/io/apicurio/registry/cli/UpdateMetadataCommand.java
cli/src/main/java/io/apicurio/registry/cli/UpdateStateCommand.java
cli/src/main/java/io/apicurio/registry/cli/VersionsCommand.java
pom.xml

Run the new cli jar: java -jar cli.jar ... to get the cool interactive shell

Initial CLI poc.

---

.github/workflows/integration-tests.yaml
.github/workflows/verify.yaml
storage/ksql/src/main/java/io/apicurio/registry/storage/impl/ksql/KafkaSqlRegistryStorage.java

Adds missing integration tests in GH actions + fixes some bugs in storage impl. For #1026

run integration tests and fix storage bug

---

tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java

Added one test to acceptance profile that reproduces a bug in sql storage.
Sql storage is not throwing ArtifactNotFoundException on methods related to artifact rules.

Fix sql storage bug - artifact rules now throwing ArtifactNotFoundException

---

tests/pom.xml
tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java

This PR is so #1065 can be closed

tests - remove vertx dep

---

storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlConfiguration.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlFactory.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java
utils/kafka/src/main/java/io/apicurio/registry/utils/kafka/KafkaUtil.java
utils/kafka/src/test/java/io/apicurio/registry/test/utils/KafkaTestContainerManager.java

Auto-create the Kafka topics if missing.

---

app/src/main/java/io/apicurio/registry/events/EventSourcedRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/AbstractMapRegistryStorage.java
app/src/test/java/io/apicurio/registry/rest/v2/GroupsResourceTest.java
app/src/test/java/io/apicurio/registry/rest/v2/IdsResourceTest.java
app/src/test/java/io/apicurio/registry/storage/AbstractRegistryStorageTest.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/sql/KafkaSqlStore.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStatements.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/SqlUtil.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/ArtifactMetaDataDtoMapper.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/ArtifactVersionMetaDataDtoMapper.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/SearchedArtifactMapper.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/mappers/SearchedVersionMapper.java
utils/sql/src/main/resources/io/apicurio/registry/storage/impl/sql/h2.ddl
utils/sql/src/main/resources/io/apicurio/registry/storage/impl/sql/postgresql.ddl

Implements the sql storage for the v2 api

SQL storage - artifact groups

---

utils/kafka/src/test/java/io/apicurio/registry/test/utils/KafkaRetryTest.java

Reduce timeout for KafkaRetryTest

---

app/src/main/java/io/apicurio/registry/rules/compatibility/JsonSchemaCompatibilityChecker.java
app/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/NumberSchemaDiffVisitor.java
app/src/test/java/io/apicurio/registry/compatibility/CompatibilityRuleApplicationTest.java

Incorrect transitive compatibility checking for JSON schemas.

---

app/src/main/java/io/apicurio/registry/ccompat/rest/CompatibilityResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/ConfigResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/ModeResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/SchemasResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/SubjectVersionsResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/SubjectsResource.java
app/src/main/java/io/apicurio/registry/ibmcompat/api/Api.java
app/src/main/java/io/apicurio/registry/rest/CompatibilityV1ApiRequestFilter.java
app/src/main/java/io/apicurio/registry/rest/RegistryApplication.java
app/src/main/java/io/apicurio/registry/rest/v1/ArtifactsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v1/IdsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v1/RulesResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v1/SearchResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/AdminResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/IdsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/SearchResourceImpl.java
app/src/test/java/io/apicurio/registry/rest/v1/FullApiTest.java
common/src/main/java/io/apicurio/registry/rest/v1/ArtifactsResource.java
common/src/main/java/io/apicurio/registry/rest/v1/IdsResource.java
common/src/main/java/io/apicurio/registry/rest/v1/RulesResource.java
common/src/main/java/io/apicurio/registry/rest/v1/SearchResource.java
common/src/main/java/io/apicurio/registry/rest/v2/AdminResource.java
common/src/main/java/io/apicurio/registry/rest/v2/GroupsResource.java
common/src/main/java/io/apicurio/registry/rest/v2/IdsResource.java
common/src/main/java/io/apicurio/registry/rest/v2/SearchResource.java

compatibility request filter for the old /api/ path

---

.github/workflows/integration-tests-artifact-groups-branch.yaml
app/src/main/java/io/apicurio/registry/storage/ArtifactNotFoundException.java
app/src/main/java/io/apicurio/registry/storage/impl/MetaDataKeys.java
app/src/test/java/io/apicurio/registry/RegistryClientTest.java
app/src/test/java/io/apicurio/registry/cluster/ClusterIT.java
app/src/test/java/io/apicurio/registry/rest/v2/AdminResourceTest.java
client/src/main/java/io/apicurio/registry/rest/client/request/BodyHandler.java
client/src/main/java/io/apicurio/registry/rest/client/request/Request.java
client/src/main/java/io/apicurio/registry/rest/client/request/RequestHandler.java
client/src/main/java/io/apicurio/registry/rest/client/request/provider/AdminRequestsProvider.java
client/src/main/java/io/apicurio/registry/rest/client/request/provider/GroupRequestsProvider.java
client/src/main/java/io/apicurio/registry/rest/client/request/provider/IdRequestsProvider.java
client/src/main/java/io/apicurio/registry/rest/client/request/provider/SearchRequestsProvider.java
storage/streams/src/main/java/io/apicurio/registry/streams/StreamsRegistryConfiguration.java
storage/streams/src/main/java/io/apicurio/registry/streams/StreamsRegistryStorage.java
storage/streams/src/main/java/io/apicurio/registry/streams/StreamsTopologyProvider.java
storage/streams/src/main/java/io/apicurio/registry/streams/utils/ArtifactKeyDeserializer.java
storage/streams/src/main/java/io/apicurio/registry/streams/utils/ArtifactKeySerde.java
storage/streams/src/main/java/io/apicurio/registry/streams/utils/ArtifactKeySerializer.java
storage/streams/src/main/java/io/apicurio/registry/streams/utils/WaitForDataService.java
utils/kafka/src/main/java/io/apicurio/registry/utils/kafka/Submitter.java
utils/kafka/src/main/proto/storage.proto
utils/streams/src/main/java/io/apicurio/registry/utils/streams/distore/DistributedReadOnlyKeyValueStore.java
utils/streams/src/main/java/io/apicurio/registry/utils/streams/distore/ExtReadOnlyKeyValueStore.java
utils/streams/src/main/java/io/apicurio/registry/utils/streams/distore/ExtReadOnlyKeyValueStoreImpl.java
utils/streams/src/main/java/io/apicurio/registry/utils/streams/distore/FilterPredicate.java
utils/streams/src/main/java/io/apicurio/registry/utils/streams/distore/KeyValueStoreGrpcImplLocalDispatcher.java
utils/streams/src/main/java/io/apicurio/registry/utils/streams/distore/ReadOnlyKeyValueStoreGrpcClient.java
utils/streams/src/main/proto/distore.proto

- Added artifact groups
- Improved search
- Added log customization
- Content separated from artifact

Add artifact groups streams storage 1180

---

app/src/main/java/io/apicurio/registry/logging/LoggingInterceptor.java
perftest/src/test/scala/simulations/InitialLoadSimulation.scala
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlSubmitter.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/BootstrapKey.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/MessageType.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/MessageTypeToKeyClass.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/sql/KafkaSqlSink.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/values/MessageTypeToValueClass.java

This is the bootstrap-message approach discussed in #1071 - this solution is temporary until a more elegant approach can be found.

Implemented a simple bootstrap check for kafka+sql storage.  Fixes #1071

---

app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/SearchResourceImpl.java
app/src/main/java/io/apicurio/registry/storage/dto/SearchFilterType.java
app/src/main/java/io/apicurio/registry/storage/impl/AbstractMapRegistryStorage.java
app/src/main/java/io/apicurio/registry/ui/servlets/SpecUrlFilter.java
app/src/main/resources-unfiltered/META-INF/resources/api-specifications/registry/v2/openapi.json
app/src/main/resources-unfiltered/META-INF/resources/apidocs/index.html
app/src/main/resources-unfiltered/META-INF/web.xml
app/src/test/java/io/apicurio/registry/rest/v2/SearchResourceTest.java
common/src/main/java/io/apicurio/registry/rest/v2/SearchResource.java
utils/sql/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java

@carlesarnal I need your help to update the streams storage to support query by contentHash and canonicalHash.

Implement artifact search by content.  Fixes #1267

---

integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/SerdesTester.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/SimpleSerdesTesterBuilder.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/WrongConfiguredConsumerTesterBuilder.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/confluent/BasicConfluentSerDesIT.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractKafkaDeserializer.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractKafkaSerDe.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractKafkaSerializer.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractSchemaResolver.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/DefaultIdHandler.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/DefaultSchemaResolver.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/IdHandler.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/Legacy4ByteIdHandler.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/SchemaLookupResult.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/SchemaResolver.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeHeaders.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/config/BaseKafkaSerDeConfig.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/config/DefaultSchemaResolverConfig.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/config/IdOption.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/headers/DefaultHeadersHandler.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/headers/DefaultHeadersHandlerConfig.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/strategy/ArtifactReference.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/json/CompactFormatStrategy.java

implements the serdes part for #796 
there are two new tests (disabled at the moment), for testing the related changes to the ccompat api

serdes use contentId option

---

.github/workflows/nightly-build.yaml

Note: Please expect inconsistency in the job scheduling. The scheduled workflow doesn't necessarily get triggered exactly at the scheduled time.

add nightly build workflow

---

docs/modules/ROOT/nav.adoc

Condition is not required in upstream nav.adoc

Show Docker install docs in v1.3 table of contents

---

app/src/test/java/io/apicurio/registry/auth/SimpleAuthTest.java
app/src/test/java/io/apicurio/registry/maven/MojoAuthTest.java
app/src/test/java/io/apicurio/registry/maven/RegisterRegistryMojoTest.java
app/src/test/java/io/apicurio/registry/maven/RegistryMojoTestBase.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractRegistryMojo.java

Added authentication configuration properties to the maven plugin as parameters plus execute one mojo test with auth enabled.

Add auth config properties to maven plugin

---

docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serde.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-avro.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-concepts.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-constants.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-json.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-protobuf.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-strategy.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-types.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifacts-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-consumer.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-producer.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-stream.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-register.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-artifact-types.adoc

Based on review feedback from Fabian and Eric and from looking at the updated v2 code base and example applications

Serdes doc refactoring

---

docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
docs/modules/ROOT/pages/getting-started/assembly-using-the-registry-client.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-concepts.adoc

Fixes https://github.com/Apicurio/apicurio-registry/issues/1121

Make it clear that serdes are for Java clients

---

app/src/main/resources-unfiltered/META-INF/resources/api-specifications/ccompat/v6/openapi.json

Ccompat openapi definition created using studio.

Add ccompat api v6 openapi definition

---

app/pom.xml
app/src/test/java/io/apicurio/registry/events/KafkaEventsProfile.java
app/src/test/java/io/apicurio/registry/events/KafkaEventsTest.java
app/src/test/java/io/apicurio/registry/events/KafkaEventsTestResource.java
utils/kafka/src/test/java/io/apicurio/registry/test/utils/KafkaTestContainerManager.java

The tests for kafka event sourcing were deleted!
This PR brings the test back

bring back kafka events tests!

---

.github/workflows/integration-tests.yaml
app/src/test/java/io/apicurio/registry/auth/SimpleAuthTest.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/AuthServerInfo.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/Constants.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryFacade.java
integration-tests/integration-tests-common/src/main/resources/test-realm.json
integration-tests/testsuite/pom.xml
integration-tests/testsuite/src/test/java/io/apicurio/tests/auth/SimpleAuthIT.java
pom.xml

This is the base for testing the auth features in kubernetes.
Kubernetes tests that use this java tests are not implemented yet, but still we are running this java tests in GH actions.

integration tests - auth

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/getting-started/assembly-installing-registry-openshift.adoc
docs/modules/ROOT/pages/getting-started/assembly-intro-to-the-registry.adoc
docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-api.adoc
docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-ui.adoc
docs/modules/ROOT/partials/getting-started/con-registry-artifacts.adoc
docs/modules/ROOT/partials/getting-started/con-registry-demo.adoc
docs/modules/ROOT/partials/getting-started/con-registry-distros.adoc
docs/modules/ROOT/partials/getting-started/con-registry-overview.adoc
docs/modules/ROOT/partials/getting-started/con-registry-rest-api.adoc
docs/modules/ROOT/partials/getting-started/con-registry-storage.adoc
docs/modules/ROOT/partials/getting-started/con-registry-web-console.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-liveness-readiness-probes.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-registry-ui.adoc
docs/modules/ROOT/partials/getting-started/proc-exporting-importing-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-kafka-streams-operatorhub.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-registry-operatorhub.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifact-versions-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifacts-using-rest-api.adoc
docs/modules/ROOT/partials/shared/attributes-links.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

@EricWittmann This one is ready to merge. Thanks!

clean up based on doc build testing

---

app/src/main/resources-unfiltered/META-INF/resources/api-specifications/registry/v2/openapi.json
common/src/main/java/io/apicurio/registry/rest/v2/GroupsResource.java
common/src/main/java/io/apicurio/registry/rest/v2/IdsResource.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/ArtifactMetaData.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/SearchedArtifact.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/VersionMetaData.java
common/src/main/resources/META-INF/openapi.json

As referenced here:  https://github.com/Apicurio/apicurio-registry/issues/1448
Our OAI description wasn't very good at defining when an operation consumed or produced binary file content.  Should be better now.

Improvements to the OpenAPI definition re: file content

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java
app/src/test/java/io/apicurio/registry/rest/v2/IdsResourceTest.java

Fixes #1501 
I added a bunch of logging, otherwise identifiying errors like this one in the future will be very difficult.
I also fixed one query that did not used tenantId

fix bug - incorrect query selectArtifactMetaDataByGlobalId

---

.github/scripts/test_apicurio_kubernetes.sh

Change required after this commit https://github.com/Apicurio/apicurio-registry-k8s-tests-e2e/commit/ebf7502918b978f72d89be0d4c2ce6b0d9bde4d7

update k8s tests invocation

---

app/src/test/java/io/apicurio/registry/mt/MultitenancyNoAuthTest.java
app/src/test/java/io/apicurio/registry/mt/MultitenancyNoAuthTestProfile.java
app/src/test/resources/io/apicurio/registry/mt/avro.json

test compat apis in mt tests

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java

fix to be added to next 2.X release

fix export query

---

build-deploy.sh

use commit to tag image in build-deploy script

---

distro/openshift-template/mt/apicurio-registry-mt-template.yaml

add service account parameter to ocp template

---

integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryFacade.java

This should fix integration tests

improve migration integration test, fix wait

---

schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/CombinedSchemaDiffVisitor.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/DiffContext.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/DiffUtil.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ArraySchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/BooleanSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/CombinedSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ConditionalSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ConstSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/EmptySchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/EnumSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/EqualitySchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/FalseSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/NotSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/NullSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/NumberSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ObjectSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/ReferenceSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/StringSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/TrueSchemaWrapper.java
schema-compatibility/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/wrapper/WrapUtil.java
schema-compatibility/json/src/test/resources/io/apicurio/registry/rules/compatibility/jsonschema/compatibility-test-data.json

Compatibility Issue #1551

---

integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/AvroSerdeIT.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractKafkaDeserializer.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/headers/HeadersHandler.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/strategy/ArtifactReference.java

if we can include this in 2.x branch it would be ideal

Fix for issue #1479 - magic byte detection

---

serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractKafkaDeserializer.java

please let tests run - to verify serdes tests pass - and merge and cherry pick to 2.x branch

fix serdes bug

---

ui/package.json
ui/src/app/pages/artifact/artifact.tsx
ui/src/app/pages/artifactVersion/artifactVersion.tsx
ui/src/app/pages/artifacts/artifacts.tsx
ui/src/app/pages/rules/rules.tsx
ui/webpack.common.js
ui/webpack.dev.js
ui/webpack.prod.js

Changes as required for running federated modules in host app.
1. Updated federatedModuleName as `sr`
2. Added `BrowserRouter` for fixing `Links` issue while running on host app.
3. Added `isProduction` flag and `[chunkhash:8]` to create unique files in prod. It will solve the caching issue.
4. Updated webpack.common.js,  webpack.dev.js and webpack.prod.js files
@EricWittmann Please verify that your `mt-ui` app should work with these changes.

fix: update webpack and add BrowserRouter

---

docs/modules/ROOT/assets/attachments/registry-rest-api.htm
docs/modules/ROOT/partials/getting-started/con-registry-migration.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-registry-kafka-storage.adoc
docs/modules/ROOT/partials/getting-started/proc-migrating-registry-applications.adoc
docs/modules/ROOT/partials/getting-started/proc-migrating-registry-data.adoc
docs/modules/ROOT/partials/shared/attributes-links.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

Adds attribute for release version in migration docs, and updates Operator docs version to fix broken links

Clean up release versioning 

---

distro/openshift-template/mt/apicurio-registry-mt-template.yaml

mt template - envoy rate limit

---

Makefile
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
build-deploy.sh
distro/openshift-template/mt/apicurio-registry-mt-template.yaml
integration-tests/integration-tests-common/pom.xml
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryFacade.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/multitenancy/MultitenantAuthIT.java
pr-check.sh
serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java

+ Skip UI build for multitenant build
+ Multitenant deployment template fixes for true Continuous Delivery
+ Add some more testing to multitenant deployment pr check build scripts
+ Removed some very verbose logging
In the future some changes similar to the pr check build scripts should be made for the build-deploy script, for now this is good as is

Multitenant deployment improvements

---

app/src/main/resources/application.properties
distro/openshift-template/mt/apicurio-registry-mt-template.yaml

mt template metrics

---

multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/metrics/MetricsConstants.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/metrics/RestMetricsResponseFilter.java

tenant manager - metrics requests count

---

rest-client/client-common/src/main/java/io/apicurio/registry/rest/client/exception/ContentNotFoundException.java
rest-client/client-common/src/main/java/io/apicurio/registry/rest/client/exception/ExceptionMapper.java
rest-client/client-common/src/main/java/io/apicurio/registry/rest/client/exception/GroupNotFoundException.java
rest-client/client-common/src/main/java/io/apicurio/registry/rest/client/exception/InvalidGroupIdException.java
rest-client/client-common/src/main/java/io/apicurio/registry/rest/client/exception/LogConfigurationNotFoundException.java
rest-client/client-common/src/main/java/io/apicurio/registry/rest/client/exception/MissingRequiredParameterException.java
rest-client/client-common/src/main/java/io/apicurio/registry/rest/client/exception/ParametersConflictException.java
rest-client/client-common/src/main/java/io/apicurio/registry/rest/client/exception/TenantManagerClientException.java

This PR adds all missing exceptions, that are propagated to REST layer, but client was not handling them properly.

Added missing exceptions from RESTAPI to rest-client

---

app/src/main/resources/application.properties
common/src/main/java/io/apicurio/registry/rest/v2/beans/ArtifactMetaData.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/SearchedArtifact.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/SearchedVersion.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/SystemInfo.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/VersionMetaData.java
multitenancy/tenant-manager-api/src/main/resources/application.properties
multitenancy/tenant-manager-datamodel/src/main/java/io/apicurio/multitenant/api/datamodel/RegistryTenant.java
multitenancy/tenant-manager-datamodel/src/main/java/io/apicurio/multitenant/api/datamodel/SystemInfo.java

this will fix the issue for @wtrocki 
but we need to update apicurio studio to generate this pattern or add the option to specify a custom one

fix returned date format

---

app/pom.xml
app/src/main/java/io/apicurio/registry/ccompat/dto/SchemaInfo.java
app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
app/src/test/java/io/apicurio/registry/ccompat/rest/ConfluentCompatApiTest.java

This pr adds schema validation to the ccompat layer at schema creation time by using the determine type feature.

Add schema validation ccompat

---

docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc

The latest version of Registry includes significant changes to how authentication and authorization work.  I have updated the documentation to reflect the latest configuration options.

Updated documentation for authn/z

---

Dockerfile.testing
Makefile
app/src/test/java/io/apicurio/registry/ImportLifecycleBeanTest.java
app/src/test/java/io/apicurio/registry/RegistryClientTest.java
app/src/test/java/io/apicurio/registry/limits/LimitsTest.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryFacade.java
pr-check.sh
pr_check_docker.sh
scripts/clean-postgres.sh
scripts/clean-postgres.sql
storage/sql/src/test/java/io/apicurio/registry/storage/util/PostgreSqlEmbeddedTestResource.java

Adds custom Dockerfile to run a postgresql instance while executing the tests

Fix mas ci

---

Makefile

This PR adds integration tests target into Makefile for local testing.

Integration tests into Makefile

---

.github/workflows/kubernetes-tests-manual.yaml
.github/workflows/kubernetes-tests.yaml

required after latest changes to e2e suite

fix k8x workflows

---

distro/openshift-template/mt/apicurio-registry-mt-template.yaml

mt template: add db ssl ca

---

ui/src/app/components/schemaMapping/emptyState.tsx
ui/src/app/components/schemaMapping/noMatchingSchema.tsx
ui/src/app/components/schemaMapping/permissionDenied.tsx
ui/src/app/components/schemaMapping/schemaCard.tsx
ui/src/app/components/schemaMapping/schemaMapping.tsx

Handle permission denied 403 for schema mapping for topics

Handle permission denied 403 for schema mapping for topics

---

integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/KafkaFacade.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/kafka/TrustAllSslEngineFactory.java
integration-tests/testsuite/src/main/java/io/apicurio/tests/serdes/TrustAllSslEngineFactory.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/serdes/apicurio/SerdesTester.java

workaround required for kubernetes tests

K8s tests shared kafka handle ssl

---

ui/src/app/pages/roles/components/modals/selectPrincipalAccount.tsx
ui/src/app/pages/roles/roles.tsx

This fixes:  https://github.com/EricWittmann/apicurio-registry/pull/new/fix/spyglass-icon

Update the role mapping (Access) filtering

---

ui/src/app/components/schemaMapping/matchingSchemaCard.tsx
ui/src/app/components/schemaMapping/schemaCard.css
ui/src/app/components/schemaMapping/schemaCard.tsx
ui/src/services/groups/groups.service.ts

UI changes for adding schema json in the topic schemas

---

app/src/test/java/io/apicurio/registry/serde/AvroSerdeTest.java
serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/strategy/QualifiedRecordIdStrategy.java

originally from https://github.com/Apicurio/apicurio-registry/pull/2012
Thank you @janvyhnanek and sorry I messed up with the commits in your original PR.

Serde qualified name strategy

---

app/src/main/java/io/apicurio/registry/ccompat/SchemaTypeFilter.java
app/src/main/java/io/apicurio/registry/ccompat/dto/Schema.java
app/src/main/java/io/apicurio/registry/ccompat/dto/SchemaInfo.java
app/src/main/java/io/apicurio/registry/ccompat/store/FacadeConverter.java
app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
app/src/main/java/io/apicurio/registry/util/ArtifactTypeUtil.java
app/src/test/java/io/apicurio/registry/ccompat/rest/ConfluentCompatApiTest.java

This PR addresses all the problems described in https://github.com/Apicurio/apicurio-registry/issues/1905.

Fix schema type

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java

Improvement for `nextSequenceValue` in h2 based storage.
We knew that method was not thread safe but for kafkasql that's not going to be executed concurrently, however for testing purposes the `mem` variant can be used concurrently.

inmemory storage, sequences mutex

---

integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/KafkaFacade.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryFacade.java
integration-tests/testsuite/src/main/java/io/apicurio/tests/utils/CustomTestsUtils.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/dbupgrade/KafkaSqlLogCompactionIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/dbupgrade/SqlStorageUpgradeIT.java

test for https://github.com/Apicurio/apicurio-registry/pull/2030

tests: kafkasql logcompaction test

---

integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryFacade.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/multitenancy/TenantReaperIT.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/api/TenantManagerExceptionMapper.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/api/TenantsResourceImpl.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/api/services/TenantStatusService.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/metrics/CustomMetricsConfiguration.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/metrics/MetricsConstants.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/metrics/UsageMetrics.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/storage/RegistryTenantStorage.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/storage/RegistryTenantStorageImpl.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/storage/TenantAlreadyExistsException.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/storage/dto/RegistryTenantDto.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/utils/Pair.java
multitenancy/tenant-manager-api/src/main/resources/application.properties
multitenancy/tenant-manager-api/src/main/resources/db/migration/h2/V2__tenants_modifiedOn.sql
multitenancy/tenant-manager-api/src/main/resources/db/migration/postgresql/V2__tenants_modifiedOn.sql
multitenancy/tenant-manager-api/src/test/java/io/apicurio/multitenant/RegistryTenantResourceTest.java
multitenancy/tenant-manager-api/src/test/java/io/apicurio/multitenant/TenantManagerClientTest.java

adds various metrics to tenant-manager for tracking the total number of tenants in each status and the time tenants spend in the TO_BE_DELETED status

tenant manager: tenants statuses metrics

---

app/src/main/java/io/apicurio/registry/metrics/MetricsConstants.java
app/src/main/java/io/apicurio/registry/metrics/RestMetricsResponseFilter.java
distro/openshift-template/mt/apicurio-perf-job.yaml

this made grafana dashboards to break

fix: remove too verbose metric tag

---

integration-tests/testsuite/src/main/java/io/apicurio/tests/LoadBalanceRegistryClient.java
integration-tests/testsuite/src/main/java/io/apicurio/tests/utils/RegistryWaitUtils.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ApicurioV2BaseIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/smokeTests/apicurio/AllArtifactTypesIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/smokeTests/apicurio/MetadataIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/smokeTests/apicurio/RulesResourceIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/smokeTests/confluent/SchemasConfluentIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/DeleteArtifactIT.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

this should fix all the remaining CI issues

fix: clustered tests improve wait

---

app/src/main/java/io/apicurio/registry/services/auth/BasicAuthClientCredentialsMechanism.java
app/src/main/java/io/apicurio/registry/services/auth/CustomAuthenticationMechanism.java

this improves this https://github.com/Apicurio/apicurio-registry/commit/1b5dd672d170ff4c9a8aecd597b779ae53f07e69 and adds it to a missing place

fix: improve OidcAuth client cleanup

---

ui/src/app/pages/roles/components/modals/selectPrincipalAccount.tsx

Sort Service Account based on the short description

Sort Service Account based on short description

---

.github/workflows/integration-tests.yaml
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/metrics/CustomMetricsConfiguration.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/metrics/UsageMetrics.java

tenant manager: fix usage histogram

---

ui/src/app/components/ruleList/compatibility-dropdown.tsx
ui/src/app/components/ruleList/validity-dropdown.tsx

fix for https://github.com/Apicurio/apicurio-registry/issues/626

ui: help text for rules

---

app/src/main/java/io/apicurio/registry/metrics/MetricsConstants.java
app/src/main/java/io/apicurio/registry/metrics/RestMetricsResponseFilter.java

adds missing metric to easily calculate requests per second

feat: add missing metric for total requests counter

---

ui/src/app/pages/roles/components/modals/grantAccessModal.tsx
ui/src/app/pages/roles/components/modals/selectPrincipalAccount.tsx
ui/src/app/pages/roles/roles.tsx

https://issues.redhat.com/browse/MGDSTRM-6396
Create role mapping:
Edit role mapping:

Enhance role mapping modal based on new design

---

serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroKafkaSerializer.java
serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaSerializer.java
serdes/protobuf-serde/src/main/java/io/apicurio/registry/serde/protobuf/ProtobufKafkaSerializer.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractKafkaSerializer.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/AbstractSchemaResolver.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/strategy/ArtifactResolverStrategy.java

Reverts Apicurio/apicurio-registry#2170 because this changes are not actually needed

Revert "feat: serdes getSchemaFromData add headers"

---

app/src/main/java/io/apicurio/registry/content/AbstractContentHandle.java
app/src/main/java/io/apicurio/registry/content/ContentHandle.java
app/src/main/java/io/apicurio/registry/content/canon/XmlContentCanonicalizer.java
pom.xml

Dependency updates 2.0.x

---

.github/workflows/integration-tests.yaml
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/Constants.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/KafkaFacade.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/RegistryFacade.java
integration-tests/integration-tests-common/src/main/java/io/apicurio/tests/common/utils/RegistryUtils.java
integration-tests/testsuite/pom.xml
integration-tests/testsuite/src/main/java/io/apicurio/tests/utils/CustomTestsUtils.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ApicurioV2BaseIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/dbupgrade/KafkaSqlLogCompactionIT.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/ContentIdKey.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/keys/GlobalIdKey.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/values/ActionType.java

@famartinrh I tried to cherry-pick the tests in `5803ed1dbf80c873daa09b2ec25022256490a81b` as well, but I'm having issues working out the conflicts. Do we want to include it?

Pick fix for issue #1873 - Kafka log compaction

---

ui/src/app/components/baseComponent.ts
ui/src/app/components/modals/invalidContentModal.css
ui/src/app/components/modals/invalidContentModal.tsx
ui/src/app/pages/artifactVersion/artifactVersion.tsx
ui/src/app/pages/artifactVersion/components/modals/editMetaDataModal.tsx
ui/src/app/pages/artifactVersion/components/tabs/info.css
ui/src/app/pages/artifactVersion/components/tabs/info.tsx
ui/src/app/pages/artifacts/artifacts.tsx
ui/src/models/apiError.model.ts
ui/src/services/admin/admin.service.ts

the idea is to make the custom rules PR smaller https://github.com/Apicurio/apicurio-registry/pull/2159
in this PR I extracted the part for listing the validation errors in a modal, this is useful regardless of custom rules...
also in this PR I address https://github.com/Apicurio/apicurio-registry/issues/2231

ui: list validation errors in modal, plus minor fixes

---

app/src/test/java/io/apicurio/registry/compatibility/CompatibilityRuleApplicationTest.java
app/src/test/java/io/apicurio/registry/validity/ValidityRuleApplicationTest.java
schema-util/avro/src/main/java/io/apicurio/registry/rules/compatibility/AvroCompatibilityChecker.java

This is in the Avro compatibility checker. Fixes https://issues.redhat.com/browse/MGDSR-142

Handle AvroTypeException in addition to ParseException

---

README.md
app/pom.xml
app/src/main/java/io/apicurio/registry/faulttolerance/FaultToleranceConstants.java
app/src/main/java/io/apicurio/registry/mt/TenantMetadataService.java
app/src/main/java/io/apicurio/registry/mt/TenantNotFoundException.java
app/src/main/java/io/apicurio/registry/services/auth/CustomAuthenticationMechanism.java
app/src/main/java/io/apicurio/registry/services/http/RegistryExceptionMapperService.java
app/src/test/java/io/apicurio/registry/mt/MultitenancyNoAuthTest.java
client/src/main/java/io/apicurio/registry/rest/client/impl/ErrorHandler.java

Any ideas where else to add timeouts or retries?

Improve reliability when communicating with external systems

---

app/src/main/java/io/apicurio/registry/services/http/RegistryExceptionMapperService.java

Always log 500 errors, no matter what.

---

ui/src/app/components/ruleList/compatibility-dropdown.tsx
ui/src/app/components/ruleList/validity-dropdown.tsx

Added "None" enums for validity and compatibility rules in the UI

---

docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
docs/modules/ROOT/partials/getting-started/con-registry-artifacts.adoc
docs/modules/ROOT/partials/getting-started/con-registry-demo.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-browsing-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-rules-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-creating-access-token-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-exporting-importing-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifacts-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc

Clean up typos and formatting found in downstream testing

Clean up typos and formatting

---

docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
docs/modules/ROOT/partials/getting-started/con-registry-artifacts.adoc
docs/modules/ROOT/partials/getting-started/con-registry-demo.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-browsing-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-rules-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-creating-access-token-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-exporting-importing-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifacts-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc

Previously committed to v2.1.x and now cherry picked to master

clean up formatting and typos found in downstream testing

---

docs/modules/ROOT/pages/getting-started/assembly-installing-registry-storage-openshift.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-kafka-oauth.adoc

Already reviewed by Carles for 2.0.x in https://github.com/Apicurio/apicurio-registry/pull/2210
Couldn't cherry pick due to new context ID format in 2.1.x.

docs: add kafka oauth config settings (already added to 2.0.x)

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/CommonSqlStatements.java

Also changed the SQL query in question to sort by DESC instead of ASC to achieve the same result with less effort.

Changed SQL storage query from findLast to findFirst

---

docs/modules/ROOT/partials/getting-started/proc-exporting-importing-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-exporting-importing-using-web-console.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-rule-maturity-matrix.adoc

Adds technical review feedback from Eric and doc peer review from Breda.

docs: add review feedback on export/import

---

app/pom.xml
app/src/main/resources/application-dev.properties
app/src/main/resources/application-prod.properties
app/src/main/resources/application-test.properties
app/src/main/resources/application.properties
storage/kafkasql/pom.xml
storage/sql/pom.xml

This is a proposal to extract the application properties to different files per profile. This should simplify our lives going forward whenever we need to add new properties from Quarkus itself or new features requiring properties to the application.

[Proposal] Split application properties into different files per profile

---

.github/workflows/integration-tests.yaml
.github/workflows/kubernetes-tests.yaml
.github/workflows/lint.yaml
.github/workflows/verify.yaml

don't run jobs when a workflow config is changed

---

app/src/test/java/io/apicurio/registry/noprofile/ArtifactTypeTest.java
schema-util/protobuf/src/main/java/io/apicurio/registry/rules/compatibility/ProtobufCompatibilityChecker.java
schema-util/protobuf/src/main/java/io/apicurio/registry/rules/compatibility/protobuf/ProtobufCompatibilityCheckerLibrary.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufFile.java

by implementing forward and full compatibility checkings.

Improve protobuf compatibility checking

---

app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/IdsResourceImpl.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlUtil.java
app/src/main/java/io/apicurio/registry/util/ArtifactTypeUtil.java
common/src/main/java/io/apicurio/registry/rest/v2/GroupsResource.java
common/src/main/java/io/apicurio/registry/rest/v2/IdsResource.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/ArtifactMetaData.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/ArtifactReference.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/ConfigurationProperty.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/ContentCreateRequest.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/Limits.java
common/src/main/java/io/apicurio/registry/rest/v2/beans/SearchedVersion.java
common/src/main/resources/META-INF/openapi.json

The Apicurio tool was used to generate an API project from an OpenAPI definition.  Please review this pull request, modify as necessary, and merge!

Regenerated JAX-RS interfaces after upgrading codegen

---

docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-concepts.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-strategy.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-producer.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc

Adds customer feedback on serdes docs and minor clean up to 2.2.x branch (already added to master)

docs: add feedback on serdes docs

---

utils/protobuf-schema-utilities/src/main/proto/additionalTypes/decimal.proto
utils/protobuf-schema-utilities/src/test/proto/additionalTypes/decimal.proto

Fix typo in the comments

---

utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
utils/protobuf-schema-utilities/src/test/proto/TestSyntax2CustomOptions.proto
utils/protobuf-schema-utilities/src/test/proto/TestSyntax3CustomOptions.proto

Fix bug in metadata parsing in Protobuf oneof field including synthetic oneof

Fix bug in metadata parsing in Protobuf oneof field including synthetic oneof

---

ui/src/app/pages/artifactVersion/artifactVersion.tsx
ui/src/app/pages/artifactVersion/components/modals/editMetaDataModal.tsx
ui/src/app/pages/artifactVersion/components/tabs/info.tsx

* "Info" tab to "Overview" tab
* "Version Metadata" to "Version metadata"
* "Content Rules" to "Content rules"
* "Edit metadata" to "Edit"
* "Edit artifact metadata" to "Edit version metadata"

Change text of titles on Artifact page

---

system-tests/src/main/java/io/apicurio/registry/systemtests/client/ApicurioRegistryApiClient.java

Need to set Bearer access token in API client when Keycloak is used for authentication.

Update(API client): Add option for Bearer access token

---

distro/openshift-template/mt/apicurio-registry-mt-template.yaml
multitenancy/tenant-manager-api/pom.xml
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/TenantReaper.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/storage/RegistryTenantStorage.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/storage/RegistryTenantStorageImpl.java
multitenancy/tenant-manager-api/src/main/java/io/apicurio/multitenant/storage/dto/RegistryTenantDto.java
multitenancy/tenant-manager-api/src/main/resources/application.properties

This is an attempt to fix the database issues in staging, hardening the tenant reaper execution, or at least provide more logging to determine the cause.

Refactor tenant manager reaper, more logging

---

docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-creating-access-token-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-exporting-importing-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifact-references-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifact-versions-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifacts-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-client.adoc

- Updated order of steps for adding artifact props
- Improved steps for creating artifacts using REST API based on SSO testing

Docs: add review feedback on artifact props and SSO testing

---

ui/webpack.dev.js

From: https://stackoverflow.com/a/45755064
Tested locally.

Fix UI dev server to display the content even in presence of warnings

---

ui/src/app/pages/artifactVersion/components/tabs/content.css
ui/src/app/pages/artifactVersion/components/tabs/content.tsx

Resolves the initial discussion on #474 , should we open a separate ticket for the Download options?

Option to display JSON data as YAML in UI

---

ui/src/app/app.css
ui/src/app/components/header/pageheader.tsx
ui/src/app/components/ruleList/ruleList.css
ui/src/app/components/ruleList/ruleList.tsx
ui/src/app/pages/artifactVersion/components/modals/editMetaDataModal.tsx
ui/src/app/pages/artifactVersion/components/modals/propertiesFormGroup.tsx
ui/src/app/pages/artifactVersion/components/tabs/info.css
ui/src/app/pages/artifactVersion/components/tabs/info.tsx
ui/src/app/pages/settings/components/configProperty.css
ui/src/app/pages/settings/components/configProperty.tsx
ui/src/app/pages/settings/settings.css
ui/src/app/pages/settings/settings.tsx
ui/tslint.json

Updated the Settings page and Artifact Properties modal

---

.github/scripts/install-tools.sh
.github/workflows/lint.yaml
.gitignore
scripts/validate-generated-code.sh

Opening in Draft as it depends on:
https://github.com/Apicurio/apicurio-codegen/pull/37
This PR checks that the generated code and the OpenApi spec are kept in sync using the codegen CLI in CI.

Infrastructure to validate the generated code for the api v2

---

app/pom.xml
app/src/main/java/io/apicurio/registry/rest/RestConfig.java
app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
app/src/main/java/io/apicurio/registry/util/ArtifactTypeUtil.java
app/src/main/java/io/apicurio/registry/util/ContentTypeUtil.java
app/src/main/resources/application.properties
app/src/test/java/io/apicurio/registry/ibmcompat/SchemaRegistryRestAPIClient.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
app/src/test/java/io/apicurio/registry/noprofile/serde/ProtobufSerdeTest.java
app/src/test/java/io/apicurio/registry/rbac/RegistryClientTest.java
client/src/main/java/io/apicurio/registry/rest/client/RegistryClient.java
client/src/main/java/io/apicurio/registry/rest/client/impl/RegistryClientImpl.java
client/src/main/java/io/apicurio/registry/rest/client/request/Parameters.java
common/src/main/java/io/apicurio/registry/rest/Headers.java
common/src/main/java/io/apicurio/registry/rest/v2/GroupsResource.java
common/src/main/java/io/apicurio/registry/utils/JAXRSClientUtil.java
common/src/main/resources/META-INF/openapi.json
integration-tests/testsuite/src/main/java/io/apicurio/tests/LoadBalanceRegistryClient.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/RegistryUITester.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/UploadArtifactsIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/ui/pages/UploadArtifactDialog.java
pom.xml
schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
ui/src/app/pages/artifacts/components/uploadForm/uploadForm.tsx
ui/src/services/groups/groups.service.ts
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java

Opening it as a draft to check if I'm following the guidelines of this repo ...
Resolves #1499
Question:
- should we extend this support to other endpoints? e.g. `updateArtifact` `createArtifactVersion`

Create artifacts from URL

---

.github/apicurio-bot.yaml

@EricWittmann @carlesarnal Take a look please, and add what you think may be missing (at least from the start), so we can start using the bot. Let me know what needs to improve, I've already added a few TODOs and I'll update the bot before we merge this.

Draft: Add config file for the Apicurio bot

---

docs/modules/ROOT/pages/getting-started/assembly-configuring-kafka-client-serdes.adoc
docs/modules/ROOT/pages/getting-started/assembly-configuring-the-registry.adoc
docs/modules/ROOT/pages/getting-started/assembly-installing-registry-docker.adoc
docs/modules/ROOT/pages/getting-started/assembly-installing-registry-openshift.adoc
docs/modules/ROOT/pages/getting-started/assembly-installing-registry-storage-openshift.adoc
docs/modules/ROOT/pages/getting-started/assembly-intro-to-registry-rules.adoc
docs/modules/ROOT/pages/getting-started/assembly-intro-to-the-registry.adoc
docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-api.adoc
docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-maven.adoc
docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-ui.adoc
docs/modules/ROOT/pages/getting-started/assembly-migrating-registry-v1-v2.adoc
docs/modules/ROOT/pages/getting-started/assembly-registry-reference.adoc
docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
docs/modules/ROOT/pages/getting-started/assembly-using-the-registry-client.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-browsing-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-exporting-importing-using-web-console.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

- Clean up context IDs for downstream builds 
- Update component versions 
- Minor copy edits

docs: clean up context IDs and versions 

---

app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java

fix: check if ContentCreateRequest has content field

---

docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-ui.adoc
docs/modules/ROOT/partials/getting-started/con-registry-distros.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-browsing-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-changing-artifact-owner-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-liveness-readiness-probes.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-kafka-streams-operatorhub.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-registry-operatorhub.adoc
docs/modules/ROOT/partials/getting-started/proc-setting-up-kafka-streams-storage.adoc
docs/modules/ROOT/partials/getting-started/proc-setting-up-postgresql-storage.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-liveness-env-vars.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

- Add new module on changing artifact owner (only available when authn enabled)
- AsyncAPI artifact type now has Documentation tab 
- Clean up attributes for branding

docs: changing artifact owner

---

app/src/main/java/io/apicurio/registry/auth/AuthConfig.java

This fixes https://github.com/Apicurio/apicurio-registry/issues/2743

Authenticated read access depends on rbac being enabled too

---

app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java

Attempt to fix the CI failure from #2765

Close the client after downloading the artifact content

---

.github/workflows/verify.yaml
system-tests/pom.xml
system-tests/src/main/java/io/apicurio/registry/systemtests/framework/ApicurioRegistryUtils.java
system-tests/src/main/java/io/apicurio/registry/systemtests/framework/KeycloakUtils.java
system-tests/src/main/java/io/apicurio/registry/systemtests/platform/Kubernetes.java
system-tests/src/main/java/io/apicurio/registry/systemtests/registryinfra/resources/ApicurioRegistryResourceType.java
system-tests/src/test/java/io/apicurio/registry/systemtests/APITests.java
system-tests/src/test/java/io/apicurio/registry/systemtests/OLMTests.java
system-tests/src/test/java/io/apicurio/registry/systemtests/OLMUpgradeTests.java
system-tests/src/test/java/io/apicurio/registry/systemtests/TestBase.java

Demo PR to show-case https://github.com/Apicurio/apicurio-registry-operator/pull/187

Use the generated models from the operator

---

app/src/main/java/io/apicurio/registry/events/EventSourcedRegistryStorage.java
common/src/main/java/io/apicurio/registry/events/dto/ArtifactId.java

Added the artifact type to events fired by the registry event source

---

client/src/main/java/io/apicurio/registry/rest/client/RegistryClient.java
client/src/main/java/io/apicurio/registry/rest/client/impl/RegistryClientImpl.java
client/src/main/java/io/apicurio/registry/rest/client/request/provider/GroupRequestsProvider.java
integration-tests/testsuite/src/main/java/io/apicurio/tests/LoadBalanceRegistryClient.java

This PR adds method to send UpdateArtifact request and include references.
Also in create artifact with references request it makes no sense to have any other content type than application/create.extended+json.

feat(registry-client): added option to update artifact with references

---

docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-browsing-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-changing-artifact-owner-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-registry-security.adoc

- Import artifact from URL
- Format content as JSON or YAML
- Clean up

docs: add new ui enhancements

---

.github/workflows/integration-tests.yaml
.github/workflows/kubernetes-tests-manual.yaml
.github/workflows/kubernetes-tests.yaml
.github/workflows/lint.yaml
.github/workflows/maven-snapshot-release.yaml
.github/workflows/publish-debug-image.yaml
.github/workflows/registry-rhbq-build.yaml
.github/workflows/release-images.yaml
.github/workflows/release.yaml
.github/workflows/tag-registry-examples.yaml
.github/workflows/tool-exportV1-release.yaml
.github/workflows/update-openapi.yaml
.github/workflows/update-website.yaml
.github/workflows/verify.yaml

Related to:
https://github.com/Apicurio/apicurio-tasks/issues/195

Review GH action versions

---

docs/modules/ROOT/partials/getting-started/con-registry-distros.adoc
docs/modules/ROOT/partials/getting-started/con-registry-storage.adoc
docs/modules/ROOT/partials/getting-started/proc-changing-artifact-owner-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-registry-operatorhub.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

Clean up: 
- storage options and versions
- upgrade channels

docs: clean up storage and upgrade versions

---

schema-util/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/diff/ObjectSchemaDiffVisitor.java
schema-util/json/src/test/resources/io/apicurio/registry/rules/compatibility/jsonschema/compatibility-test-data.json

Motivation: https://github.com/Apicurio/apicurio-registry/issues/2835

Json backward compatability fix for type keyword

---

distro/openshift-template/mt/apicurio-registry-mt-template.yaml

Ref:
https://github.com/Apicurio/apicurio-tenant-manager/pull/64

Clean the OpenShift template from Tenant Manager

---

app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
app/src/test/java/io/apicurio/registry/ccompat/rest/SubjectVersionStringTest.java

Fixes: https://github.com/Apicurio/apicurio-registry/issues/2851

fix: comply with undocumented behavior in ccompat when parsing versions

---

docs/modules/ROOT/partials/getting-started/con-kafka-connect-converters.adoc
docs/modules/ROOT/partials/getting-started/con-registry-distros.adoc
docs/modules/ROOT/partials/getting-started/con-registry-rest-api.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-constants.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-liveness-readiness-probes.adoc
docs/modules/ROOT/partials/getting-started/proc-creating-access-token-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-downloading-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-kafka-streams-operatorhub.adoc
docs/modules/ROOT/partials/getting-started/proc-installing-registry-operatorhub.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-consumer.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-producer.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-config-stream.adoc
docs/modules/ROOT/partials/getting-started/proc-registry-serdes-register.adoc
docs/modules/ROOT/partials/getting-started/proc-setting-up-kafka-streams-storage.adoc
docs/modules/ROOT/partials/getting-started/proc-setting-up-postgresql-storage.adoc
docs/modules/ROOT/partials/getting-started/proc-testing-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/shared/attributes-links.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

Minor cleanup from downstream testing (format and branding)

docs: cleanup from downstream testing

---

.github/workflows/new-system-tests.yaml
new-system-tests/README.md
new-system-tests/pom.xml
new-system-tests/src/test/java/io/apicurio/registry/systemtests/example/ExampleIT.java
new-system-tests/src/test/resources/kubernetes/example.yaml
pom.xml

This is an attempt to re-start a clean module, properly checked in CI that can be evolved and maintained with the required `system-tests`.
If we agree to merge this PR I would expect to review follow-up PRs porting one after the other the legacy tests to this new infrastructure so that we can, eventually, delete the current `system-tests` at all.
This approach enables, IMHO, good development practices such as:
- small and self-contained PRs
- consistency checked in CI
- effective code reviews
cc. @rkubis @obabec

[proposal] System tests revamp

---

.github/workflows/integration-tests.yaml

This is a first step to simplify and, possibly, speed up the IT pipeline.

Simplify the IT CI using dependent steps

---

schema-util/protobuf/src/main/java/io/apicurio/registry/rules/compatibility/protobuf/ProtobufCompatibilityCheckerLibrary.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufFile.java

Fix NPE in Protobuf compatibility checking

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStorageEvent.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/SqlStorageEventType.java
storage/kafkasql/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlRegistryStorage.java

Fix for https://github.com/Apicurio/apicurio-registry/issues/2991

Ensure the kafka consumer thread starts *after* the SQL db is initialized

---

new-system-tests/pom.xml
new-system-tests/src/test/java/io/apicurio/registry/systemtests/Utils.java

* Wait for existence of Deployment
* Check if Kafka is in Ready state
* Wait for Kafka to be in Ready state

New(Utils): Functions for work with Deployment and Kafka resources

---

docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc
schema-resolver/pom.xml
schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
schema-resolver/src/test/java/io/apicurio/registry/resolver/config/ConfigurationTest.java

Resolves #2997 
Contains a few TODO comments I could use some feedback on.

fix: check that the schema resolver config matches documentation

---

new-system-tests/src/main/java/io/apicurio/registry/systemtests/Constants.java
new-system-tests/src/test/java/io/apicurio/registry/systemtests/KafkasqlNoAuthNoIAM.java
new-system-tests/src/test/resources/apicurio/02_registry_kafkasql_no_auth_no_iam.yaml
new-system-tests/src/test/resources/kafkasql/01_subscription.yaml
new-system-tests/src/test/resources/kafkasql/02_no_auth.yaml

New(tests): Deploy of Registry with KafkaSQL storage and without IAM

---

new-system-tests/src/test/java/io/apicurio/registry/systemtests/KafkasqlNoAuthKeycloak.java
new-system-tests/src/test/resources/apicurio/02_registry_kafkasql_no_auth_keycloak.yaml

New(tests): Deploy of Registry with KafkaSQL storage and Keycloak IAM

---

new-system-tests/pom.xml

Using brand new functionalities 🙂

Simplify Java Gen Maven plugin workflow

---

pom.xml

Reverts Apicurio/apicurio-registry#3050
This should not have been merged.

Revert "build(deps): bump confluent.version from 7.3.0 to 7.3.1"

---

app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
app/src/test/java/io/apicurio/registry/noprofile/compatibility/CompatibilityRuleApplicationTest.java
integration-tests/legacy-tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
integration-tests/testsuite/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java
schema-util/avro/pom.xml
schema-util/avro/src/main/java/io/apicurio/registry/rules/compatibility/AvroCompatibilityChecker.java
schema-util/avro/src/test/java/io/apicurio/registry/rules/compatibility/avro/AvroSchemaSmokeTest.java
schema-util/avro/src/test/resources/io/apicurio/registry/rules/compatibility/avro/compatibility-test-data.json
schema-util/common/pom.xml
schema-util/common/src/main/java/io/apicurio/registry/rules/compatibility/AbstractCompatibilityChecker.java
schema-util/common/src/main/java/io/apicurio/registry/rules/compatibility/CompatibilityExecutionResult.java
schema-util/common/src/main/java/io/apicurio/registry/rules/compatibility/SimpleCompatibilityDifference.java
schema-util/common/src/test/java/io/apicurio/registry/rules/compatibility/CompatibilityTestExecutor.java
schema-util/json/pom.xml
schema-util/json/src/main/java/io/apicurio/registry/rules/compatibility/JsonSchemaCompatibilityChecker.java
schema-util/json/src/test/resources/io/apicurio/registry/rules/compatibility/jsonschema/compatibility-test-data.json

Improve Avro compatibility testing 

---

Dockerfile.jvm.staged
devfile.yaml

Add the required files for using Stonesoup.

Onboarding to Stonesoup

---

app/src/test/java/io/apicurio/registry/noprofile/rest/v1/ArtifactsResourceTest.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v1/TestResourceTest.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
schema-util/common/src/main/java/io/apicurio/registry/rules/RuleViolationException.java
schema-util/json/src/main/java/io/apicurio/registry/rules/compatibility/jsonschema/JsonUtil.java
schema-util/util-provider/src/test/java/io/apicurio/registry/rules/validity/JsonSchemaContentValidatorTest.java

fix: prevent JSON schema library from attempting to retrieve referenced schemas. Fixes #3086

---

docs/local-test-playbook.yml
docs/modules/ROOT/pages/getting-started/assembly-configuring-kafka-client-serdes.adoc
docs/modules/ROOT/pages/getting-started/assembly-intro-to-registry-rules.adoc
docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-maven.adoc
docs/modules/ROOT/pages/getting-started/assembly-registry-reference.adoc
docs/modules/ROOT/pages/getting-started/assembly-using-kafka-client-serdes.adoc
docs/modules/ROOT/partials/getting-started/con-kafka-connect-converters.adoc
docs/modules/ROOT/partials/getting-started/con-registry-artifacts.adoc
docs/modules/ROOT/partials/getting-started/con-registry-client.adoc
docs/modules/ROOT/partials/getting-started/con-registry-content.adoc
docs/modules/ROOT/partials/getting-started/con-registry-demo.adoc
docs/modules/ROOT/partials/getting-started/con-registry-overview.adoc
docs/modules/ROOT/partials/getting-started/con-registry-rules.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serde.adoc
docs/modules/ROOT/partials/getting-started/con-registry-serdes-concepts.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-downloading-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-exporting-importing-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifact-references-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifact-versions-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-managing-artifacts-using-rest-api.adoc
docs/modules/ROOT/partials/getting-started/proc-testing-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-writing-registry-client.adoc
docs/modules/ROOT/partials/getting-started/ref-registry-client.adoc

Includes review feedback on:
- Intro material
- Java client
- Maven plug-in
- Clean up

docs: technical review feedback 

---

docs/modules/ROOT/partials/getting-started/con-registry-artifacts.adoc
docs/modules/ROOT/partials/getting-started/con-registry-migration.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-browsing-artifacts-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-configuring-rules-using-console.adoc
docs/modules/ROOT/partials/getting-started/proc-migrating-registry-applications.adoc
docs/modules/ROOT/partials/getting-started/proc-migrating-registry-data.adoc
docs/modules/ROOT/partials/getting-started/proc-writing-registry-client.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

- Clarify that artifact versions are no longer immutable. 
- Clean up versions, minor copy edits

docs: artifact versions are now deletable using api, clean up

---

app/src/main/java/io/apicurio/registry/ui/config/UiConfigProperties.java
docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc
ui/config/config-keycloakjs-rbac.js
ui/config/config-keycloakjs.js
ui/config/config-none.js
ui/config/config-oidcjs.js
ui/package-lock.json
ui/package.json
ui/src/app/pages/artifactVersion/components/modals/generateClientModal.css
ui/src/app/pages/artifactVersion/components/modals/generateClientModal.tsx
ui/src/app/pages/artifactVersion/components/tabs/info.css
ui/src/app/pages/artifactVersion/components/tabs/info.tsx
ui/src/services/config/config.service.ts
ui/src/services/downloader/downloader.service.ts
ui/webpack.common.js

Rebased version of this:  https://github.com/Apicurio/apicurio-registry/pull/3325

Implemented most of the UX design for Client SDK Gen

---

app/src/main/java/io/apicurio/registry/ccompat/store/RegistryStorageFacadeImpl.java
app/src/main/java/io/apicurio/registry/cncf/schemaregistry/impl/SchemagroupsResourceImpl.java
app/src/main/java/io/apicurio/registry/ibmcompat/api/impl/ApiServiceImpl.java
app/src/main/java/io/apicurio/registry/rest/v1/ArtifactsResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
app/src/main/java/io/apicurio/registry/rules/RuleContext.java
app/src/main/java/io/apicurio/registry/rules/RuleExecutorFactory.java
app/src/main/java/io/apicurio/registry/rules/RulesService.java
app/src/main/java/io/apicurio/registry/rules/RulesServiceImpl.java
app/src/main/java/io/apicurio/registry/rules/integrity/IntegrityRuleExecutor.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
app/src/test/java/io/apicurio/registry/noprofile/compatibility/CompatibilityRuleApplicationTest.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v1/RulesResourceTest.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
app/src/test/java/io/apicurio/registry/rbac/AdminResourceTest.java
common/src/main/resources/META-INF/openapi.json
schema-util/common/src/main/java/io/apicurio/registry/rules/RuleViolation.java
schema-util/common/src/main/java/io/apicurio/registry/rules/integrity/IntegrityLevel.java
ui/src/app/components/ruleList/index.ts
ui/src/app/components/ruleList/integrity-dropdown.tsx
ui/src/app/components/ruleList/ruleList.tsx
ui/src/app/pages/artifactVersion/components/tabs/info.tsx

Added a new artifact reference integrity rule.  Logic, testing, and UI all implemented.

Implemented a basic artifact reference integrity rule.

---

distro/docker/src/main/docker/Dockerfile.jvm
distro/docker/src/main/docker/Dockerfile.kafkasql.jvm
distro/docker/src/main/docker/Dockerfile.mssql.jvm
distro/docker/src/main/docker/Dockerfile.native
distro/docker/src/main/docker/Dockerfile.sql.jvm

feat: do not run images under root UID/GID

---

docs/modules/ROOT/partials/getting-started/ref-registry-security-configuration.adoc

Addresses https://issues.redhat.com/browse/IPT-947
**Note**: This PR should also be cherry picked to `2.4.x` branch.

docs: add section on HTTP basic client credentials token expiry

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-maven.adoc
docs/modules/ROOT/pages/getting-started/assembly-managing-registry-artifacts-ui.adoc
docs/modules/ROOT/pages/getting-started/assembly-using-the-registry-client.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-automatically-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifact-references-manually-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-adding-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-downloading-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/getting-started/proc-migrating-registry-applications.adoc
docs/modules/ROOT/partials/getting-started/proc-testing-artifacts-using-maven-plugin.adoc
docs/modules/ROOT/partials/shared/attributes-links.adoc
docs/modules/ROOT/partials/shared/attributes.adoc

- Add new doc on auto-detect and register artifact refs using maven plugin
- Rewrite existing maven plugin artifact refs doc as manual registration use case
- Clean up
Documents https://github.com/Apicurio/apicurio-registry/pull/3351
**Note**: This PR should also be cherry picked to `2.4.x` branch.

docs: add auto-detect and register artifact refs using maven plugin

---

ui/package-lock.json
ui/package.json

Reverts Apicurio/apicurio-registry#3564

Revert "build(deps): bump tough-cookie and ts-jest in /ui"

---

python-sdk/Makefile

Fix publishing of the Python SDK

---

app/src/main/java/io/apicurio/registry/rest/v2/AdminResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
app/src/test/java/io/apicurio/registry/rbac/AdminResourceTest.java

Hi @EricWittmann , 
I have made the changes suggested by you in my PR #3491. Please review the changes and let me know if this change is as expected. As mentioned by @carlesarnal I will add test cases for the same if the changes are correct.
Closes #3474

Add Exception for empty rule

---

pom.xml
storage/gitops/pom.xml
storage/kafkasql/pom.xml
storage/mssql/pom.xml
storage/sql/pom.xml

This is the first step for the application modularization. This makes depending on the app module much easier for those not familiar with the project structure.

Remove black magic for building storages classpath

---

ui/src/app/pages/settings/settings.tsx

Fixes https://github.com/Apicurio/apicurio-registry/issues/3775

Fixed a regression in the Settings page search box

---

app/src/main/java/io/apicurio/registry/rest/v2/AdminResourceImpl.java
app/src/test/java/io/apicurio/registry/rbac/AdminResourceTest.java

Hi @andreaTP and @EricWittmann,
This PR closes #3776 .
I have added the missing null checks on role mapping. Could you please review the changes?
If the changes are correct, I'll proceed with implementing the test cases.
Thank you

Add null checks on  role mapping

---

app/src/test/java/io/apicurio/registry/noprofile/maven/RegisterRegistryMojoTest.java
app/src/test/java/io/apicurio/registry/noprofile/maven/RegistryMojoTestBase.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java

Add option to skip the register goal

---

common/pom.xml
operator/model/pom.xml
storage/mssql/pom.xml
storage/sql/pom.xml
ui/pom.xml

Make apicurio-registry work properly with Visual Studio Code

---

app/src/test/java/io/apicurio/registry/AbstractRegistryTestBase.java
app/src/test/java/io/apicurio/registry/AbstractResourceTestBase.java
app/src/test/java/io/apicurio/registry/auth/AuthTestAnonymousCredentials.java
app/src/test/java/io/apicurio/registry/limits/LimitsTest.java
app/src/test/java/io/apicurio/registry/noprofile/compatibility/CompatibilityRuleApplicationTest.java
app/src/test/java/io/apicurio/registry/rbac/AdminClientTest.java
app/src/test/java/io/apicurio/registry/rbac/RegistryClientTest.java
client/pom.xml
integration-tests/src/test/java/io/apicurio/tests/ApicurioRegistryBaseIT.java
integration-tests/src/test/java/io/apicurio/tests/smokeTests/apicurio/ArtifactsIT.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/ERCache.java
utils/tests/src/main/java/io/apicurio/registry/utils/tests/TestUtils.java

In draft to test out:
https://github.com/redhat-developer/kiota-java-extra/pull/39

Bump Kiota Maven plugin

---

Makefile
app/src/main/java/io/apicurio/registry/rest/v2/AdminResourceImpl.java
app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
app/src/main/java/io/apicurio/registry/storage/ArtifactStateExt.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v2/GroupsResourceTest.java
app/src/test/java/io/apicurio/registry/rbac/AdminResourceTest.java
integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
storage/mysql/pom.xml
ui/src/app/pages/settings/settings.tsx
utils/converter/src/main/java/io/apicurio/registry/utils/converter/ConnectEnum.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/ConnectUnion.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroData.java
utils/converter/src/test/java/io/apicurio/registry/utils/converter/avro/AvroDataTest.java

* Add null checks on  role mapping (#3800)
* Add null checks on  role mapping
* Add check for Role and Unit Test
* Fixed a regression in the Settings page search box (#3798)
* modified state change checks in ArtifactStateExt and AbstractSqlRegistryStorage (#3637)
* Incorrect default value avro serialization (#3633)
* Fix default value converter
* Add test for default byte type value in converter test
* Correct comment
* added unit tests (#3593)
* Bugfix: prase decimal's default
---------

Backport fixes (#3966)

---

integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/ExtJsonConverter.java

This is a backport of the original fix.

Handle situations with complex schemas in json converter (#4144)

---

app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaParser.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaResolverConfig.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/config/DefaultSchemaResolverConfig.java
serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaSerializer.java
serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaKafkaSerializerConfig.java
serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchemaParser.java
serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java

This is a port of the original fix to the 2.5.x branch.

Add support for autoregister schemas in the json serde (#4127)

---

python-sdk/kiota-version.csproj
python-sdk/poetry.lock
python-sdk/pyproject.toml
python-sdk/tests/basic_test.py

The UX regression has been reported [here](https://github.com/microsoft/kiota/pull/3962).

Bump Kiota and dependencies of the Python SDK

---

utils/converter/src/main/resources/META-INF/services/org.apache.kafka.connect.storage.Converter

Add service loader manifests for Kafka Connect Converters

---

docs-playbook/.gitignore
docs-playbook/Dockerfile
docs-playbook/LICENSE
docs-playbook/README.md
docs-playbook/_build-all.sh
docs-playbook/build.sh
docs-playbook/docs-playbook.yml
docs-playbook/package-lock.json
docs-playbook/package.json
docs-playbook/search-playbook.yml
docs-playbook/supplemental_ui/css/search.css
docs-playbook/supplemental_ui/js/vendor/lunr.js
docs-playbook/supplemental_ui/js/vendor/search.js
docs-playbook/supplemental_ui/partials/footer-content.hbs
docs-playbook/supplemental_ui/partials/footer-scripts.hbs
docs-playbook/supplemental_ui/partials/head-meta.hbs
docs-playbook/supplemental_ui/partials/header-content-lunr.hbs

Moved from: https://github.com/Apicurio/apicurio-docs-playbook
The above repo will be archived.

Moved the docs playbook into apicurio-registry

---

.github/workflows/release.yaml

Forgot to propagate this change to the workflow:
https://github.com/Apicurio/apicurio-registry/commit/ee640b6c5f2854406e218b59a6cbb0b176e0613b
:sweat_smile:

Fix the PyPi release CI

---

app/src/main/java/io/apicurio/registry/rules/integrity/IntegrityRuleExecutor.java
ui/ui-app/src/app/pages/artifact/components/tabs/BranchesTable.tsx
ui/ui-app/src/app/pages/artifact/components/tabs/VersionsTable.tsx
ui/ui-app/src/app/pages/explore/components/toolbar/ExplorePageToolbar.tsx
ui/ui-app/src/services/useConfigService.ts

* https://github.com/Apicurio/apicurio-registry/issues/4473

Ensure inappropiate actions are hidden in UI read-only mode

---

java-sdk/pom.xml

Java 11 compatible SDK

---

ui/package-lock.json
ui/ui-app/package-lock.json
ui/ui-app/src/services/useConfigService.ts

Fixed the UI config for settings

---

pom.xml

This PR upgrades Avro to 1.11.4 to include critical big fixes

[2.5] Upgrade Avro to 1.11.4

---

README.md

Just copy an pasting this example did not work. The SNAPSHOT tag doesn't exist on the docker hub and the environment variable was also incorrect resulting in an error.

Changed example from readme

---

docs/modules/ROOT/partials/getting-started/ref-registry-serdes-config-props.adoc

Commit 2c6897ad86c8735129368cf4c5df7e81f6043193 moved the location of `SerdeConfig.java`. This PR adjusts sources to changes.

Update SerdeConfig reference

---

operator/controller/src/main/java/io/apicurio/registry/operator/feat/KafkaSql.java
operator/controller/src/main/java/io/apicurio/registry/operator/feat/PostgresSql.java
operator/controller/src/main/java/io/apicurio/registry/operator/resource/app/AppDeploymentResource.java

Follow up on the conversation on the other PR.
This gets Postgres configuration to use the shape of KafkaSql as agreed.

[chore] cleanup sql datasource

---

ui/ui-app/src/app/pages/artifact/ArtifactPage.tsx
ui/ui-app/src/app/pages/group/GroupPage.tsx

Fixes the following issue:
* https://github.com/Apicurio/apicurio-registry/issues/5460

Fixed a couple places where we were not URI encoding elements of nav links

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
app/src/main/java/io/apicurio/registry/storage/importing/v2/SqlDataUpgrader.java

Fixes:
* https://github.com/Apicurio/apicurio-registry/issues/5401

feat(import): Create missing groups when importing

---

app/src/main/java/io/apicurio/registry/storage/impl/kafkasql/KafkaSqlFactory.java

Fixes: 
* https://github.com/Apicurio/apicurio-registry/issues/5441

feat(kafka): Added a new config for the Kafka consumer group name

---

app/src/main/java/io/apicurio/registry/ccompat/rest/v7/ConfigResource.java
app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/ConfigResourceImpl.java
app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/v7/ConfluentCompatibilityConfigTest.java

Fixes:
* https://github.com/Apicurio/apicurio-registry/issues/5337

Implement the defaultToGlobal option in ccompat /config/:subject endpoint

---

common/src/main/resources/META-INF/openapi.json

need to add following to make example work
"contentType": "application/json",

make example work

---

operator/controller/src/main/java/io/apicurio/registry/operator/StatusUpdater.java
operator/controller/src/test/java/io/apicurio/registry/operator/it/StatusUpdaterTest.java

Still pretty primitive, but better than having TODOs :slightly_smiling_face:

Implementing an initial status handling

---

docs/modules/ROOT/partials/getting-started/proc-installing-registry-kafka-storage.adoc

fix typo in env var name

---

utils/maven-plugin/src/main/java/io/apicurio/registry/maven/AbstractRegistryMojo.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/DownloadRegistryMojo.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/RegisterRegistryMojo.java
utils/maven-plugin/src/main/java/io/apicurio/registry/maven/TestUpdateRegistryMojo.java

Workaround for #5683
I tested locally against the reproducer, to test the changes in CI we need a bit more infrastructure ...

Fix vertx failures in the maven plugin

---

operator/controller/src/main/java/io/apicurio/registry/operator/ApicurioRegistry3Reconciler.java
operator/controller/src/main/java/io/apicurio/registry/operator/StatusUpdater.java
operator/controller/src/test/java/io/apicurio/registry/operator/it/StatusUpdaterTest.java
operator/controller/src/test/java/io/apicurio/registry/operator/unit/StatusUpdaterTest.java

This should handle some cases of failing tests. These are minimal and quick changes since there is a plan to revisit this again soon.

refactor(operator): improve status conditions handling

---

app/src/main/java/io/apicurio/registry/rest/v3/SystemResourceImpl.java
app/src/main/java/io/apicurio/registry/ui/UserInterfaceConfigProperties.java
docs/modules/ROOT/partials/getting-started/ref-registry-all-configs.adoc

Part of porting https://github.com/Apicurio/apicurio-registry/pull/5926/files to 3.x.

Add scope value to the ui config properties

---

.github/workflows/release-images.yaml
.github/workflows/release-sdk-typescript.yaml
.github/workflows/release.yaml
go-sdk/Makefile
go-sdk/generate.sh
go-sdk/go-sdk.csproj
pom.xml
python-sdk/python-sdk.csproj
typescript-sdk/package.json

Fixes https://github.com/Apicurio/apicurio-registry/issues/5633

fix: build failure on aarch64 #5633

---

examples/simple-json/src/main/java/io/apicurio/registry/examples/simple/json/SimpleJsonSchemaExample.java

Fixes:
* https://github.com/Apicurio/apicurio-registry/issues/5969

We need to enable headers so that the bean type is sent for each kafka message

---

app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/CompatibilityResourceImpl.java
app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/v7/CompatibilityResourceTest.java
integration-tests/src/test/java/io/apicurio/tests/smokeTests/confluent/ConfluentConfigUtils.java
integration-tests/src/test/java/io/apicurio/tests/smokeTests/confluent/RulesResourceConfluentIT.java

Issue:
* https://github.com/Apicurio/apicurio-registry/issues/6089

(fix): Fix for issue #6089

---

app/src/main/java/io/apicurio/registry/rest/v2/GroupsResourceImpl.java
app/src/test/java/io/apicurio/registry/noprofile/Issue5713Test.java
schema-util/common/src/main/java/io/apicurio/registry/content/util/ContentTypeUtil.java

(fix): Implemented a fix for #5713

---

distro/docker/src/main/docker/Dockerfile.jvm
distro/docker/src/main/docker/Dockerfile.native
operator/controller/src/main/docker/Dockerfile.jvm
pom.xml
ui/Dockerfile

This PR upgrades the Quarkus version and also the base images, fixing some existing security issues.

Patch security issues

---

ui/ui-app/src/app/App.tsx

Fixes:
* https://github.com/Apicurio/apicurio-registry/issues/4948

(fix): Properly set the login redirect url

---

config-index/runtime/src/main/resources/META-INF/quarkus-extension.yaml

This fixes a startup exception.

Fix the metadata in the config index extension

---

examples/ai/apicurio-registry-mcp-server/README.md
examples/ai/apicurio-registry-mcp-server/pom.xml
examples/ai/apicurio-registry-mcp-server/src/main/java/io/apicurio/registry/mcp/Descriptions.java
examples/ai/apicurio-registry-mcp-server/src/main/java/io/apicurio/registry/mcp/ObjectMapperCustomizerImpl.java
examples/ai/apicurio-registry-mcp-server/src/main/java/io/apicurio/registry/mcp/RegistryService.java
examples/ai/apicurio-registry-mcp-server/src/main/java/io/apicurio/registry/mcp/Utils.java
examples/ai/apicurio-registry-mcp-server/src/main/java/io/apicurio/registry/mcp/servers/AdminMCPServer.java
examples/ai/apicurio-registry-mcp-server/src/main/java/io/apicurio/registry/mcp/servers/ArtifactsMCPServer.java
examples/ai/apicurio-registry-mcp-server/src/main/java/io/apicurio/registry/mcp/servers/GroupsMCPServer.java
examples/ai/apicurio-registry-mcp-server/src/main/java/io/apicurio/registry/mcp/servers/MCPPrompts.java
examples/ai/apicurio-registry-mcp-server/src/main/java/io/apicurio/registry/mcp/servers/SystemMCPServer.java
examples/ai/apicurio-registry-mcp-server/src/main/java/io/apicurio/registry/mcp/servers/VersionsMCPServer.java
examples/ai/apicurio-registry-mcp-server/src/main/resources/application.properties
examples/ai/apicurio-registry-mcp-server/src/test/java/io/apicurio/registry/mcp/DebugTest.java
examples/pom.xml

See README.md for more information.

feat(examples): implement a simple Apicurio Registry MCP server

---

.github/workflows/integration-tests.yaml

The integration test workflow is broken.  Trying to determine why.

chore(ci): Minor changes to the failing integration tests

---

app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractHandleFactory.java
app/src/main/java/io/apicurio/registry/storage/impl/sql/AbstractSqlRegistryStorage.java
integration-tests/src/test/java/io/apicurio/tests/converters/RegistryConverterIT.java
schema-resolver/pom.xml
schema-resolver/src/main/java/io/apicurio/registry/resolver/AbstractSchemaResolver.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/DefaultSchemaResolver.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/SchemaLookupResult.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/cache/ContentWithReferences.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/cache/ERCache.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/client/RegistryArtifactReference.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/client/RegistryClientFacade.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/client/RegistryClientFacadeImpl.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/client/RegistryClientFacadeImpl_v2.java
schema-resolver/src/main/java/io/apicurio/registry/resolver/strategy/ArtifactReference.java
schema-resolver/src/test/java/io/apicurio/registry/resolver/ERCacheTest.java
schema-util/common/src/main/java/io/apicurio/registry/content/AbstractContentHandle.java
schema-util/common/src/main/java/io/apicurio/registry/content/ContentHandle.java
schema-util/common/src/main/java/io/apicurio/registry/content/TypedContentImpl.java
utils/converter/src/main/java/io/apicurio/registry/utils/converter/avro/AvroData.java

NOTE: It seems the 3.x does not containe the changes made by bebcf820 PR#5637, but we can at least add the test.

fix: incorrect Avo converter caching (forwardport of 6fc6cc47)

---

app/src/main/java/io/apicurio/registry/ccompat/rest/v7/impl/ConfigResourceImpl.java
app/src/test/java/io/apicurio/registry/ccompat/rest/CCompatCompatibilityConfigTest.java
app/src/test/java/io/apicurio/registry/ccompat/rest/ForwardCompatModeProfile.java
app/src/test/java/io/apicurio/registry/noprofile/ccompat/rest/CCompatTestConstants.java

Testing old PR that should have already been merged:
* https://github.com/Apicurio/apicurio-registry/pull/5251

chore(merge): Test/merge change from snophey - ccompat compat bug

---

app/src/test/java/io/apicurio/registry/noprofile/Issue6530Test.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/FileDescriptorUtils.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtoContent.java
utils/protobuf-schema-utilities/src/main/java/io/apicurio/registry/utils/protobuf/schema/ProtobufSchemaLoader.java
utils/protobuf-schema-utilities/src/test/java/io/apicurio/registry/utils/protobuf/schema/ProtoContentTest.java

fix(protobuf): Improve protobuf validation/loading further

---

app/src/test/java/io/apicurio/registry/noprofile/serde/AvroSerdeTest.java
app/src/test/java/io/apicurio/registry/noprofile/serde/JsonSchemaSerdeTest.java
app/src/test/java/io/apicurio/registry/noprofile/serde/ProtobufSerdeTest.java
serdes/generic/serde-common-protobuf/src/main/java/io/apicurio/registry/serde/protobuf/MessageIndexesUtil.java
serdes/generic/serde-common-protobuf/src/main/java/io/apicurio/registry/serde/protobuf/ProtobufSerializer.java
serdes/generic/serde-common-protobuf/src/main/java/io/apicurio/registry/serde/protobuf/ProtobufSerializerConfig.java
serdes/generic/serde-common/src/main/java/io/apicurio/registry/serde/config/SerdeConfig.java

Compatibility between confluent and apicurio protobuf serdes.  Probably still some work to do, but we have a test for it now at least.

fix(protobuf-serde): Improved compatibility options for protobuf serde

---

app/src/main/java/io/apicurio/registry/rest/v3/GroupsResourceImpl.java
app/src/test/java/io/apicurio/registry/noprofile/rest/v3/DryRunTest.java

The dryRun parameter is not respected when using ifExists=FIND_OR_CREATE_VERSION in the createArtifact endpoint. When calling the endpoint with dryRun=true on an already-existing artifact, a new version is actually created and persisted instead of performing a true dry-run simulation, as described in https://github.com/Apicurio/apicurio-registry/issues/6670.
The cause is that the dryRun parameter is not being propagated through the method call chain in GroupsResourceImpl.java when handling the FIND_OR_CREATE_VERSION case.
Included is a new test for the specific ifExists=FIND_OR_CREATE_VERSION scenario, as well as fix to an existing test that used ifExists=CREATE_VERSION which was validating the buggy, unintended behavior.
Fixes https://github.com/Apicurio/apicurio-registry/issues/6670

Fix dryRun parameter handling in createArtifact with FIND_OR_CREATE_VERSION
